jumpscale/packages/admin/services/heartbeat.py, jumpscale/packages/tfgrid_solutions/scripts/threebot/monitoring_alert_handler.py, jumpscale/packages/tfgrid_solutions/scripts/threebot/register_dashboard.py
=> send owner tname instead of vdc tname to the logger

jumpscale/packages/vdc/chats/extend_k8s.py, jumpscale/packages/vdc/chats/new_vdc.py, jumpscale/sals/vdc/__init__.py, jumpscale/sals/vdc/deployer.py, jumpscale/sals/vdc/kubernetes.py, jumpscale/sals/vdc/models.py, jumpscale/sals/vdc/s3.py, jumpscale/sals/vdc/size.py, jumpscale/sals/vdc/threebot.py, jumpscale/sals/vdc/vdc.py
=> Development vdc dynamic info loading

jumpscale/packages/vdc_dashboard/frontend/components/base/Sidebar.vue, jumpscale/packages/vdc_dashboard/frontend/index.js
Changed order of kubernetes and s3 in dashboard sidebar
https://github.com/threefoldtech/vdc/issues/62
=> VDC dashboard sidebar ordering

jumpscale/packages/admin/services/heartbeat.py, jumpscale/packages/tfgrid_solutions/scripts/threebot/register_dashboard.py
=> Adds clean urls

jumpscale/clients/explorer/models.py, jumpscale/sals/vdc/deployer.py, jumpscale/sals/vdc/kubernetes.py
Replace k8s with kubernetes in VDC ui
Replace k8s with kubernetes in VDC ui 
https://github.com/threefoldtech/vdc/issues/56
=> replace k8s with kubernetes in vdc ui

jumpscale/packages/vdc/chats/new_vdc.py
Update vdc flavor massages
[vdc chatflow (packages info and essential input)](https://github.com/threefoldtech/vdc/issues/53)
=> Update vdc flavor massages

jumpscale/packages/vdc_dashboard/sals/solutions_chatflow.py
Changed vdc chatflow subdomain step messages as mentioned here https://github.com/threefoldtech/vdc/issues/68
=> Changed vdc chatflow subdomain step messages

jumpscale/packages/tfgrid_solutions/scripts/threebot/minimal_entrypoint.py, jumpscale/packages/vdc/billing.py, jumpscale/packages/vdc/chats/extend_k8s.py, jumpscale/packages/vdc/chats/new_vdc.py, jumpscale/packages/vdc/services/provision_wallet_billing.py, jumpscale/packages/vdc_dashboard/frontend/components/base/Sidebar.vue, jumpscale/packages/vdc_dashboard/frontend/index.js, jumpscale/packages/vdc_dashboard/sals/vdc_dashboard_sals.py, jumpscale/sals/vdc/deployer.py, jumpscale/sals/vdc/kubernetes.py, jumpscale/sals/vdc/proxy.py, jumpscale/sals/vdc/threebot.py, jumpscale/sals/vdc/vdc.py
Capitalize VDC in all strings and frontend
=> Capitalize VDC in all strings and frontend

jumpscale/tools/zos/reporting/__init__.py
=> add tool to report pub ips status

jumpscale/packages/vdc_dashboard/sals/solutions_chatflow.py
- Fix choose custom subdomain step
- [Marketplace chatflow selecting domain](https://github.com/threefoldtech/vdc/issues/73)
=> Fix choose custom subdomain step

jumpscale/packages/tfgrid_solutions/scripts/threebot/minimal_entrypoint.py, jumpscale/sals/vdc/deployer.py
use vdc_uuid in identity tname
=> Development vdc unique identities

jumpscale/packages/vdc/chats/new_vdc.py, jumpscale/packages/vdc_dashboard/bottle/deployments.py, jumpscale/packages/vdc_dashboard/frontend/api.js, jumpscale/packages/vdc_dashboard/frontend/components/base/Kubernetes.vue, jumpscale/packages/vdc_dashboard/frontend/components/base/S3.vue
- move s3 exposed link to the end of chatflow
- add button for the s3 url in the vdc dashboard
- https://github.com/threefoldtech/vdc/issues/79
=> Development vdc S3 expose

jumpscale/packages/vdc_dashboard/chats/zeroci.py, jumpscale/packages/vdc_dashboard/frontend/data.js
- Added zeroCI chatflow
- Allowed the solution in the frontend
- [Create helm chart for zeroci](https://github.com/threefoldtech/vdc/issues/46)
=> Add zeroCI chatflow

jumpscale/packages/vdc_dashboard/bottle/deployments.py
=> fix s3 expose in vdc dashboard

jumpscale/packages/vdc/chats/new_vdc.py, jumpscale/packages/vdc_dashboard/chats/extend_k3s.py, jumpscale/packages/vdc_dashboard/chats/extend_kubernetes.py, jumpscale/packages/vdc_dashboard/frontend/components/base/Kubernetes.vue
- move extend chatflow to vdc dashboard
- fix extend chatflow
- rename k8s to k3s
- https://github.com/threefoldtech/vdc/issues/83
=> fix add node in vdc dashboard

jumpscale/packages/vdc_dashboard/chats/extend_kubernetes.py
with k8s extension chatflow on vdc_dashborad, there is no more initialization wallet. so instead pay the first hour of capacity with prepaid wallet
=> Development extend k8s payment

jumpscale/packages/vdc/frontend/components/base/Table.vue
=> fix vdc urls in deployer

jumpscale/packages/vdc_dashboard/chats/extend_kubernetes.py
=> fix extend kubernetes chatflow

jumpscale/packages/vdc/chats/new_vdc.py
remove expose s3 as it's available in the dashboard
to reduce steps
- https://github.com/threefoldtech/vdc/issues/88
=> remove expose s3 as it's available in the dashboard

jumpscale/packages/vdc_dashboard/chats/taiga.py, jumpscale/packages/vdc_dashboard/frontend/data.js
=> Add taiga chatflow

jumpscale/packages/vdc_dashboard/chats/peertube.py, jumpscale/packages/vdc_dashboard/frontend/data.js, jumpscale/sals/kubernetes/manager.py
- Add vdc peerutbe.
- Quote the params sent in helm installation command line
=> Add peertube chatflow

jumpscale/sals/vdc/deployer.py
=> Update the exception message when there's not enough resources

jumpscale/packages/tfgrid_solutions/scripts/threebot/minimal_entrypoint.py, jumpscale/sals/vdc/deployer.py, jumpscale/sals/vdc/kubernetes.py, jumpscale/sals/vdc/scheduler.py, jumpscale/sals/vdc/vdc.py
- sort nodes based on wights
- retry explorer pool calls (they fail due to stellar on the explorer side)
=> Development vdc node order

jumpscale/packages/tfgrid_solutions/scripts/threebot/minimal_entrypoint.py, jumpscale/packages/vdc/bottle/api.py, jumpscale/packages/vdc/chats/new_vdc.py, jumpscale/packages/vdc_dashboard/chats/extend_kubernetes.py, jumpscale/packages/vdc_dashboard/chats/monitoring_stack.py, jumpscale/packages/vdc_dashboard/frontend/components/base/Kubernetes.vue, jumpscale/packages/vdc_dashboard/frontend/components/base/S3.vue, jumpscale/packages/vdc_dashboard/frontend/components/base/Sidebar.vue, jumpscale/packages/vdc_dashboard/frontend/data.js, jumpscale/sals/vdc/deployer.py, jumpscale/sals/vdc/kubernetes.py, jumpscale/sals/vdc/size.py, jumpscale/sals/vdc/threebot.py, jumpscale/sals/vdc/vdc.py
- Rename s3 to storage nodes / expose s3 to expose storage controller
- Disable monitoring stack to be installed by default and add it to marketplace
- Remove Storage nodes actions
=> Development vdc monitoringstack

jumpscale/packages/tfgrid_solutions/scripts/threebot/minimal_entrypoint.py, jumpscale/packages/vdc_dashboard/chats/extend_kubernetes.py, jumpscale/packages/vdc_dashboard/chats/monitoring_stack.py, jumpscale/sals/vdc/deployer.py, jumpscale/sals/vdc/threebot.py
- fix kubernetes extension
- some different fixes accross vdc sals and deployer
- https://github.com/threefoldtech/vdc/issues/96
=> Development vdc fixextend

jumpscale/packages/vdc_dashboard/bottle/deployments.py, jumpscale/packages/vdc_dashboard/sals/vdc_dashboard_sals.py, jumpscale/sals/kubernetes/manager.py
- change the listing command to use kubectl with`-l` option
- Add validation for variables in parsing data
- Use /root/,kube/config in vdc_dashboard_sals and helm delete chart
=> Fix listing charts

jumpscale/packages/chatflows/actors/chatbot.py
- Fix packages chatflow engine loading
- fix variables override 
- https://github.com/threefoldtech/js-sdk/issues/1745
=> fix package chats loading

jumpscale/packages/vdc/bottle/api.py, jumpscale/packages/vdc/chats/new_vdc.py
clean vdc instances when the name is reused not on listing
=> clean old vdc instances on reuse only

jumpscale/sals/billing/billing.py, jumpscale/sals/billing/models.py, jumpscale/sals/billing/test_billing.py, jumpscale/sals/vdc/vdc.py
- add info logs in billing code
- allow refund by a specific amount
- add a description field to payments
=> logging billing operations

jumpscale/packages/vdc_dashboard/chats/gitea.py, jumpscale/packages/vdc_dashboard/frontend/data.js
- add gitea chatflow
[gitea chart](https://github.com/threefoldtech/vdc/issues/37)
=> Add gitea chatflow

docs/wiki/identity.md, docs/wiki/marketplace/deployment.md, docs/wiki/threebot_deployer/threebot_deployer.md, jumpscale/packages/auth/__init__.py, jumpscale/packages/auth/bottle/auth.py, jumpscale/packages/auth/bottle/templates/login.html, jumpscale/packages/tfgrid_solutions/scripts/threebot/entrypoint.py, jumpscale/packages/threebot_deployer/bottle/utils.py, jumpscale/packages/threebot_deployer/chats/threebot.py, jumpscale/packages/threebot_deployer/models/user_solutions.py, jumpscale/sals/reservation_chatflow/deployer.py, jumpscale/sals/reservation_chatflow/reservation_chatflow.py, tests/frontend/tests/base_tests.py
- Drop the 3bot import from another network functionality
- typo in 3bot deployer
- A testnet 3bot should not have a mainnet identity and vice versa
- Change text on button to TF Connect
- https://github.com/threefoldtech/js-sdk/issues/1793
- https://github.com/threefoldtech/js-sdk/issues/1826
- https://github.com/threefoldtech/js-sdk/issues/1689
- https://github.com/threefoldtech/js-sdk/issues/1799
=> Development threebotdeployer improvments

jumpscale/packages/auth/bottle/auth.py
lower username before storing it in the session
workaround: https://github.com/threefoldtech/3Bot_connect/issues/179
=> workaround threebot connect 

jumpscale/packages/admin/actors/wallet.py, jumpscale/packages/admin/frontend/components/dashboard/Dashboard.vue, jumpscale/packages/admin/frontend/components/wallets/Wallet.vue
Fixes #1823 and #1822
after accepting 
and for invalid wallets
=> remove new wallet shortcut and handle wallet details properly

jumpscale/packages/admin/frontend/components/wallets/Wallets.vue
in case other networks
in case of testnet 
fixes #1800
=> Remove testnet funded wallet for all networks except for testnet explorers

.github/workflows/build_image_with_trc.yml, jumpscale/install/Dockerfile, jumpscale/install/rootfs/etc/zinit/start.yaml, jumpscale/install/rootfs/etc/zinit/trc.yaml
Add workflow to create an image with trc
=> Add workflow to create an image with trc

jumpscale/packages/vdc/bottle/api.py, jumpscale/packages/vdc/chats/new_vdc.py, jumpscale/sals/vdc/deployer.py, jumpscale/sals/vdc/threebot.py, jumpscale/sals/vdc/vdc.py
- run trc inside vdc 3bot
- allow 0 plan prices
=> Development vdc embed trc

jumpscale/packages/admin/actors/admin.py
=> enable AUTO_EXTEND_POOLS by default

jumpscale/packages/vdc/chats/new_vdc.py
=> add more descriptive size for vdcs

jumpscale/packages/vdc_dashboard/bottle/deployments.py, jumpscale/packages/vdc_dashboard/frontend/api.js, jumpscale/packages/vdc_dashboard/frontend/components/vdcSettings/Delete.vue, jumpscale/packages/vdc_dashboard/frontend/components/vdcSettings/Kubernetes.vue, jumpscale/sals/vdc/kubernetes.py
- Fix delete worker
https://user-images.githubusercontent.com/10658229/102903862-92d38780-4479-11eb-90bc-b118ca9db658.mp4
=> fix delete worker from the vdc dashboard

jumpscale/packages/vdc/billing.py, jumpscale/sals/vdc/deployer.py, jumpscale/sals/vdc/kubernetes.py, jumpscale/sals/vdc/threebot.py, jumpscale/sals/vdc/vdc.py
use actual vdc pools expiration instead of stored config
=> get expiration date from pools not stored config

jumpscale/packages/vdc/billing.py, jumpscale/packages/vdc/services/grace_period_service.py, jumpscale/sals/vdc/deployer.py, jumpscale/sals/vdc/grace_period.py, jumpscale/sals/vdc/vdc.py
- check grace period
- pools exiration is set to lower than 2 days (configurable)
- prepaid wallet has less than one hour to cover resources
- apply grace period
- extend pools for 2 weeks (renew plan)
- save vdc to be in grace period
- apply action
- actions during grace period
- check hourly for balance (prepaid):
- deduce tokens until it covers the grace period
- revert grace period
- revert of grace period
- revert action to normal
- Simulation scenario
```
JS-NG> aa = GRACE_PERIOD_FACTORY.get("vdc_devnet_magidentfinal_1608813818")                          
JS-NG> aa                                                                                            
GracePeriodModel(
instance_name='vdc_devnet_magidentfinal_1608813818',
vdc_instance_name='vdc_devnet_magidentfinal', …
```
=> init work for adding grace period and services

jumpscale/servers/threebot/threebot.py
=> Handle the lingering packages after switching branches

jumpscale/packages/vdc_dashboard/chats/cryptpad.py, jumpscale/packages/vdc_dashboard/chats/discourse.py, jumpscale/packages/vdc_dashboard/chats/gitea.py, jumpscale/packages/vdc_dashboard/chats/mattermost.py, jumpscale/packages/vdc_dashboard/chats/peertube.py, jumpscale/packages/vdc_dashboard/chats/taiga.py, jumpscale/packages/vdc_dashboard/chats/zeroci.py, jumpscale/sals/kubernetes/manager.py, jumpscale/sals/vdc/deployer.py, jumpscale/sals/vdc/threebot.py
=> Development vdc traefik upgrade

jumpscale/packages/admin/frontend/components/packages/Package.vue
Fixes https://github.com/threefoldtech/js-sdk/issues/1847
darkmode
light mode
=> Update chatflows icon in package card to mdi-chat

jumpscale/sals/vdc/threebot.py
=> Fix sdk version after merge

jumpscale/sals/vdc/deployer.py
Fix traefik_installed method call
=> Fix traefik_installed method call

jumpscale/sals/vdc/deployer.py
Fix is_traefik_installed method
=> Fix is_traefik_installed method

jumpscale/packages/admin/actors/admin.py, jumpscale/packages/admin/frontend/components/settings/AddIdentity.vue
=> support devnet in addidenttiy dialog

jumpscale/packages/vdc/bottle/api.py, jumpscale/packages/vdc/frontend/api.js, jumpscale/packages/vdc/frontend/components/solutions/Delete.vue, jumpscale/packages/vdc/frontend/components/solutions/Workloads.vue
=> add action to delete vdc

jumpscale/packages/tfgrid_solutions/scripts/threebot/entrypoint.py, jumpscale/packages/threebot_deployer/bottle/utils.py, jumpscale/packages/threebot_deployer/chats/threebot.py, jumpscale/packages/threebot_deployer/models/user_solutions.py, jumpscale/sals/marketplace/deployer.py
- Embed TRC with 3bot container
- Use ca ACME server for zero ssl certificate
=> Development embed threebot trc

jumpscale/packages/farmmanagement/actors/farm_management.py
Fixes https://github.com/threefoldtech/js-sdk/issues/1838
=> make explorer property in farmmgmt actor to reflect the active identity

jumpscale/packages/threebot_deployer/chats/threebot.py, jumpscale/sals/reservation_chatflow/deployer.py
- Remove trc container usage
- use models from explorer
- https://github.com/threefoldtech/js-sdk/issues/1827
=> use the correct size and models for calculating units

jumpscale/packages/vdc_dashboard/chats/discourse.py, jumpscale/packages/vdc_dashboard/sals/solutions_chatflow.py
=> Adds discourse smtp settings

jumpscale/packages/threebot_deployer/bottle/utils.py, jumpscale/packages/threebot_deployer/chats/change_location.py, jumpscale/packages/threebot_deployer/chats/change_size.py, jumpscale/packages/threebot_deployer/chats/restart_threebot.py, jumpscale/sals/marketplace/apps_chatflow.py, jumpscale/sals/reservation_chatflow/deployer.py
- fix 3bot extension and restart
- wait on subdomain deletion to avoid gateway caching 
- remove trc from the query of extension
- https://github.com/threefoldtech/js-sdk/issues/1879
=> fix subdomain deletion waiting

jumpscale/packages/vdc/chats/new_vdc.py
- show prices plans in the chatflow
=> show plans prices in the chatflow

jumpscale/packages/tfgrid_solutions/chats/flist.py, jumpscale/packages/tfgrid_solutions/chats/ubuntu.py, jumpscale/packages/threebot_deployer/chats/change_size.py, jumpscale/packages/threebot_deployer/chats/restart_threebot.py, jumpscale/sals/marketplace/apps_chatflow.py, jumpscale/sals/marketplace/deployer.py, jumpscale/sals/reservation_chatflow/deployer.py
- use threebot deployer sizes from explorer models
- some fixes to queries
- Extension done OK
at creation time
after extending
- https://github.com/threefoldtech/js-sdk/issues/1827
=> use threebot deployer sizes from explorer models

docs/wiki/tutorials/taiga_client.md, jumpscale/clients/taiga/models.py, jumpscale/clients/taiga/taiga.py
Fix and Enhancement in Taiga client, specially in the listing part
- Add **copy issue** function from circle to other one, modify move also to get all the issue info not the subject only
- Fix listing issue "Taiga API issue" by add a **full_info** attribute to all listing functions to get the whole info for each object
- Modify taiga tutorial and docstring according to the last enhancement  
Fixes #1898
Fixes #1899
=> Improve and Fix in Taiga Client

jumpscale/packages/vdc_dashboard/frontend/components/vdcSettings/Home.vue
=> Update vdc icons

jumpscale/packages/vdc_dashboard/chats/cryptpad.py, jumpscale/packages/vdc_dashboard/chats/discourse.py, jumpscale/packages/vdc_dashboard/chats/gitea.py, jumpscale/packages/vdc_dashboard/chats/mattermost.py, jumpscale/packages/vdc_dashboard/chats/peertube.py, jumpscale/packages/vdc_dashboard/chats/taiga.py, jumpscale/packages/vdc_dashboard/chats/zeroci.py, jumpscale/packages/vdc_dashboard/sals/solutions_chatflow.py
Moved  certresolver chart config to be in base chatflow sals instead of duplicating it in every chart
=> Move certresolver chart config to base chatflow

jumpscale/packages/tfgrid_solutions/chats/flist.py, jumpscale/packages/tfgrid_solutions/chats/ubuntu.py
- fix ubuntu ,flist chatflow uses query instead of resources
=> fix ubuntu chatflow

jumpscale/sals/marketplace/apps_chatflow.py, jumpscale/sals/marketplace/deployer.py
vdc 3Bot domains will be in `[vdcdev.grid.tf, vdctest.grid.tf, vdcmain.grid.tf]`
3bot deployer domains will be in `[3botdev.grid.tf, 3bottest.grid.tf, 3botmain.grid.tf]`
solutions domains will be in `[webg1dev.grid.tf, webg2dev.grid.tf, webg1test.grid.tf, webg2test.grid.tf, webg1main.grid.tf, webg2main.grid.tf]`
=> set domains for solutions and deployers

jumpscale/packages/vdc/chats/new_vdc.py
- wait on vdc 3bot container initalization
- https://github.com/threefoldtech/js-sdk/issues/2032
=> add vdc 3bot initaliztion

jumpscale/sals/vdc/deployer.py
Allow traefik chart http redirect to https
https://github.com/threefoldtech/js-sdk/issues/2037
=> Traefik chart http redirect to https

jumpscale/packages/admin/frontend/components/wallets/Wallet.vue
Fix the error check in showing the wallet details.
=> Fix show wallet details

jumpscale/sals/reservation_chatflow/reservation_chatflow.py
- list only std wallets in deployments
- https://github.com/threefoldtech/js-sdk/issues/2059
=> list only std wallets in deployments

jumpscale/packages/marketplace/package.py
- upgrade marketplace package to use STD wallet
- https://github.com/threefoldtech/js-sdk/issues/2061
=> upgrade marketplace package to use STD wallet

jumpscale/packages/polls/package.py
- update polls package to use STD wallet
=> migrate polls package to use STD wallet

docs/wiki/tutorials/add_funds_to_wallet.md, docs/wiki/tutorials/add_funds_to_wallet_dashboard.md, docs/wiki/tutorials/deploy_ubuntu_container.md
- update docs to be ready for std network
- https://github.com/threefoldtech/js-sdk/issues/2066
=> update docs to be ready for std network

jumpscale/sals/reservation_chatflow/reservation_chatflow.py, jumpscale/sals/vdc/wallet.py
- upgrade vdc package to use STD wallets only
- https://github.com/threefoldtech/js-sdk/issues/2060
=> upgrade vdc wallets to be mainnet only

docs/architecture/decisions/0017-migrate-testnet-devnet-to-use-std-stellar-wallet.md
create adr for migrating from TEST stellar wallets to STD
=> create adr for migrating from TEST stellar wallets to STD

jumpscale/packages/threebot_deployer/chats/threebot.py
=> allow 3bot devnet

jumpscale/packages/tfgrid_solutions/scripts/threebot/entrypoint.py, jumpscale/packages/threebot_deployer/chats/threebot.py
=> fix 3bot on devnet

jumpscale/sals/billing/billing.py, jumpscale/sals/vdc/size.py, jumpscale/sals/vdc/vdc.py
Apply the discount on the vdc prices returned from the explorer and add a note with it in the payment screen.
https://github.com/threefoldtech/js-sdk/issues/2081
=> apply and show discount message on payment page

docs/architecture/decisions/0018-change-domain-names-to-shorter-ones.md, jumpscale/sals/marketplace/apps_chatflow.py
- change threebot domain names to shorter ones
**_Check the attached ADR_**
=> change threebot domain names to shorter ones

jumpscale/sals/vdc/deployer.py, jumpscale/sals/vdc/vdc.py
- round price and remove trc container
=> round price and remove trc container

jumpscale/sals/vdc/wallet.py
- to make wallet initalizations easier
=> init wallet can be used from config manager

jumpscale/clients/stellar/stellar.py
Does the activation of the wallets directly from activation_wallet, otherwise it goes to the threefold services
=> add activation wallet

jumpscale/clients/stellar/stellar.py
enables merge accounts feature
=> support merge into account

jumpscale/packages/vdc/chats/new_vdc.py, jumpscale/sals/vdc/deployer.py
removes network name, as the domain will already reflect that
=> shorter vdc names

jumpscale/sals/marketplace/apps_chatflow.py
reduce numbers to be readble in domains
=> reduce numbers to be readble in domains

jumpscale/packages/tfgrid_solutions/scripts/threebot/minimal_entrypoint.py
This reverts commit bb172e3b38b39d746f1fcb345965d0a03bfea36a.
=> Revert "Don't fail in 3bot entrypoint if run twice (#2035)"

jumpscale/clients/stellar/__init__.py, jumpscale/packages/vdc/chats/new_vdc.py
Don't start the vdc chatflow unless there're more than 15 xlms in the activation service wallet.
https://github.com/threefoldtech/js-sdk/issues/2080
=> check activation wallet balance before deploying vdcs

jumpscale/clients/stellar/stellar.py, jumpscale/packages/vdc/chats/new_vdc.py, jumpscale/packages/vdc_dashboard/chats/extend_kubernetes.py, jumpscale/sals/vdc/size.py, jumpscale/sals/vdc/threebot.py
=> Development vdc nodespecs

jumpscale/sals/vdc/vdc.py
- update discount message
- [https://github.com/threefoldtech/js-sdk/issues/2107](https://github.com/threefoldtech/js-sdk/issues/2107)
=> update discount message

jumpscale/packages/vdc_dashboard/chats/monitoring_stack.py, jumpscale/packages/vdc_dashboard/chats/monitoringstack.py, jumpscale/packages/vdc_dashboard/frontend/components/marketplace/Home.vue, jumpscale/packages/vdc_dashboard/frontend/data.js, jumpscale/packages/vdc_dashboard/sals/solutions_chatflow.py
Fixes for grafana / prometheus
=> Development vdc monitorstack

jumpscale/clients/stellar/stellar.py
=> implement new activation mechanism with sponsored accounts

jumpscale/packages/vdc_dashboard/chats/blog.py, jumpscale/packages/vdc_dashboard/chats/publisher.py, jumpscale/packages/vdc_dashboard/chats/website.py, jumpscale/packages/vdc_dashboard/chats/wiki.py
Update publisher chatflows to use charts (Still not tested).
Update publisher/website/blog/wiki chatflows of `vdc_dashboard` package.
#2084
=> update publishingtools chatflows to use charts

jumpscale/packages/admin/frontend/components/base/Dialog.vue
- Fix Uncaught RangeError in the base dialog
- https://github.com/threefoldtech/js-sdk/issues/1837
=> Fix Uncaught RangeError in the base dialog

jumpscale/packages/vdc_dashboard/chats/kubeapps.py, jumpscale/packages/vdc_dashboard/sals/vdc_dashboard_sals.py
- Generate the access token for `kubeaps` 
- Add minor fixes for the chart
- Fixing an issue related to listing the solutions in the market place
https://github.com/threefoldtech/js-sdk/issues/2103
=> Development vdc kubeapps fixes

jumpscale/packages/admin/frontend/index.html, jumpscale/packages/chatflows/frontend/index.html, jumpscale/packages/marketplace/frontend/index.html, jumpscale/packages/threebot_deployer/frontend/index.html, jumpscale/packages/vdc/frontend/index.html, jumpscale/packages/vdc_dashboard/frontend/index.html
- Change vuetify version to 2.3
=> Change vuetify version to 2.3

jumpscale/clients/explorer/models.py, jumpscale/clients/explorer/pools.py, jumpscale/sals/vdc/deployer.py, jumpscale/sals/zos/pools.py
=> add pool payment (#2135)

jumpscale/packages/vdc_dashboard/frontend/components/vdcSettings/S3.vue
=> Update zstor config data

jumpscale/clients/explorer/models.py, jumpscale/clients/explorer/pools.py, jumpscale/packages/threebot_deployer/chats/change_location.py, jumpscale/sals/marketplace/apps_chatflow.py, jumpscale/sals/marketplace/deployer.py, jumpscale/sals/reservation_chatflow/deployer.py, jumpscale/sals/zos/pools.py
https://github.com/threefoldtech/js-sdk/issues/2151
=> wait for pool payments

jumpscale/sals/marketplace/deployer.py
- units to be integer only
- https://github.com/threefoldtech/js-sdk/issues/2147
=> fix threebot restart

jumpscale/clients/stellar/stellar.py, jumpscale/packages/threebot_deployer/chats/threebot.py, jumpscale/sals/marketplace/apps_chatflow.py, jumpscale/sals/marketplace/deployer.py
- retry stellar payments in 3bot and apps
- https://github.com/threefoldtech/js-sdk/issues/2152
=> retry stellar payments in 3bot and apps

jumpscale/clients/stellar/stellar.py
- retry transfer in stellar client
=> retry transfer in stellar client

jumpscale/packages/admin/actors/admin.py, jumpscale/packages/admin/frontend/api.js, jumpscale/packages/admin/frontend/components/settings/Settings.vue
- https://github.com/threefoldtech/js-sdk/issues/2154
=> add option to clear blocked domains

jumpscale/packages/chatflows/frontend/mixins/field.js, jumpscale/packages/threebot_deployer/chats/threebot.py
- Move the duplication check of threebot name to the frontend 
- Add not_exist validator to string_ask
- [https://github.com/threefoldtech/js-sdk/issues/2149](https://github.com/threefoldtech/js-sdk/issues/2149)
=> Move the duplication check of threebot name to the frontend

jumpscale/packages/admin/frontend/components/pools/Pools.vue
- Fix units per month
- https://github.com/threefoldtech/js-sdk/issues/2167
=> fix pools view to be per month

jumpscale/packages/vdc_dashboard/sals/solutions_chatflow.py, jumpscale/sals/vdc/kubernetes_auto_extend.py
extend the cluster before solution deployment if it can be extended according to the vdc spec
https://github.com/threefoldtech/js-sdk/issues/2123
=> Development vdc solution cluster extension

docs/architecture/decisions/0019-use-custom-activation-wallet-for-threebot-deployers.md, jumpscale/clients/stellar/__init__.py, jumpscale/clients/stellar/stellar.py, jumpscale/entry_points/threebot.py, jumpscale/packages/admin/actors/wallet.py, jumpscale/packages/tfgrid_solutions/scripts/threebot/entrypoint.py, jumpscale/packages/tfgrid_solutions/scripts/threebot/entrypoint.sh, jumpscale/packages/tfgrid_solutions/scripts/threebot/initialize.sh, jumpscale/packages/threebot_deployer/bottle/utils.py, jumpscale/packages/threebot_deployer/chats/threebot.py
- In case of threebot fails to activate its wallet via threefold service it'll activate using own activation wallet
- Wallet will be created on the deployer and then the secret will be passed to the entrypoint as a secret env
- more info in the adr
- https://github.com/threefoldtech/js-sdk/issues/2180
=> Development custom activation wallet

jumpscale/packages/vdc_dashboard/bottle/deployments.py, jumpscale/packages/vdc_dashboard/frontend/api.js, jumpscale/packages/vdc_dashboard/frontend/components/marketplace/Home.vue, jumpscale/packages/vdc_dashboard/frontend/components/marketplace/Solution.vue, jumpscale/packages/vdc_dashboard/sals/vdc_dashboard_sals.py
Add option to view all deployed workloads on vdc other than selecting the type for each
Add option to view all deployed workloads on vdc other than selecting the type for each
https://github.com/threefoldtech/js-sdk/issues/2162
=> Development vdc listing solutions

jumpscale/packages/vdc_dashboard/frontend/components/vdcSettings/Home.vue
update VDC wallet message
- https://github.com/threefoldtech/js-sdk/issues/1934#issuecomment-758510125
=> update VDC wallet  message

jumpscale/packages/threebot_deployer/chats/threebot.py
Don't rais an error if duplicated identity name
- https://github.com/threefoldtech/js-sdk/issues/2149#issuecomment-758520408
=> Don't rais an error if duplicated identity name for the new 3Bot

jumpscale/packages/vdc_dashboard/frontend/components/vdcSettings/Home.vue
Update Expire msg (Wallet low balance warning) to be in days and hours
#1934
=> Update expire msg (days and hours)

jumpscale/packages/tfgrid_solutions/scripts/threebot/entrypoint.py
- Make sure secret is passed correctly
=> fix wallet in entrypoint if not created on the deployer

jumpscale/sals/kubernetes/manager.py, jumpscale/sals/vdc/kubernetes.py
Add a method to add a new entrypoint or override an existing one in the cluster's traefik ingress controller.
=> Traefik entrypoint sal method 

jumpscale/packages/vdc_dashboard/bottle/deployments.py, jumpscale/packages/vdc_dashboard/frontend/api.js, jumpscale/packages/vdc_dashboard/frontend/components/vdcSettings/S3.vue
- Add zbd passwords to the config file
- https://github.com/threefoldtech/js-sdk/issues/2186
=> Add zbd passwords to the config file

jumpscale/packages/threebot_deployer/bottle/utils.py
- use greenlets to threebot listing, it will reduce the listing time a lot
- https://github.com/threefoldtech/js-sdk/issues/2207
=> use greenlets to threebot listing

jumpscale/clients/explorer/workloads.py, jumpscale/packages/tfgrid_solutions/actors/solutions.py, jumpscale/sals/zos/workloads.py
- list workloads by using gevent to be faster at least 2x
- https://github.com/threefoldtech/js-sdk/issues/1814
=> list workloads by using gevent to be faster

jumpscale/packages/vdc_dashboard/bottle/deployments.py, jumpscale/packages/vdc_dashboard/frontend/api.js, jumpscale/packages/vdc_dashboard/frontend/components/vdcSettings/Home.vue, jumpscale/packages/vdc_dashboard/frontend/components/vdcSettings/S3.vue
- Add zdb passwords to the JSON file
- Fix VDC wallet warning
- https://github.com/threefoldtech/js-sdk/issues/1934
- https://github.com/threefoldtech/js-sdk/issues/2239
=> VDC: Add zdbs password and fix Wallet warning

jumpscale/packages/auth/static/css/style.css
Fix login page background
[#901](https://github.com/threefoldtech/js-sdk/issues/901)
=> Fix login page bg

jumpscale/packages/vdc_dashboard/sals/solutions_chatflow.py
ignore domain operations if the domain step is not executed
Tested on taiga, mattermost, and a domainless solution.
https://github.com/threefoldtech/js-sdk/issues/2242
=> ignore domain operations if the domain step is not executed

jumpscale/packages/threebot_deployer/frontend/components/solutions/ActionConfirmation.vue, jumpscale/packages/threebot_deployer/frontend/components/solutions/Delete.vue, jumpscale/packages/threebot_deployer/frontend/components/solutions/Stop.vue
Updated confirmation messages to be configurable in threebot deployer
https://github.com/threefoldtech/js-sdk/issues/2234
=> Update action confiramtion messages in 3bot deployer

jumpscale/sals/marketplace/deployer.py
- Add sanity check for misconfigured gateways in case the farm was moved or deleted!
- https://github.com/threefoldtech/js-sdk/issues/2264
=> sanity check for misconfigured gateways

jumpscale/packages/vdc_dashboard/sals/solutions_chatflow.py, jumpscale/sals/kubernetes/manager.py
- Remove duplication code in kubernetes client
=> Remove duplication code in kubernetes client

jumpscale/sals/marketplace/deployer.py
- add method to clean user pools
- https://github.com/threefoldtech/js-sdk/issues/2270
=> add method to clean user pools

jumpscale/sals/reservation_chatflow/deployer.py
- fix subdomain deletion in dry run by passing the identity
=> fix subdomain deletion in dry run by passing the identity

jumpscale/packages/vdc_dashboard/sals/solutions_chatflow.py
- Moved the release name duplication check to the frontend
- https://github.com/threefoldtech/js-sdk/issues/2275
=> Moved the release name duplication check to the frontend

jumpscale/packages/threebot_deployer/chats/change_location.py, jumpscale/packages/threebot_deployer/chats/change_size.py, jumpscale/packages/threebot_deployer/chats/restart_threebot.py, jumpscale/packages/threebot_deployer/chats/threebot.py, jumpscale/sals/marketplace/apps_chatflow.py
- always use current branch instead of hardcoding it
- https://github.com/threefoldtech/js-sdk/issues/2274
=> always use current branch instead of hardcoding it

poetry.lock, pyproject.toml
=> bump version for jsng for 11.0b12

docs/architecture/decisions/0020-dynamically-get-branch-for-threebot-deployer.md, docs/architecture/decisions/0021-wait-for-pool-payments.md
- add adr for getting 3bot deployer branch
- add adr for wait pool payment
=> add adr for getting 3bot deployer branch

jumpscale/packages/vdc_dashboard/chats/blog.py, jumpscale/packages/vdc_dashboard/chats/website.py, jumpscale/packages/vdc_dashboard/chats/wiki.py
Update source directory defaults in website and wiki chatflows and remove it for blog as it's no effect.
=> publishingtools: update source directory defaults

jumpscale/clients/github/github.py, jumpscale/clients/github/helper.py, jumpscale/clients/github/repo.py, tests/clients/github/test_github.py
=> Fix github tests (#2287)

jumpscale/packages/vdc_dashboard/frontend/data.js
Enable blog, website and wiki in apps collection.
=> enable blog, website and wiki solutions

jumpscale/sals/vdc/s3_auto_topup.py
fix auto-extend zdb in listing
#2299
=> fix auto-extend zdb in listing

tests/servers/threebot/test_threebot.py
Use farm management instead of the marketplace package to not create a wallet in the test
=> Fix add package test

jumpscale/sals/kubernetes/manager.py
Clarify its usage and make the namespace and the yaml config optional.
=> Traefik upgrade docsting

jumpscale/tools/servicemanager/servicemanager.py
1. Remove scheduled services before stopping the running ones
2. Add logging
3. Remove signal handler since the rack server already handles them and calls the service manager stop method.
https://github.com/threefoldtech/js-sdk/issues/2246
=> remove scheduled before stopping running and add logging

jumpscale/packages/vdc_dashboard/sals/solutions_chatflow.py
use the logged in username
https://github.com/threefoldtech/js-sdk/issues/2320
=> Development fix solution username

jumpscale/packages/threebot_deployer/chats/threebot.py
fail if no nodes available instead of showing empty drop down
https://github.com/threefoldtech/js-sdk/issues/2318
=> fail if no nodes available

jumpscale/sals/marketplace/deployer.py, jumpscale/sals/reservation_chatflow/deployer.py
allow users to create/extend pools with ipv4us in admin dashboard
=> add ipv4us to pools chatflows

jumpscale/sals/chatflows/chatflows.py
add more description in chatflow error logs
https://github.com/threefoldtech/js-sdk/issues/1851
=> more descriptive logs for chatflow exceptions

jumpscale/packages/tfgrid_solutions/chats/kubernetes.py, jumpscale/packages/tfgrid_solutions/chats/minio.py
ask secret instead of string for minio SK and k8s cluster secret
https://github.com/threefoldtech/js-sdk/issues/1819
=> secret ask in k8s and minio

jumpscale/packages/admin/frontend/components/base/JSONRenderer.vue
- Add copy feature to JSONRenderer component
- [https://github.com/threefoldtech/js-sdk/issues/1632](https://github.com/threefoldtech/js-sdk/issues/1632)
=> Add copy feature to JSONRenderer component

.github/workflows/js-sdk-check-wheel.yml
This PR Adding a GitHub action workflow that will clean install Project dependencies, build the wheel from pyproject.toml and confirm that it has the right stuff and it can install correctly using pip.
closes  #1786
=> Adding poetry build to the workflow - issue#1786

jumpscale/sals/zos/network.py, jumpscale/sals/zos/node_finder.py, jumpscale/sals/zos/volumes.py, jumpscale/sals/zos/workloads.py
=> ansible helpers

jumpscale/sals/vdc/deployer.py
wait pool payments in the explorer on plan renewal
https://github.com/threefoldtech/js-sdk/issues/2334
=> Development vdc wait renew

jumpscale/packages/admin/frontend/components/solutions/Solution.vue, jumpscale/packages/admin/frontend/components/solutions/SolutionChatflow.vue, jumpscale/packages/tfgrid_solutions/chats/network.py, jumpscale/packages/tfgrid_solutions/chats/network_access.py, jumpscale/packages/tfgrid_solutions/sals/network_chat_base.py
split network chatflow
https://github.com/threefoldtech/js-sdk/issues/2221
=> Development split network chatflow

jumpscale/packages/vdc_dashboard/frontend/App.vue, jumpscale/packages/vdc_dashboard/frontend/index.js
Make marketplace default view in vdc dashboard
https://github.com/threefoldtech/js-sdk/issues/2244
=> Marketplace default vdc_dashboard view

docs/tests/sals/kubernetes/test_kubernetes.md, jumpscale/sals/kubernetes/manager.py, tests/sals/kubernetes/test_kubernetes.py
Add more tests for Kubernetes sals
#2140
=> Add More Tests for Kubernetes Sals

jumpscale/packages/vdc/chats/new_vdc.py, jumpscale/sals/vdc/deployer.py, jumpscale/sals/vdc/vdc.py
move capacity check to chatflow
https://github.com/threefoldtech/js-sdk/issues/2342
=> do capacity check before payment for new vdcs

jumpscale/packages/vdc_dashboard/bottle/deployments.py, jumpscale/packages/vdc_dashboard/frontend/App.vue, jumpscale/packages/vdc_dashboard/frontend/api.js
- Added dashboard update button in UI
- Supported branch query param
https://github.com/threefoldtech/js-sdk/issues/2210
=> VDC Dashboard: update button in UI

jumpscale/packages/vdc_dashboard/sals/solutions_chatflow.py
Allow the user to choose a custom domain not managed by any gateway.
https://github.com/threefoldtech/js-sdk/issues/2028
=> Choose custom domain for VDC solutions

jumpscale/tools/servicemanager/servicemanager.py
Log method was removed, so it's replaced with info
=> Fix service waiting log

jumpscale/packages/vdc_dashboard/frontend/components/vdcSettings/Wallet.vue
- Add wallet transactions button
- https://github.com/threefoldtech/js-sdk/issues/2254
=> add button for wallet transactions

jumpscale/sals/crtsh/__init__.py
- check only letsencrypt certs
=> check only letsencrypt certs

jumpscale/packages/vdc_dashboard/chats/discourse.py, jumpscale/packages/vdc_dashboard/sals/solutions_chatflow.py
- Add default values to smtp
- checks for passwords
- https://github.com/threefoldtech/js-sdk/issues/2381
=> add checks for discrose password check and default values to email

jumpscale/packages/vdc_dashboard/chats/digibyte.py, jumpscale/packages/vdc_dashboard/frontend/data.js, jumpscale/packages/vdc_dashboard/sals/vdc_dashboard_sals.py, jumpscale/sals/vdc/kubernetes.py
Adding the chatflow for digibyte
https://github.com/threefoldtech/js-sdk/issues/2209
=> Development vdc blockchain chatflows

jumpscale/packages/tfgrid_solutions/chats/minio.py
properly use the selected disk type for query and deployment in minio
=> fix minio disks

jumpscale/packages/auth/bottle/templates/login.html
- Fix typo in auth message
- [https://github.com/threefoldtech/js-sdk/issues/2385](https://github.com/threefoldtech/js-sdk/issues/2385)
=> Typo in auth message

jumpscale/packages/auth/bottle/auth.py, jumpscale/packages/auth/bottle/templates/email_not_verified.html, jumpscale/packages/auth/bottle/templates/login.html
- Add template for email verification
- https://github.com/threefoldtech/js-sdk/issues/2386
=> Add template for email verification

jumpscale/sals/billing/billing.py, jumpscale/sals/reservation_chatflow/deployer.py
- Add clear messages
- https://github.com/threefoldtech/js-sdk/issues/2391
=> add clear messages for payment

jumpscale/sals/zos/workloads.py
make sure the workload is not being deleted on decomission 
https://github.com/threefoldtech/js-sdk/issues/2420
=> check next action before signing the workload for deletion

jumpscale/packages/admin/frontend/components/solutions/KubernetesNodes.vue, jumpscale/packages/admin/frontend/components/solutions/Solution.vue, jumpscale/packages/admin/frontend/components/solutions/SolutionChatflow.vue, jumpscale/packages/admin/frontend/index.js, jumpscale/packages/tfgrid_solutions/chats/extend_kube.py, jumpscale/packages/vdc_dashboard/chats/monitoringstack.py
=> Development vdc kube extend1

jumpscale/sals/vdc/vdc.py, jumpscale/tools/zos/consumption/usage.py
- use explorer prices instead of creating a pool
- fix typo in vdc
=> Update zos consumption tool

jumpscale/packages/admin/frontend/components/pools/Pool.vue, jumpscale/packages/tfgrid_solutions/actors/solutions.py
https://github.com/threefoldtech/js-sdk/issues/935
=> Check pool name is an identifier

jumpscale/packages/vdc_dashboard/bottle/deployments.py
- Add missing data in zstor config file
- Add `meta` in the object
According to this doc: [https://github.com/threefoldtech/0-stor_v2#config-file](https://github.com/threefoldtech/0-stor_v2#config-file)
=> Add missing data in zstor config file

jumpscale/packages/admin/frontend/components/solutions/KubernetesNodes.vue, jumpscale/packages/tfgrid_solutions/chats/extend_kube.py, jumpscale/packages/tfgrid_solutions/chats/kubernetes.py, jumpscale/sals/reservation_chatflow/deployer.py, jumpscale/sals/reservation_chatflow/solutions.py
- Add Public IP in creating and extending the k8s nodes
https://github.com/threefoldtech/js-sdk/issues/2223
=> Development vdc kube public ip enable

jumpscale/packages/threebot_deployer/chats/change_size.py, jumpscale/packages/threebot_deployer/chats/restart_threebot.py
fix expiration calculation in threebot restart and resize
https://github.com/threefoldtech/js-sdk/issues/2428
=> Development fix 3bot restart

jumpscale/packages/threebot_deployer/chats/change_location.py
Choose a pool without any active workloads respecting the farm and node choices. If multiple exists, choose the one with the max min(cu, su). Create one if none exists.
https://github.com/threefoldtech/js-sdk/issues/2429
=> Use a pool in the farm if one exists and contains the selected node 

jumpscale/packages/threebot_deployer/chats/change_location.py, jumpscale/sals/reservation_chatflow/deployer.py
=> Fix node policy when selecting automatic

jumpscale/sals/vdc/kubernetes_auto_extend.py
handle zero percentage returned in k8s stats
https://github.com/threefoldtech/js-sdk/issues/2455
=> fix zero division

jumpscale/packages/vdc_dashboard/chats/zeroci.py, jumpscale/packages/vdc_dashboard/sals/solutions_chatflow.py
Add volume paths to zeroci to allow multiple instances 
=> Add volume paths to zeroci 

jumpscale/packages/vdc_dashboard/chats/monitoringstack.py, jumpscale/packages/vdc_dashboard/frontend/components/marketplace/Solution.vue, jumpscale/packages/vdc_dashboard/sals/vdc_dashboard_sals.py
Description
Add admin password to the user entered values to be viewed in "More Details" tab of Application details.
View creation formatted time instead of timestamp
Related Issues
#2197
=> Development vdc consistent app details

jumpscale/packages/marketplace/frontend/data.js, jumpscale/packages/vdc_dashboard/chats/digibyte.py, jumpscale/packages/vdc_dashboard/frontend/data.js
- https://github.com/threefoldtech/js-sdk/issues/2460
=> Fix solutions names in marketplace

jumpscale/packages/tfgrid_solutions/chats/network.py
fix ip version in network chatflow
=> fix network ip version

jumpscale/packages/vdc_dashboard/frontend/data.js
Disable `file browser` chat flow
https://github.com/threefoldtech/js-sdk/issues/2396
=> Disable firebrowser chatflow

jumpscale/packages/vdc_dashboard/frontend/data.js
Disable `document server` chat flow
=> Disable document server chat flow

jumpscale/packages/chatflows/frontend/mixins/field.js
allow using `is_identifier`  with `true` and `false`
https://github.com/threefoldtech/js-sdk/issues/2277
=> Handle is_identifier field

jumpscale/packages/vdc_dashboard/chats/discourse.py, jumpscale/packages/vdc_dashboard/chats/gitea.py, jumpscale/packages/vdc_dashboard/chats/kubeapps.py, jumpscale/packages/vdc_dashboard/chats/mattermost.py, jumpscale/packages/vdc_dashboard/chats/monitoringstack.py, jumpscale/packages/vdc_dashboard/chats/peertube.py, jumpscale/packages/vdc_dashboard/chats/taiga.py, jumpscale/packages/vdc_dashboard/frontend/data.js, jumpscale/packages/vdc_dashboard/sals/solutions_chatflow.py, jumpscale/sals/vdc/kubernetes_auto_extend.py
check requested resources of deployed pods
https://github.com/threefoldtech/js-sdk/issues/2474
=> Development vdc k8s reservations

jumpscale/packages/marketplace/chats/gollum.py, jumpscale/packages/tfgrid_solutions/chats/etcd.py, jumpscale/packages/tfgrid_solutions/chats/extend_kube.py, jumpscale/packages/tfgrid_solutions/chats/gollum.py, jumpscale/packages/vdc_dashboard/chats/gollum.py, jumpscale/sals/marketplace/deployer.py, jumpscale/sals/reservation_chatflow/deployer.py, jumpscale/sals/reservation_chatflow/reservation_chatflow.py, jumpscale/sals/vdc/s3_auto_topup.py
- Add Support `ipv4u`.
- Validate that the pool has `ipv4u`
- Validate that the Node has public IP
=> Development vdc kube ipv4u

tests/frontend/pages/Packages/packages.py
=> fix open browser test

jumpscale/packages/vdc/chats/new_vdc.py, jumpscale/sals/vdc/deployer.py, jumpscale/sals/vdc/proxy.py, jumpscale/sals/vdc/vdc.py
validate subdomains before vdc deployment && check if there are lingering domains with no respective workloads
https://github.com/threefoldtech/js-sdk/issues/2309
=> Development vdc subdomains

jumpscale/packages/vdc_dashboard/frontend/components/marketplace/SolutionChatflow.vue
- Fix auto extened redirection
- https://github.com/threefoldtech/js-sdk/issues/2488
=> Fix auto extened redirection

jumpscale/clients/explorer/models.py, jumpscale/packages/admin/actors/admin.py, jumpscale/packages/admin/frontend/api.js, jumpscale/packages/admin/frontend/components/solutions/DeleteNode.vue, jumpscale/packages/admin/frontend/components/solutions/KubernetesNodes.vue, jumpscale/packages/admin/frontend/components/solutions/NodeInfo.vue, jumpscale/packages/admin/frontend/components/solutions/Solution.vue, jumpscale/packages/admin/frontend/components/solutions/SolutionChatflow.vue, jumpscale/packages/admin/frontend/index.js, jumpscale/packages/marketplace/chats/gollum.py, jumpscale/packages/tfgrid_solutions/actors/solutions.py, jumpscale/packages/tfgrid_solutions/chats/etcd.py, jumpscale/packages/tfgrid_solutions/chats/extend_kube.py, jumpscale/packages/tfgrid_solutions/chats/gollum.py, jumpscale/packages/tfgrid_solutions/chats/kubernetes.py, jumpscale/packages/vdc_dashboard/chats/gollum.py, jumpscale/packages/vdc_dashboard/chats/monitoringstack.py, jumpscale/sals/marketplace/deployer.py, jumpscale/sals/reservation_chatflow/deployer.py, jumpscale/sals/reservation_chatflow/reservation_chatflow.py, jumpscale/sals/reservation_chatflow/solutions.py, jumpscale/sals/vdc/s3_auto_topup.py
- kubernetes sizes support https://github.com/threefoldtech/js-sdk/issues/1836
- kubernetes allow extending: https://github.com/threefoldtech/js-sdk/issues/2224
- kubernetes public IP support https://github.com/threefoldtech/js-sdk/issues/2223 
- Kubernetes delete button https://github.com/threefoldtech/js-sdk/issues/2350
- Kubenetes list nodes for deployed solutions https://github.com/threefoldtech/js-sdk/issues/2351
- This is the story 
https://github.com/threefoldtech/js-sdk/issues/2225
- https://github.com/threefoldtech/js-sdk/issues/1836
- https://github.com/threefoldtech/js-sdk/issues/2224
- https://github.com/threefoldtech/js-sdk/issues/2223 
- https://github.com/threefoldtech/js-sdk/issues/2350
- https://github.com/threefoldtech/js-sdk/issues/2351
=> Development vdc kube

jumpscale/sals/vdc/kubernetes_auto_extend.py
https://github.com/threefoldtech/js-sdk/issues/2492
=> include all nodes

jumpscale/packages/vdc/farm_config.json, jumpscale/sals/vdc/deployer.py, jumpscale/sals/vdc/size.py
- support reading deployment farms from config file in vdc deployment by setting it in js config under `j.core.config.get("VDC_FARMS_CONFIG")`
- example config: 
```json
{
"S3_AUTO_TOPUP_FARMS": {
"devnet": ["lochristi_dev_lab"],
"testnet": ["freefarm"],
"mainnet": ["freefarm"]
},
"ZDB_FARMS": {
"devnet": ["lochristi_dev_lab", "lochristi_dev_lab"],
"testnet": ["freefarm"],
"mainnet": ["freefarm"]
},
"PREFERED_FARM": {
"devnet": "lochristi_dev_lab",
"testnet": "freefarm",
"mainnet": "freefarm"
},
"NETWORK_FARM": {
"devnet": "lochristi_dev_lab",
"testnet": "freefarm",
"mainnet": "freefarm"
},
"PROXY_FARM": {
"devnet": "csfarmer",
"testnet": "csfarmer",
"mainnet": "csfarmer"
}
```
- for devnet you need to set `lochristi_dev_lab` twice in zdb farms as it contains less than 10 nodes which are …
=> Development vdc farms

jumpscale/sals/reservation_chatflow/deployer.py, jumpscale/sals/zos/gateway_finder.py
show farms that contain gateways only as options for pool creation
=> consider gateways as nodes in farm capacity check

solutions_automation/vdc/dashboard/cryptpad.py, solutions_automation/vdc/deployer.py, tests/sals/automated_chatflows/test_vdc_dashboard.py
Update and fix problems in vdc dashboard tests
- Fix tearDownClass method
- Update cryptpad chatflow test after adding new msg
=> Development vdc testing dashboard

jumpscale/sals/vdc/deployer.py, jumpscale/sals/vdc/vdc.py
=> Use private ip instead of public one on extending the cluster

tests/sals/automated_chatflows/test_vdc_chatflows.py
=> fix vdc teardown

jumpscale/packages/admin/frontend/components/dashboard/DiskUsage.vue, solutions_automation/dashboard_solutions/generic_flist.py, solutions_automation/dashboard_solutions/kubernetes.py, solutions_automation/dashboard_solutions/minio.py, solutions_automation/dashboard_solutions/monitoring.py, solutions_automation/dashboard_solutions/network.py, solutions_automation/dashboard_solutions/ubuntu.py
=> Development vdc networkmsg

jumpscale/sals/marketplace/deployer.py, jumpscale/sals/reservation_chatflow/deployer.py, jumpscale/sals/reservation_chatflow/reservation_chatflow.py, solutions_automation/dashboard_solutions/network.py
=> Update network message

jumpscale/packages/vdc_dashboard/bottle/deployments.py, jumpscale/packages/vdc_dashboard/frontend/api.js, jumpscale/packages/vdc_dashboard/frontend/components/marketplace/Delete.vue, jumpscale/packages/vdc_dashboard/frontend/components/marketplace/Solution.vue, jumpscale/packages/vdc_dashboard/sals/solutions_chatflow.py, jumpscale/packages/vdc_dashboard/sals/vdc_dashboard_sals.py, jumpscale/sals/kubernetes/manager.py
use a namespace for each chart to facilitate deletion
https://github.com/threefoldtech/js-sdk/issues/2523
=> Development vdc namespaces

jumpscale/clients/explorer/models.py, jumpscale/packages/admin/frontend/components/pools/Pool.vue, jumpscale/packages/admin/frontend/components/pools/Pools.vue
show ipv4 related info in dashboard
https://github.com/threefoldtech/js-sdk/issues/2519
=> show ipv4 related info in dashboard

jumpscale/packages/tfgrid_solutions/chats/gollum.py, tests/core/identity/test_identity.py, tests/frontend/tests/base_tests.py, tests/sals/automated_chatflows/chatflows_base.py, tests/sals/vdc/vdc_base.py, tests/servers/threebot/test_threebot.py
- use testnet explorer for tests
- fix typo
=> Change tests explorer

jumpscale/packages/vdc/chats/new_vdc.py
=> disable backup

jumpscale/sals/reservation_chatflow/deployer.py
https://github.com/threefoldtech/js-sdk/issues/2532
=> stopchatflow if no available pools

jumpscale/sals/reservation_chatflow/deployer.py
- update the message in case of no resources for deploying pool
Closes: https://github.com/threefoldtech/js-sdk/issues/2536, https://github.com/threefoldtech/js-sdk/issues/2360
=> update the message in case of no resources for deploying pool

tests/sals/automated_chatflows/test_vdc_chatflows.py
=> update vdc chatflows

jumpscale/packages/vdc_dashboard/frontend/components/vdcSettings/Home.vue
- update vdc expiration message with information about grace period
- https://github.com/threefoldtech/js-sdk/issues/2542
=> update vdc expiration message with information about grace period

jumpscale/clients/explorer/farms.py, jumpscale/clients/explorer/models.py, jumpscale/clients/explorer/prices.py, jumpscale/packages/farmmanagement/actors/farm_management.py, jumpscale/packages/farmmanagement/frontend/components/cspricestable/cspricestable.html, jumpscale/packages/farmmanagement/frontend/components/cspricestable/cspricestable.js, jumpscale/packages/farmmanagement/frontend/components/cspricestable/index.vue, jumpscale/packages/farmmanagement/frontend/components/nodestable/nodestable.html, jumpscale/packages/farmmanagement/frontend/services/farmmanagementServices.js, jumpscale/packages/farmmanagement/frontend/store/farmmanagement.js, jumpscale/packages/farmmanagement/frontend/store/index.js, jumpscale/packages/farmmanagement/frontend/views/farmmanagement/farmmanagement.html, jumpscale/packages/farmmanagement/frontend/views/farmmanagement/farmmanagement.js, jumpscale/packages/tfgrid_solutions/chats/network.py, jumpscale/sals/marketplace/apps_chatflow.py, jumpscale/sals/reservation_chatflow/deployer.py, jumpscale/sals/vdc/deployer.py, jumpscale/sals/vdc/kubernetes.py, jumpscale/sals/zos/gateway_finder.py, jumpscale/sals/zos/pools.py, jumpscale/tools/zos/consumption/usage.py
- should fix #2252 
don't merge before https://github.com/threefoldtech/tfexplorer/pull/286 is merged
=> custom pricing implementation for farmers

jumpscale/packages/vdc_dashboard/frontend/data.js
Fixes #2510 and disables meetings app
=> reorder kubeapps,zeroci, filebrowser and disable meetings app

CONTRIBUTION.md, VALUES.md
Add values and contribution files to js-sdk repo
=> Add values and contribution files to js-sdk repo

jumpscale/packages/vdc_dashboard/chats/digibyte.py, jumpscale/sals/vdc/kubernetes.py
https://github.com/threefoldtech/js-sdk/issues/2261
=> Add support for multiple traefik entrypoint addition in one call

jumpscale/packages/chatflows/frontend/mixins/field.js
- Fix the required validator by handling the empty case.
- https://github.com/threefoldtech/js-sdk/issues/2504
=> Fix the required validator by handling the empty case.

jumpscale/packages/tfgrid_solutions/chats/extend_pools.py, jumpscale/packages/tfgrid_solutions/chats/pools.py, jumpscale/packages/vdc/chats/new_vdc.py, jumpscale/sals/marketplace/apps_chatflow.py
change starting chatflows messages that check stellar service
- https://github.com/threefoldtech/js-sdk/issues/2567
=> change starting chatflows messages that check stellar service

jumpscale/packages/vdc_dashboard/services/update_dashboard_check.py
- Add UPDATE_DASHBOERD_CHECK service
- Check every 2 hours for updates in the remote repo
- Push log and notification with the info
- https://github.com/threefoldtech/js-sdk/issues/2557
=> Add UPDATE_DASHBOERD_CHECK service

jumpscale/packages/vdc_dashboard/chats/etcd.py, jumpscale/packages/vdc_dashboard/frontend/components/marketplace/Solution.vue, jumpscale/packages/vdc_dashboard/sals/vdc_dashboard_sals.py
Update etcd with ingress configurations
- Update etcd to use ingressroutetcp
- Fix frontend domain button condition, so show only if domain with value
- Enhance code of get_deployments function with 2 helper methods
#2431
=> Update etcd with ingress configurations

jumpscale/packages/vdc_dashboard/bottle/deployments.py, jumpscale/sals/vdc/proxy.py, jumpscale/sals/vdc/s3.py, jumpscale/sals/vdc/vdc.py
fetch running socat from kubernetes controller instead of saving them
=> Development vdc list socat

jumpscale/sals/vdc/vdc.py
don't fail when no socat proxies are deployed
=> don't fail if no socat proxies are deployed

jumpscale/packages/vdc_dashboard/sals/vdc_dashboard_sals.py
Fix **solution_id** missing key problem that reflects in application info
User Supplied Values is empty.
User Supplied Values return correct info, solution_uuid _(which used as solution_id in other locations)_ is one of them.
#2594
=> Fix solution_id missing key

jumpscale/clients/explorer/farms.py, jumpscale/packages/farmmanagement/actors/farm_management.py, jumpscale/packages/farmmanagement/frontend/components/cspricestable/cspricestable.html, jumpscale/packages/farmmanagement/frontend/components/cspricestable/cspricestable.js, jumpscale/packages/farmmanagement/frontend/services/farmmanagementServices.js, jumpscale/packages/farmmanagement/frontend/store/farmmanagement.js, jumpscale/packages/farmmanagement/frontend/views/farmmanagement/farmmanagement.html, jumpscale/packages/farmmanagement/frontend/views/farmmanagement/farmmanagement.js
=> update farm mgmt data only after saving

jumpscale/packages/vdc_dashboard/chats/etcd.py
Fix time to use implemented one in jsng
=> Fix time to use implemented one in jsng

.github/workflows/full.yml, pyproject.toml, tests/sals/automated_chatflows/test_vdc_chatflows.py, tests/sals/vdc/test_vdc.py
skip vdc high flavor tests
#2601
=> skip extended tests

jumpscale/packages/tfgrid_solutions/chats/kubernetes.py
Update the resources with `ipv4u` in case the public IP is enabled for k8s to be able to filter the pools with the right resources
https://github.com/threefoldtech/js-sdk/issues/2223
=> Handle selecting pools for k8s solution with IPV4U

jumpscale/packages/vdc/bottle/api.py
Add a bottle endpoint to redirect to the solution
=> Add solution redirection endpoint

jumpscale/packages/vdc_dashboard/bottle/deployments.py, jumpscale/packages/vdc_dashboard/frontend/components/vdcSettings/Kubernetes.vue
Add autoscale msg to the user if there still a capacity
#2528
=> Add autoscale msg to the user if there still a capacity

jumpscale/packages/vdc_dashboard/frontend/data.js
=> Disable taiga and discourse because of SSO

jumpscale/clients/stellar/stellar.py
=> Fix stellar testnet account activation through friendbot

jumpscale/packages/vdc_dashboard/bottle/deployments.py, jumpscale/packages/vdc_dashboard/frontend/components/vdcSettings/Home.vue
- Make vdc grace period more clear
- https://github.com/threefoldtech/js-sdk/issues/2542
=> update vdc grace period message

jumpscale/packages/vdc/bottle/api.py, jumpscale/packages/vdc/frontend/components/solutions/Wallet.vue, jumpscale/packages/vdc/frontend/components/solutions/Workloads.vue, jumpscale/packages/vdc_dashboard/frontend/components/vdcSettings/Home.vue, jumpscale/packages/vdc_dashboard/frontend/components/vdcSettings/Wallet.vue
- Make the default value of QR code is the plan price to be more clear
=> make the default value for qr code the vdc price

jumpscale/clients/explorer/prices.py, jumpscale/packages/vdc/billing.py, jumpscale/packages/vdc/services/fund_prices_diff.py, jumpscale/packages/vdc_dashboard/bottle/deployments.py, jumpscale/packages/vdc_dashboard/chats/extend_kubernetes.py, jumpscale/packages/vdc_dashboard/services/transaction_from_prepaid_to_provision_wallet.py, jumpscale/sals/vdc/vdc.py, jumpscale/tools/zos/consumption/usage.py
- Fix calculate the VDC expiration date
- Round the cloud units stropes like the explorer
- Fix prices usage calculations
- Fix calculator remaining_days in auto-extend service
- Adding FundPricesDifference service to pay the difference hourly
- Check if provisioning wallet has enough balance to renew plane
- Fund the transaction fees to the prepaid wallet if have the hour price
- [https://github.com/threefoldtech/js-sdk/issues/2600](https://github.com/threefoldtech/js-sdk/issues/2600)
=> Fix VDC expiration date

tests/sals/zos/test_pools.py
=> fix test pools

jumpscale/packages/vdc_dashboard/sals/solutions_chatflow.py
=> Fix delete solution in vdc dashboard

jumpscale/packages/vdc_dashboard/chats/cryptpad.py
- Change cryptpad volume hostpath
- https://github.com/threefoldtech/tf-cryptpad/issues/1
=> Change cryptpad volume hostpath

jumpscale/packages/vdc_dashboard/sals/solutions_chatflow.py
label all deployment resources
https://github.com/threefoldtech/js-sdk/issues/2657
=> Development vdc labels

jumpscale/sals/vdc/threebot.py
- use the current branch in vdc deployers instead of hardcoding it
=> use the current branch in vdc deployers instead of hardcoding it

jumpscale/packages/vdc_dashboard/chats/peertube.py
=> Development vdc peertube fix

jumpscale/packages/vdc/chats/new_vdc.py, jumpscale/sals/minio_admin/__init__.py, vdc.json
=> Development vdc s3

tests/sals/automated_chatflows/test_vdc_dashboard.py, tests/sals/vdc/vdc_base.py
Fix importing wallets in vdc dashboard tests' setup
=> Fix importing wallets in vdc dashboard tests setup

jumpscale/packages/admin/frontend/components/wallets/Import.vue
Hide text of secret field 
when clicking on eye icon 
[#2518](https://github.com/threefoldtech/js-sdk/issues/2518)
=> secret field for import wallet dialog

.github/workflows/full.yml
=> change the run branch to development

jumpscale/core/identity/__init__.py
adds network option to simplify identity creations
=> allow network option for identity creation

jumpscale/packages/admin/actors/wallet.py, jumpscale/packages/admin/frontend/api.js, jumpscale/packages/admin/frontend/components/wallets/Wallet.vue, jumpscale/packages/admin/frontend/index.html
Added qr code for topping up wallet in admin dashboard
https://github.com/threefoldtech/js-sdk/issues/1756
=> Added qr code for topping up wallet in admin dashboard

jumpscale/packages/farmmanagement/frontend/views/farmmanagement/farmmanagement.html, jumpscale/packages/farmmanagement/frontend/views/farmmanagement/farmmanagement.js
Added validation in custom pricing form
https://user-images.githubusercontent.com/36021484/109519643-15994400-7ab4-11eb-8735-5e2e67736647.mp4
https://github.com/threefoldtech/js-sdk/issues/2624
=> Added validation in custom pricing form

jumpscale/packages/threebot_deployer/bottle/utils.py, jumpscale/packages/threebot_deployer/chats/restart_threebot.py, jumpscale/packages/threebot_deployer/frontend/components/base/Table.vue, jumpscale/packages/threebot_deployer/frontend/components/solutions/Info.vue, jumpscale/packages/threebot_deployer/models/user_solutions.py
- show state error when the 3bot is unreachable
becomes
-https://github.com/threefoldtech/js-sdk/issues/2682
=> show state error when the 3bot is unreachable

jumpscale/packages/vdc_dashboard/bottle/backup.py, jumpscale/packages/vdc_dashboard/frontend/api.js, jumpscale/packages/vdc_dashboard/package.toml
- Add endpoints for backup/restore
Add List, Backup, Restore, Delete
- https://github.com/threefoldtech/js-sdk/issues/2646
- https://github.com/threefoldtech/js-sdk/issues/2647
=> add endpoints for backup/restore for vdc dashboard

.github/workflows/full.yml, jumpscale/packages/vdc/chats/new_vdc.py, tests/collect_tokens.py
- Collect token after running tests in CI
- Send failed wallets to merge to telegram channel
- Fix typo
- Edit workflow to continue on an error to collect the token then exit
=> Collect token after running tests in CI

jumpscale/packages/vdc_dashboard/chats/presearch.py
We want to have the Presearch node deployable with minimum resources. This PR is meant to test the deployment of Presearch node with minimal resources for compute (cpu/mem) 
* https://github.com/threefoldtech/vdc-solutions-charts/pull/105 (Needs to be approved first)
* https://github.com/threefoldtech/js-sdk/issues/2642
=> Presearch - lower the resource limits 

jumpscale/clients/stellar/__init__.py, jumpscale/packages/vdc/billing.py, jumpscale/packages/vdc/services/fund_prices_diff.py, jumpscale/sals/billing/billing.py, jumpscale/sals/billing/models.py, jumpscale/sals/reservation_chatflow/deployer.py, jumpscale/sals/reservation_chatflow/reservation_chatflow.py, jumpscale/sals/vdc/grace_period.py, jumpscale/sals/vdc/vdc.py, tests/sals/automated_chatflows/test_vdc_dashboard.py, tests/sals/billing/test_billing.py, tests/sals/vdc/test_vdc.py, tests/sals/vdc/vdc_base.py, tests/sals/zos/test_pools.py
- Make the TRANSACTION_FEES as a stalletFactory prop
- https://github.com/threefoldtech/js-sdk/issues/2704
=> Make the TRANSACTION_FEES as a stalletFactory prop

docs/tests/sals/automated_chatflows/test_solutions.md, solutions_automation/dashboard_solutions/four_to6gw.py, solutions_automation/deployer.py, tests/sals/automated_chatflows/test_solutions.py
add test for 4to6 GW
https://github.com/threefoldtech/js-sdk/issues/1532
=> add 4to6 gw test

jumpscale/packages/vdc/bottle/api.py, jumpscale/packages/vdc/frontend/components/solutions/Workloads.vue
Show only vdcs that have threebot's domain deployed
when threebot's domain is not deployed yet
after it's deployed
#2710
=> Show only vdcs that have threebot's domain deployed

jumpscale/packages/vdc_dashboard/chats/extend_kubernetes.py
- check available capacity before extending kubernetes cluster in vdc, A warning like that will come before payment
- https://github.com/threefoldtech/js-sdk/issues/2711#event-4413802655
=> check available capacity before extending kubernetes cluster in vdc

jumpscale/packages/vdc_dashboard/chats/matic.py, jumpscale/packages/vdc_dashboard/frontend/data.js
This is the chatflow for Matic solution that will deploy a Matic node.
* This PR needs to be approved first https://github.com/threefoldtech/vdc-solutions-charts/pull/106
* Issue under this link https://github.com/threefoldtech/vdc-solutions-charts/issues/39
=> Add Matic Chatflow

jumpscale/sals/reservation_chatflow/reservation_chatflow.py
- add more information in 3bot error message
=> add more information in 3bot error message

docs/wiki/quick_start.md, docs/wiki/tutorials/deploy_ubuntu_container.md
=> Remove FreeTFT from quickstart and deploy ubuntu tutorial

jumpscale/packages/vdc/chats/new_vdc.py, jumpscale/sals/vdc/deployer.py, jumpscale/sals/vdc/scheduler.py, jumpscale/sals/vdc/threebot.py, solutions_automation/vdc/dashboard/vdc.py, solutions_automation/vdc/deployer.py
allow user to select farms to deploy zdb
https://github.com/threefoldtech/js-sdk/issues/2338
=> Development vdc storage farms selection

jumpscale/packages/threebot_deployer/chats/change_location.py, jumpscale/sals/marketplace/apps_chatflow.py, jumpscale/sals/reservation_chatflow/deployer.py, jumpscale/sals/zos/node_finder.py
- Fix nodes filter
- Change payment for threebot change location after initialization
Please NOTE: we won't be able to deploy on any farm that doesn't have access node
=> fix access nodes filter and threebot deployer change location payment

jumpscale/packages/vdc_dashboard/sals/solutions_chatflow.py
- set max length to solutions name
- https://github.com/threefoldtech/js-sdk/issues/2736
=> set max length to solutions name

jumpscale/packages/vdc_dashboard/sals/solutions_chatflow.py, jumpscale/sals/kubernetes/manager.py
Fix duplicate name in chatflow
#2740
=> Fix duplicate name in chatflow

jumpscale/packages/vdc_dashboard/bottle/deployments.py, jumpscale/packages/vdc_dashboard/frontend/App.vue, jumpscale/packages/vdc_dashboard/frontend/api.js
- Wait until the 3Bot start to refresh the frontend in updating the VDC
- Handle the update API failure
https://user-images.githubusercontent.com/36021484/110790803-28610500-827a-11eb-98b4-dd7dc9850134.mp4
- https://github.com/threefoldtech/js-sdk/issues/2709
- https://github.com/threefoldtech/js-sdk/issues/2668
=> Development update vdc threebot

jumpscale/packages/vdc_dashboard/chats/taiga.py
Adding new taiga chart config
https://github.com/threefoldtech/js-sdk/issues/2582
=> Adding new taiga chart config

jumpscale/packages/vdc_dashboard/chats/taiga.py
Pass new chart limits param when choose flavor
=> Pass new chart limits param when choose flavor

jumpscale/packages/vdc_dashboard/chats/taiga.py
- Fix passing params to taiga chart
=> Fix passing params to taiga chart

jumpscale/packages/vdc_dashboard/frontend/data.js
- Enable taiga in VDC marketplace
- https://github.com/threefoldtech/js-sdk/issues/2582
=> Enable taiga in VDC marketplace

jumpscale/packages/vdc_dashboard/frontend/components/License.vue
- Update the License message that appears to the user at the first login to the VDC.
- Update wiki link with https://wiki.cloud.threefold.io
#2726
=> Update VDC license msg

jumpscale/packages/vdc/billing.py, jumpscale/packages/vdc/services/fund_prices_diff.py
Fix calculate user price per hour
=> Fix calculate user price per hour

jumpscale/sals/vdc/deployer.py
Sleep when pool creation and extension has a problem
=> Sleep when pool creation and extension has a problem

jumpscale/packages/vdc_dashboard/frontend/components/vdcSettings/Actions.vue, jumpscale/packages/vdc_dashboard/frontend/components/vdcSettings/Backups.vue, jumpscale/packages/vdc_dashboard/frontend/components/vdcSettings/Restore.vue
Optimze vdc backup layout
Update headers
update timestamp format
Add Search input
Filter backups with date
Update create popup 
Fix typos
[#2752](https://github.com/threefoldtech/js-sdk/issues/2752)
=> optimize vdc backup layout

jumpscale/packages/threebot_deployer/frontend/App.vue, jumpscale/packages/threebot_deployer/frontend/components/solutions/ActionConfirmation.vue
Fix logout in Threebot deployer
- Remove the duplication in the `methods` definition 
- Change the messages type to Object in the ActionConfirmation component
- https://github.com/threefoldtech/js-sdk/issues/2746
=> Fix logout in Threebot deployer

jumpscale/packages/vdc_dashboard/frontend/components/vdcSettings/Backups.vue
- https://github.com/threefoldtech/js-sdk/issues/2752
=> fix backup status to be more meaningful

jumpscale/packages/threebot_deployer/chats/restart_threebot.py
possible fix to include the threebots with error in the non-running 3bots
- https://github.com/threefoldtech/js-sdk/issues/2757
=> fix threebot state

docs/vdc/vdc_dashboard_rest_interface.md, jumpscale/packages/auth/bottle/auth.py, jumpscale/packages/vdc_dashboard/bottle/controller.py, jumpscale/packages/vdc_dashboard/bottle/deployments.py, jumpscale/packages/vdc_dashboard/bottle/vdc_helpers.py, jumpscale/packages/vdc_dashboard/chats/extend_kubernetes.py, jumpscale/packages/vdc_dashboard/frontend/api.js, jumpscale/packages/vdc_dashboard/frontend/components/vdcSettings/DeleteConfirmation.vue, jumpscale/packages/vdc_dashboard/frontend/components/vdcSettings/Kubernetes.vue, jumpscale/packages/vdc_dashboard/frontend/components/vdcSettings/S3.vue, jumpscale/packages/vdc_dashboard/frontend/index.js, jumpscale/packages/vdc_dashboard/package.py, jumpscale/packages/vdc_dashboard/package.toml, jumpscale/sals/vdc/deployer.py, jumpscale/sals/vdc/quantum_storage.py, jumpscale/sals/vdc/s3.py, jumpscale/sals/vdc/s3_auto_topup.py, jumpscale/sals/vdc/vdc.py, jumpscale/sals/vdc/zdb_auto_topup.py
Create a REST interface to be used with the current vdc dashboard
- Add controller bottle server (REST interface endpoints) in vdc dashboard package
-  Create a common vdc helpers file to include common functionalities between bottle servers in vdcc dashboard
- Add controller_autherized decorator in auth
- Add delete button on storage nodes in vdc dashboard ui
- https://github.com/threefoldtech/js-sdk/issues/2743
- https://github.com/threefoldtech/js-sdk/issues/2774#event-4468740241
=> Development vdc rest interface

jumpscale/packages/vdc_dashboard/chats/discourse.py, jumpscale/packages/vdc_dashboard/frontend/data.js, jumpscale/packages/vdc_dashboard/sals/solutions_chatflow.py
=> Development discourse chatflow

jumpscale/packages/vdc_dashboard/chats/blog.py, jumpscale/packages/vdc_dashboard/chats/website.py, jumpscale/packages/vdc_dashboard/chats/wiki.py
=> Update blog, wiki, website docs links

jumpscale/packages/admin/frontend/components/pools/Pools.vue
Merge active and total table 
[#2588](https://github.com/threefoldtech/js-sdk/issues/2588)
=> merge table cells

jumpscale/packages/vdc_dashboard/bottle/controller.py
Master node should not be deleted in vdc.
Add check and error when endpoint to delete recieves the wid of the master node
https://github.com/threefoldtech/js-sdk/issues/2743
=> Add check for master node when deleting node in vdc rest interface

jumpscale/sals/vdc/quantum_storage.py
- Zdb hook file path was changed
- Added the new path
=> fix zdb hook path

jumpscale/clients/stellar/stellar.py
For some wallets, geting balance fails if there are no cursor. 
error example:
```
KeyError: 'cursor'
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/home/waleed/js-sdk/jumpscale/clients/stellar/stellar.py", line 155, in get_balance
for account in self._find_escrow_accounts(address):
File "/home/waleed/js-sdk/jumpscale/clients/stellar/stellar.py", line 173, in _find_escrow_accounts
new_cursor = parse.parse_qs(next_link_query)["cursor"][0]
│            │              └ 'cursor=&limit=10&order=asc&signer=GB2LWAT2QJPXQM2K3VJCSH4EB3YLZCGDKVUQLSQIUO652IRJZ6D6F5LY'
│            └ <module 'urllib.parse' from '/usr/lib/python3.8/urllib/parse.py'>
└ ''
KeyError: 'cursor'
```
Add check for cursor
```
wallet.get_balance("GB2LWAT2QJPXQM2K3VJCSH4EB3YLZCGDKVUQLSQIUO652IRJZ6 …
```
=> Add check for cursor in get balance in stellar client

jumpscale/packages/vdc_dashboard/frontend/components/vdcSettings/S3.vue
=> fix  merge in s3 and quantum storage

jumpscale/sals/vdc/quantum_storage.py
- fix merges with quantum storage
- fix merges and cleanup
- https://github.com/threefoldtech/js-sdk/issues/2715
=> Development quantumstoragefix

jumpscale/packages/vdc/frontend/components/solutions/Delete.vue, jumpscale/packages/vdc_dashboard/frontend/components/vdcSettings/DownloadKubeconfig.vue, jumpscale/packages/vdc_dashboard/frontend/components/vdcSettings/S3.vue
new message
```
WARNING: This action can't be undone. Please make sure to transfer the tokens left in your wallet before deletion. (Wallet secret is available in your VDC dashboard wallet pane)
```
- https://github.com/threefoldtech/js-sdk/issues/2809
=> add warining to transfer the left tokens in the wallet

tests/sals/automated_chatflows/test_vdc_dashboard.py
=> change self in setUpClass

jumpscale/packages/vdc_dashboard/frontend/components/vdcSettings/S3.vue
- rename enable quantum storage to quantum storage configurations
=> rename enable quantum storage to quantum storage configurations

jumpscale/packages/vdc_dashboard/bottle/deployments.py, jumpscale/packages/vdc_dashboard/frontend/api.js, jumpscale/packages/vdc_dashboard/frontend/components/vdcSettings/Home.vue, jumpscale/packages/vdc_dashboard/frontend/style.css
- Add js-ng & js-sdk versions to vdc dashboard 
- https://github.com/threefoldtech/js-sdk/issues/2766
=> add ng and sdk version to vdc dashboard

jumpscale/sals/vdc/kubernetes.py
- Update traefik version.
- enable traefik in all deployment.
=> Update traefik version

jumpscale/packages/auth/bottle/auth.py, jumpscale/packages/vdc/billing.py, jumpscale/packages/vdc_dashboard/bottle/deployments.py, jumpscale/packages/vdc_dashboard/bottle/vdc_helpers.py, jumpscale/packages/vdc_dashboard/chats/extend_kubernetes.py, jumpscale/packages/vdc_dashboard/chats/extend_storage.py, jumpscale/packages/vdc_dashboard/services/domain.py, jumpscale/packages/vdc_dashboard/services/etcd_backup.py
raise if no vdc instances found in vdc dashboard
- https://github.com/threefoldtech/js-sdk/issues/2792
=> raise if no vdc instances found in vdc dashboard

docs/vdc/vdc_deployer.md
- add docs for vdc deployment
- https://github.com/threefoldtech/js-sdk/issues/1924
=> add docs for vdc deployment

jumpscale/packages/vdc/chats/new_vdc.py, jumpscale/packages/vdc_dashboard/bottle/controller.py, jumpscale/packages/vdc_dashboard/chats/extend_storage.py, jumpscale/sals/vdc/deployer.py, jumpscale/sals/vdc/quantum_storage.py, jumpscale/sals/vdc/threebot.py, jumpscale/sals/vdc/vdc.py, jumpscale/sals/vdc/zdb_auto_topup.py
- Use password hash for zdb
- Get password from vdc instance
- Get zdb farms from config instead of zdb workload.
#2802
=> Use password hash for zdb

jumpscale/packages/tfgrid_solutions/scripts/threebot/minimal_entrypoint.py, jumpscale/sals/vdc/deployer.py
Increase backup schedule to 12h
=> Increase backup schedule to 12h

jumpscale/clients/explorer/models.py, jumpscale/packages/farmmanagement/frontend/components/nodeinfo/nodeinfo.html, jumpscale/packages/farmmanagement/frontend/components/nodestable/nodestable.js
=> show hostname in farm management

jumpscale/packages/vdc_dashboard/frontend/components/vdcSettings/Backups.vue
Change backup msg in case no backup available
#2829
=> Change backup msg in case no backup available

jumpscale/packages/vdc/chats/new_vdc.py
show vdc uuid in deployment error messages
=> add vdc uuid in error msg

tests/frontend/pages/pools/pools.py
update list pool tests (frontend)
=> update pool tests 

.github/workflows/basic.yml, docs/tests/sals/automated_chatflows/test_solutions.md, solutions_automation/dashboard_solutions/etcd.py, solutions_automation/deployer.py, tests/sals/automated_chatflows/test_solutions.py
test etcd
https://github.com/threefoldtech/js-sdk/issues/2255
=> add etcd test

jumpscale/packages/threebot_deployer/bottle/utils.py, jumpscale/packages/threebot_deployer/chats/change_location.py, jumpscale/packages/threebot_deployer/chats/change_size.py, jumpscale/packages/threebot_deployer/chats/restart_threebot.py, jumpscale/packages/threebot_deployer/frontend/components/base/Table.vue
- fix paying before initalizing in restart and fix states
- https://github.com/threefoldtech/js-sdk/issues/2796
- https://github.com/threefoldtech/js-sdk/issues/2797
=> Fix threebot states and fix paying before initializing in restart/resize 

jumpscale/packages/vdc_dashboard/frontend/App.vue
- Clear cache in reload frontend after update the dashboard
- https://github.com/threefoldtech/js-sdk/issues/2838
=> Clear cache in reload frontend after update the dashboard

jumpscale/packages/vdc_dashboard/chats/matic.py
This chatflow is capable of launching 3 types of nodes for Matic / Polygon network,
* Sentry Node
* Full Node
* Validator
https://github.com/threefoldtech/vdc-solutions-charts/pull/127 (Need to be approved first)
https://github.com/threefoldtech/vdc-solutions-charts/issues/120
=> Update matic chatflow for multi-node setup

jumpscale/packages/admin/frontend/index.js, jumpscale/packages/notebooks/package.toml, jumpscale/servers/threebot/threebot.py
- Adds option to exclude packages in package.toml
- Disables notebooks package #2853
=> Allow excluding packages and exclude notebooks package

jumpscale/clients/stellar/__init__.py
=> use options instead of GET for tokenservices health check

docs/vdc/billing.md, docs/vdc/vdc_deployer.md
Create a VDC billing Docs
#1924
=> VDC Billing Docs

docs/vdc/vdc_deployer.md, docs/vdc/vdc_grid_requirement.md
- Add grid requirement docs for vdc
- Add logging and mc install for vdc deployment docs
#1924
=> Add grid requirement docs for vdc

jumpscale/packages/vdc_dashboard/frontend/data.js
- update the help link for OwnCloud solution
- fixing bad character in the Description
=> update help link for OwnCloud solution

jumpscale/packages/threebot_deployer/bottle/utils.py
- Increase timeout for deleting workloads 
- minor fix
- https://github.com/threefoldtech/js-sdk/issues/2797
=> fix threebot stop state

docs/vdc/solutions_development.md
creating docs for  how to develop a new solution for the `vdc`, should cover all aspects including repo, forking, pipeline, threefold connect, `vdc` integration
https://github.com/threefoldtech/js-sdk/issues/1924
=> create docs for  how to develop a new solution for the vdc

jumpscale/sals/vdc/kubernetes.py, jumpscale/sals/vdc/vdc.py
Fix ssh instance name in vdc deployer
=> Fix ssh instance name in vdc deployer

jumpscale/packages/admin/frontend/App.vue
- Fix Logging out in the 3Bot
- https://github.com/threefoldtech/js-sdk/issues/2871
=> Fix Logging out in the 3Bot

jumpscale/packages/vdc_dashboard/bottle/backup.py, jumpscale/packages/vdc_dashboard/frontend/api.js, jumpscale/packages/vdc_dashboard/frontend/components/vdcSettings/Actions.vue, jumpscale/packages/vdc_dashboard/frontend/components/vdcSettings/Backups.vue, jumpscale/packages/vdc_dashboard/frontend/components/vdcSettings/Restore.vue
Refactor VDC Backup and Restore listing to list backup as 1 item, not 2 items, add timeout before reloading to list the true data.
#2789
=> VDC Backup and Restore listing

jumpscale/packages/vdc_dashboard/frontend/data.js
Fix dash help link
- jumpscale/packages/vdc_dashboard/frontend/data.js
=> Fix dash help link

jumpscale/packages/vdc_dashboard/frontend/components/marketplace/Solution.vue
=> Fix Solution component

jumpscale/sals/vdc/deployer.py
Fix Farm pool units for zdb farms
#2861
=> Fix Farm pool units for zdb farms

jumpscale/install/rootfs/etc/zinit/start.yaml, jumpscale/packages/admin/bottle/admin.py
add heartbeat endpoint and use it with zinit
=> Development heartbeat

jumpscale/clients/liquid/liquid.py
- Add functionalities in liquid client to be able to create orders. 
- Required for usage in the TFT selling bot with the follow [specs](https://github.com/threefoldfoundation/home_private/blob/master/specs/sales_bot.md)
```
client = j.clients.liquid.get("test_client",token_id=TOKEN_ID,token_secret=TOKEN_SECRET)
client.save()
JS-NG> client.create_order(order_type="limit",product_id=637,side="sell",quantity=12,price=50)
{'id': 4238991143, 'order_type': 'limit', 'quantity': '12.0', 'disc_quantity': '0.0', 'iceberg_total_quantity': '0.0', 'side': 'sell', 'filled_quantity': '0.0', 'price': 50.0, 'created_at': 1617896032, 'updated_at': 1617896032, 'status': 'live', 'leverage_level': 1, 'source_exchange': 'QUOINE', 'product_id': 637, 'margin_type': None, 'take_profit': None, 'stop_loss': None, …
```
=> Development liquid client

tests/clients/github/test_github.py
=> skip all github tests

jumpscale/packages/vdc_dashboard/chats/mastodon.py
=> admin creds typo

jumpscale/packages/vdc_dashboard/frontend/data.js
=> updating links again for maketplace: fixes 2875

jumpscale/clients/stellar/balance.py, jumpscale/clients/stellar/stellar.py, jumpscale/clients/stellar/vesting.py
Solves #2890
Makes the stellar client get_balance show vesting details
=> Make the stellar client aware of vesting accounts

jumpscale/clients/liquid/liquid.py
- query params should be encoded in the signature
=> fix queries in liquid client

jumpscale/clients/liquid/liquid.py
- small hardening to liquid client
=> Make sure params is passed or use normal path

jumpscale/clients/liquid/liquid.py
This reverts commit 10cad051afe2bb1cc700dbadf3a9241d31badc92.
We only need to change path in that place not the whole file
=> Revert "Make sure params is passed or use normal path (#2902)"

jumpscale/clients/btc_alpha/__init__.py, jumpscale/clients/btc_alpha/btc_alpha.py
- https://github.com/threefoldfoundation/tft-sales-bot/issues/2
=> add btc alpha ported from jsx

jumpscale/packages/vdc/services/fund_prices_diff.py
=> Fix vdc fund diff service

docs/vdc/vdc_grid_requirement.md, jumpscale/packages/vdc/chats/new_vdc.py, jumpscale/packages/vdc/farm_config.json, jumpscale/sals/vdc/deployer.py, jumpscale/sals/vdc/kubernetes.py, jumpscale/sals/vdc/public_ip.py, jumpscale/sals/vdc/size.py, jumpscale/sals/vdc/vdc.py
- Make vdc farms configurable
- Add compute and network farms selection in chatflow
- Update grid requirement docs for vdc
#2858
=> vdc farms configuration

jumpscale/packages/vdc_dashboard/frontend/components/vdcSettings/DeleteConfirmation.vue, jumpscale/packages/vdc_dashboard/frontend/components/vdcSettings/Home.vue, jumpscale/packages/vdc_dashboard/frontend/components/vdcSettings/Kubernetes.vue, jumpscale/packages/vdc_dashboard/frontend/components/vdcSettings/S3.vue
fix redirection after deletion in compute & storage nodes
- Change redirection into emitting events
- https://github.com/threefoldtech/js-sdk/issues/2857
=> fix redirection after deletion in compute & storage nodes

jumpscale/packages/vdc_dashboard/bottle/controller.py, jumpscale/packages/vdc_dashboard/bottle/deployments.py, jumpscale/packages/vdc_dashboard/bottle/vdc_helpers.py, jumpscale/packages/vdc_dashboard/frontend/api.js, jumpscale/packages/vdc_dashboard/frontend/components/base/Code.vue, jumpscale/packages/vdc_dashboard/frontend/components/vdcSettings/Home.vue, jumpscale/packages/vdc_dashboard/frontend/components/vdcSettings/alerts/Alert.vue, jumpscale/packages/vdc_dashboard/frontend/components/vdcSettings/alerts/Alerts.vue, jumpscale/packages/vdc_dashboard/frontend/data.js, jumpscale/packages/vdc_dashboard/frontend/index.js, jumpscale/packages/vdc_dashboard/sals/solutions_chatflow.py, jumpscale/sals/chatflows/chatflows.py
- Add alert view in the VDC dashboard.
- jumpscale/packages/vdc_dashboard/bottle/controller.py
- jumpscale/packages/vdc_dashboard/bottle/deployments.py 
- jumpscale/packages/vdc_dashboard/bottle/vdc_helpers.py
- jumpscale/packages/vdc_dashboard/sals/solutions_chatflow.py
- jumpscale/sals/chatflows/chatflows.py
- frontend
- https://github.com/threefoldtech/js-sdk/issues/2794
=> VDC: add alert view

jumpscale/packages/vdc/services/check_health_service.py, jumpscale/packages/vdc_dashboard/bottle/controller.py
**Please note: this will require to update all existing dashboards to work correctly as we've added a new unauthorized endpoint in the vdc dashboard**
- Add service for check vdcs health on vdc package
- Add new unauthorized endpoint in vdc dashboard to make sure it's working
- Raise alerts
- Related Logs
- https://github.com/threefoldtech/js-sdk/issues/2907
=> Add service in vdc deployer for checking the vdc health

jumpscale/packages/vdc_dashboard/chats/digibyte.py, jumpscale/packages/vdc_dashboard/chats/presearch.py
=> Fix Digibyte and Presearch

jumpscale/packages/vdc_dashboard/sals/solutions_chatflow.py
=> Fix deployment cleanup

jumpscale/packages/vdc_dashboard/bottle/controller.py, jumpscale/packages/vdc_dashboard/chats/extend_kubernetes.py, jumpscale/sals/vdc/deployer.py, jumpscale/sals/vdc/kubernetes_auto_extend.py, jumpscale/sals/vdc/s3_auto_topup.py, jumpscale/sals/vdc/vdc.py
show addons price depend on explorer price
#2935
=> kubernetets addons worker price

jumpscale/sals/vdc/deployer.py
Link exception for kubernetes and zdb deployments
=> Link exception for kubernetes and zdb deployments

jumpscale/clients/stellar/stellar.py
=> fix 0 retries message

jumpscale/tools/zos/reporting/__init__.py
- Now we can get all, one, selection
- resolves https://github.com/threefoldtech/js-sdk/issues/2954
=> extend the usage of reporting tool to take all available farms or selection

jumpscale/packages/vdc/services/check_health_service.py, jumpscale/sals/vdc/vdc.py
harden health check service to make sure the vdc has kubernetes
=> Development healthcheck hardening

jumpscale/packages/vdc_dashboard/bottle/deployments.py
- Use `git ls-remote` instead of fetch repo URL
- jumpscale/packages/vdc_dashboard/bottle/deployments.py
- https://github.com/threefoldtech/js-sdk/issues/2923
=> Use git ls-remote instead of fetch repo URL

jumpscale/packages/vdc/chats/new_vdc.py, jumpscale/packages/vdc/farm_config.json, jumpscale/packages/vdc_dashboard/chats/extend_storage.py, jumpscale/sals/vdc/size.py, jumpscale/sals/vdc/vdc.py
- vdc soft delete instance
- Store vdc deployment state in redis
- Fix pay initiaiztion fees
- Fix some typos
#2952
#2958
=> vdc soft delete instance

jumpscale/packages/vdc_dashboard/chats/digibyte.py, jumpscale/packages/vdc_dashboard/package.toml
We need to increase the compute limits as the node requires more resources to operate 
https://github.com/threefoldfoundation/www_threefold_marketplace/issues/38
https://github.com/threefoldfoundation/info_cloud/issues/15
- [ x] [Pre-commit hook is installed](https://github.com/threefoldtech/js-ng#pre-commit) to do formatting checks before committing code...etc
=> Digibyte : Increase Compute Limits

jumpscale/packages/vdc/chats/new_vdc.py, jumpscale/packages/vdc/package.py
Clear the deploying instance from redis when starting vdc package
#2958
=> Clear the deploying instance from redis when starting vdc package

jumpscale/tools/vdc/reporting/__init__.py
- Add reporting tool for vdc to make debugging easy
=> add reporting tool for vdc

jumpscale/packages/admin/services/notifier.py, jumpscale/packages/tfgrid_solutions/utils.py
=> Notifier service

jumpscale/packages/vdc_dashboard/bottle/api/controller.py, jumpscale/packages/vdc_dashboard/bottle/api/helpers.py
- Example requests
- Add logger plugin to controller bottle server
=> add plugin to bottle to wrap the requests

jumpscale/packages/vdc/package.py
=> Fix vdc package

jumpscale/packages/farmmanagement/actors/farm_management.py, jumpscale/sals/reservation_chatflow/deployer.py
- fix farm managment actor and empty/free pool creation
=> fix farm managment actor and empty/free pool creation

jumpscale/tools/vdc/reporting/__init__.py
- Add wallets information
- Add public ip status
- Add ipv4 units
=> Development reportingimprovment

docs/vdc/vdc_dashboard.md, docs/vdc/vdc_dashboard_rest_interface.md, docs/vdc/vdc_grid_requirement.md, jumpscale/packages/vdc/chats/new_vdc.py, jumpscale/packages/vdc_dashboard/chats/extend_kubernetes.py, jumpscale/packages/vdc_dashboard/chats/extend_storage.py, jumpscale/packages/vdc_dashboard/frontend/components/vdcSettings/Home.vue, jumpscale/packages/vdc_dashboard/frontend/components/vdcSettings/S3.vue, jumpscale/tools/vdc/reporting/__init__.py
Fixes #2878  phrasing in https://github.com/threefoldtech/js-sdk/issues/2981 and #2990
=> update language from zdb nodes to storage containers

solutions_automation/vdc/dashboard/vdc.py
update zdb farm message in vdc solutions automation
=> update zdb farm message

jumpscale/packages/vdc_dashboard/bottle/api/controller.py, jumpscale/packages/vdc_dashboard/chats/extend_kubernetes.py, jumpscale/packages/vdc_dashboard/chats/extend_storage.py, jumpscale/packages/vdc_dashboard/services/s3_auto_topup.py, jumpscale/sals/vdc/deployer.py, jumpscale/sals/vdc/s3_auto_topup.py, jumpscale/sals/vdc/threebot.py, jumpscale/sals/vdc/vdc.py, jumpscale/sals/vdc/zdb_auto_topup.py
- Refund addons payment to the prepaid wallet
- Deploy zdb for an hour and if successful, extend the pool with the remaining duration
- multiply the number of nodes that will be deployed by the cost of each one
#2993
#2992
=> refund addons payment to the prepaid wallet

jumpscale/packages/vdc/chats/new_vdc.py, jumpscale/packages/vdc_dashboard/bottle/api/controller.py, jumpscale/packages/vdc_dashboard/bottle/api/exceptions.py, jumpscale/packages/vdc_dashboard/chats/extend_kubernetes.py, jumpscale/packages/vdc_dashboard/chats/extend_storage.py, jumpscale/sals/vdc/deployer.py, jumpscale/sals/vdc/kubernetes_auto_extend.py, jumpscale/sals/vdc/s3_auto_topup.py, jumpscale/sals/vdc/vdc.py, jumpscale/sals/vdc/zdb_auto_topup.py
- Enable public ip for extend kubernetes
- Allow SSD/HDD for storage containers
- Fix deploy more than one storage container
- Increase vdc payment timeout
#2985
#2986
=> Enable public ip in extend kubernetes and allow SSD/HDD for storage containers

jumpscale/packages/vdc_dashboard/chats/etcd.py, jumpscale/packages/vdc_dashboard/chats/minio.py, jumpscale/packages/vdc_dashboard/sals/solutions_chatflow.py
Clear solutions and domain on failure
#2914
=> Clear solutions and domain on failure

docs/wiki/rpc.md, jumpscale/clients/gedis/__init__.py, jumpscale/clients/gedis/gedis.py, jumpscale/servers/gedis/__init__.py, jumpscale/servers/gedis/baseactor.py, jumpscale/servers/gedis/example_actor.py, jumpscale/servers/gedis/server.py, jumpscale/servers/gedis/systemactor.py, jumpscale/servers/gedis_http/__init__.py, pyproject.toml, tests/servers/gedis/test_actors/memory_profiler.py, tests/servers/gedis/test_actors/test_actor.py, tests/servers/gedis/test_actors/test_reloading.py, tests/servers/gedis/test_actors/test_reloading_changed.py, tests/servers/gedis/test_gedis.py
=> Development mv gedis

jumpscale/sals/vdc/deployer.py
Update s3 display message while deploying new VDC
- update `jumpscale/sals/vdc/deployer.py` display message
https://github.com/threefoldtech/js-sdk/issues/3017
=> Update s3 display message for VDC

jumpscale/clients/stellar/stellar.py
- reject empty transactions in stellar client
=> reject empty transactions in stellar client

jumpscale/clients/stellar/stellar.py
=> fix comparison in stellar client

jumpscale/packages/tfgrid_solutions/scripts/threebot/register_dashboard.py, jumpscale/packages/vdc/chats/new_vdc.py, jumpscale/packages/vdc_dashboard/bottle/deployments.py, jumpscale/sals/vdc/namemanager.py, jumpscale/sals/vdc/snapshot.py
Fix backup permission problem
#2959
=> Use removesuffix instead of rstrip

jumpscale/packages/vdc/services/check_health_service.py
=> hotfix health check service

jumpscale/packages/vdc/services/check_health_service.py
=> update phrasing in health service

jumpscale/sals/vdc/kubernetes_auto_extend.py
Skip if node IP is not found
#3013
=> Fix kubernetes node status 

jumpscale/packages/vdc/chats/new_vdc.py, jumpscale/sals/vdc/deployer.py, jumpscale/sals/vdc/kubernetes.py, jumpscale/sals/vdc/threebot.py
=> Hash vdc password in deployer

jumpscale/tools/vdc/reporting/__init__.py
- fix threebot domain state in reporting tool to add "https"
=> fix threebot domain state in reporting tool

jumpscale/sals/vdc/kubernetes_auto_extend.py
- fix kubernetes nodes index error for non-initalized worker nodes
- https://github.com/threefoldtech/js-sdk/issues/3040
=> fix kubernetes nodes index error for non-initalized worker nodes

jumpscale/sals/vdc/deployer.py, jumpscale/sals/vdc/scheduler.py
Exclude accessnodes for all workloads except networks
#3042
=> Exclude accessnodes for all workloads except networks

jumpscale/sals/vdc/deployer.py, jumpscale/sals/vdc/proxy.py, jumpscale/sals/vdc/public_ip.py
- remove duplicate logs as it's added from the vdc logger component
=> remove duplicate logs as it's added from the vdc logger component

jumpscale/clients/explorer/workloads.py, jumpscale/packages/vdc/bottle/api.py, jumpscale/packages/vdc/chats/new_vdc.py, jumpscale/packages/vdc/frontend/components/solutions/Wallet.vue, jumpscale/packages/vdc/frontend/components/solutions/Workloads.vue, jumpscale/packages/vdc/services/update_expiration.py, jumpscale/sals/vdc/vdc.py
- Remove redundant calls while listing vdcs
- Add `state` and `expiration` to vdc instance
- Add service to calculate the vdc expiration every 5 mins
- Only load wallet info when clicking the wallet button
#3007
=> Remove redundant calls while listing vdcs

poetry.lock, pyproject.toml
- add importlib-metadata dependancy
=> add importlib-metadata dependancy

jumpscale/packages/admin/services/notifier.py, jumpscale/packages/vdc/services/check_health_service.py, poetry.lock, pyproject.toml
add telegram notifier send messages to telegram group VDCs Monitoring
https://github.com/threefoldtech/js-sdk/issues/3044
=> add telegram notifier

jumpscale/tools/vdc/reporting/__init__.py
- harden reporting invalid vdcs
- https://github.com/threefoldtech/js-sdk/issues/3056
=> harden reporting invalid vdcs

jumpscale/tools/vdc/reporting/__init__.py
- harden reporting invalid wallet only vdcs
https://github.com/threefoldtech/js-sdk/issues/3056
=> harden reporting invalid wallet only vdcs

jumpscale/packages/vdc/services/check_health_service.py, jumpscale/packages/vdc/services/fund_prices_diff.py, jumpscale/packages/vdc/services/grace_period_service.py
Sleep between iterations in vdc services to not block other services
=> Sleep between iterations in vdc services to not block other services

jumpscale/packages/admin/services/notifier.py
update telegram message format for vdc monitoring 
=> update telegram message format

jumpscale/packages/admin/services/notifier.py, poetry.lock, pyproject.toml
move telegram dependency to temp branch
=> move telegram dependency

jumpscale/packages/admin/frontend/components/solutions/Solution.vue, jumpscale/packages/admin/frontend/components/solutions/Solutions.vue, jumpscale/packages/admin/frontend/data.js, jumpscale/packages/vdc_dashboard/services/bandwidth_limit.py
- Update info links in admin solutions
- Update bandwidth service to select the right interface in case the worker has public IP
#2998
#2968
=> Update info links in admin solutions

jumpscale/sals/billing/models.py
=> Fix comparison between float and Decimal

jumpscale/sals/billing/models.py
=> Fix payment timeout for extending kubernetes workers

jumpscale/packages/admin/frontend/components/solutions/Info.vue, jumpscale/packages/tfgrid_solutions/chats/etcd.py, jumpscale/sals/reservation_chatflow/deployer.py, jumpscale/sals/reservation_chatflow/solutions.py
Deploy etcd cluster on different nodes
- Deploy etcd cluster on different pools and nodes
- Update listing and info for etcd solutions
#3072
- Deployment process
- Solution info
- Deployment process
- Solution info
=> deploy etcd on different nodes

jumpscale/clients/explorer/models.py, jumpscale/clients/explorer/workloads.py, jumpscale/sals/zos/signature.py, jumpscale/sals/zos/virtual_machine.py, jumpscale/sals/zos/workloads.py, jumpscale/sals/zos/zos.py
Adding support in js-sdk for generic VMs.
https://github.com/threefoldtech/home/issues/1047
=> Add generic vms models

jumpscale/packages/threebot_deployer/package.py, jumpscale/sals/nginx/__init__.py, jumpscale/sals/nginx/nginx.py, jumpscale/servers/threebot/threebot.py, jumpscale/tools/nginx/nginxserver.py
Stop using storedFactory with nginx sal 
#3083
=> Stop using storedFactory with nginx sal 

jumpscale/packages/admin/frontend/index.html, jumpscale/packages/chatflows/frontend/index.html, jumpscale/packages/farmmanagement/frontend/index.html, jumpscale/packages/marketplace/frontend/index.html, jumpscale/packages/threebot_deployer/frontend/index.html, jumpscale/packages/vdc/frontend/index.html, jumpscale/packages/vdc_dashboard/frontend/index.html
- Use fixed vuetify version
#3093
=> Use fixed vuetify version

jumpscale/packages/vdc/services/check_threebot.py
Create a service to check vdc threebot if down deploy a new threebot and delete the old one 
#3099
=> Check vdc threebot service

jumpscale/sals/vdc/vdc.py
Fixing race condition while listing vdcs
https://github.com/threefoldtech/itenv_testnet/issues/11
=> Fixing race condition while listing vdcs

jumpscale/packages/farmmanagement/actors/farm_management.py, jumpscale/packages/farmmanagement/frontend/views/farmedit/farmedit.html, jumpscale/packages/farmmanagement/frontend/views/farmedit/farmedit.js
- Validate wallet input
- disabled the trusting field as we use only TFT for now 
- https://github.com/threefoldtech/js-sdk/issues/2701
=> Farm management: Add wallet validation

jumpscale/sals/vdc/models.py, jumpscale/sals/vdc/vdc.py
Fix vdc load info locking
https://github.com/threefoldtech/itenv_testnet/issues/11
=> Fix vdc load info locking

jumpscale/sals/vdc/vdc.py
=> Fix threebot attr in vdc instance 

jumpscale/packages/vdc_dashboard/chats/dash.py, jumpscale/packages/vdc_dashboard/frontend/data.js, jumpscale/packages/vdc_dashboard/package.toml
This is to add a chat-flow for deploying a dash node.
#82
threefoldtech/tf_operations#145
=> Dash : Add chatflow

jumpscale/packages/admin/frontend/App.vue, jumpscale/packages/vdc_dashboard/frontend/App.vue
Add support button
[#2994](https://github.com/threefoldtech/js-sdk/issues/2994)
=> Add support btn

jumpscale/clients/explorer/models.py, jumpscale/packages/farmmanagement/frontend/views/farmmanagement/farmmanagement.css, jumpscale/packages/farmmanagement/frontend/views/farmmanagement/farmmanagement.html, jumpscale/packages/farmmanagement/frontend/views/farmmanagement/farmmanagement.js
-Add the "Upgrade to grid3 pricing" button
- https://github.com/threefoldtech/js-sdk/issues/3096
=> Add the "Upgrade to grid3 pricing" button in FaemMgmt

jumpscale/packages/admin/frontend/App.vue, jumpscale/packages/vdc/frontend/App.vue, jumpscale/packages/vdc_dashboard/frontend/App.vue
Add support btn in VDC
[#2994](https://github.com/threefoldtech/js-sdk/issues/2994)
=> Development support

jumpscale/sals/vdc/models.py
=> Fix compute node size

jumpscale/install/Dockerfile, jumpscale/packages/tfgrid_solutions/scripts/threebot/entrypoint.sh
link the poetry to one of dirs in PATH
#3081
=> Modify the docker file to add a symlink in PATH to the poetry binary

jumpscale/packages/vdc/chats/new_vdc.py, jumpscale/sals/vdc/deployer.py
Check overall resources before starting the vdc deployment
#3144
=> Check overall resources before starting the vdc deployment

jumpscale/packages/vdc/frontend/App.vue
Fix support bar 
[#3151](https://github.com/threefoldtech/js-sdk/issues/3151)
=> Fix support bar

jumpscale/packages/admin/services/notifier.py
=> Fix email notifier

jumpscale/sals/vdc/kubernetes.py
Fix private IP check in kubernetes master
=> Fix private IP check in kubernetes master

jumpscale/packages/vdc/services/check_threebot.py
Improve `check_threebot` service
- Replace `has_minimal_components` with a check on Kubernetes and expiration time
- Add more check to validate that the Kubernetes object has a master node
- Get `pool_id` from workload, not from threebot object
- Deal with `download_kube_config` exceptions to not break the service
- Deal with `deploy_threebot` exceptions to not break the service
#3187
=> Improve check_threebot service

jumpscale/clients/explorer/workloads.py
Apply NextAction filter on listing workloads
https://github.com/threefoldtech/tfexplorer/issues/330
=> Apply NextAction filter on listing workloads

jumpscale/sals/vdc/scheduler.py
Add the number of deployment in the farm search
=> Add the number of deployment in farm search

jumpscale/packages/admin/services/alerts_notifier.py
- Add mail service to notifier the escalation emails with the alerts count every hour.
- jumpscale/packages/admin/services/alerts_notifier.py
- https://github.com/threefoldtech/js-sdk/issues/3203
=> Add alerts notifier service in admin package

jumpscale/tools/servicemanager/servicemanager.py
update docs for service manager to have schedule_on_start
- https://github.com/threefoldtech/js-sdk/issues/3217
=> update docs for service manager to have schedule_on_start

jumpscale/packages/vdc_dashboard/services/upgrade_traefik.py
Schedule upgrade_traefik service to run on start
#3219
=> Schedule upgrade_traefik service to run on start

jumpscale/sals/reservation_chatflow/deployer.py, jumpscale/sals/zos/container.py
Allow HDD disk type for containers
=> Allow HDD disk type for containers

jumpscale/packages/tfgrid_solutions/chats/vmachine.py, jumpscale/sals/reservation_chatflow/deployer.py
fixes for virtual machine chatflow deployments
- Fix node/pool selection
- Fix network creation
- Fix query and cu/su calculations (was for container which made first 50GB for free this case is different)
- Remove over-provision which no longer supported
- https://github.com/threefoldtech/js-sdk/issues/3215
=> fixes for virtual machine chatflow deployments

jumpscale/packages/tfgrid_solutions/chats/vmachine.py, jumpscale/sals/reservation_chatflow/deployer.py, jumpscale/sals/reservation_chatflow/solutions.py
- fix vm solution listing and deletion 
- fix solution listing / deletion
- fix pool query to deploy for at leaset 15 mins
- https://github.com/threefoldtech/js-sdk/issues/3215
=> fix vm solution listing and deletion

jumpscale/packages/vdc_dashboard/bottle/api/deployments.py, jumpscale/packages/vdc_dashboard/chats/vmachine.py, jumpscale/packages/vdc_dashboard/frontend/api.js, jumpscale/packages/vdc_dashboard/frontend/components/marketplace/SolutionChatflow.vue, jumpscale/packages/vdc_dashboard/frontend/components/vdcSettings/Home.vue, jumpscale/packages/vdc_dashboard/frontend/components/vdcSettings/VirtualMachine.vue, jumpscale/packages/vdc_dashboard/frontend/index.js, jumpscale/sals/reservation_chatflow/solutions.py, jumpscale/sals/vdc/deployer.py, jumpscale/sals/vdc/vdc.py, jumpscale/sals/vdc/vmachine.py
- support vms on vdc
- Add vms pane to the vdc settings
- Deploy vms with pub ips and without
- Payment using vdc prepaid wallet
- List & delete vms
- Makes use of the power of vdc retries
- https://github.com/threefoldtech/js-sdk/issues/3215
=> Development vdc vms

tests/servers/gedis/test_gedis.py
Fix redis timout issue in `test02_memory_cleanup` test
- tests/servers/gedis/test_gedis.py
=> Fix redis timout issue

jumpscale/packages/vdc/services/check_threebot.py, jumpscale/packages/vdc/services/update_expiration.py, jumpscale/sals/vdc/vdc.py
- Fix empty/expire check in vdc redeploy threebot service.
- Don't update vdc expiration in case it is still deploying.
- Fix zdb listing in vdc object.
=> Some fixes in vdc

jumpscale/sals/marketplace/apps_chatflow.py
speeds up getting farmers and their checks using gevent greenlets
for the case of needing one farmer the info is communicated using only_one_event
#3229
=> speed up farmers fetching

jumpscale/packages/vdc/services/check_threebot.py
=> Fixes redeploy threebot to not delete other containers

jumpscale/packages/vdc/services/check_threebot.py, jumpscale/sals/vdc/vdc.py
Enhances threebot recovery not to delete threebot if it is unreachable from the first time
Hardens is empty check
#3236
=> Enhances threebot recovery not to delete threebot if it is unreachable

jumpscale/packages/vdc_dashboard/bottle/vdc_helpers.py
Harden get_vdc caching
Harden get_vdc caching
#3240
=> Harden get_vdc caching

jumpscale/packages/vdc/frontend/App.vue, jumpscale/packages/vdc_dashboard/frontend/App.vue
Fix support bar position
[#3150](https://github.com/threefoldtech/js-sdk/issues/3150)
=> Development supportbar

pyproject.toml
=> Update pyproject.toml to the new release

.github/workflows/build_tagged_image.yml
- Update get tag version to align with github actions
=> Update get tag version to align with github

jumpscale/sals/marketplace/apps_chatflow.py, jumpscale/sals/marketplace/deployer.py
- In the case of threebot restart no need for extension
- Fix threebot payment case when pool doesn't need extension
- https://github.com/threefoldtech/tf_support/issues/17
=> Fix threebot payment case when pool doesn't need extension

jumpscale/sals/vdc/deployer.py, jumpscale/sals/vdc/kubernetes.py, jumpscale/sals/vdc/s3.py, jumpscale/sals/vdc/threebot.py
These logs were included for debugging purposes (they cause leaks)
=> Remove time logs

jumpscale/clients/stellar/stellar.py
Tested the new endpoint and works ok
=> Update stellar endpoint to use the new node

jumpscale/sals/marketplace/apps_chatflow.py
- Harden stellar payments in 3bot  deployer
=> Harden stellar payment in threebot deployer

jumpscale/sals/marketplace/apps_chatflow.py
- fix threebot deployer payment  in case of the pool has enough units
- https://github.com/threefoldtech/tf_operations/issues/261
=> fix threebot deployer payment

jumpscale/clients/stellar/stellar.py
- upgrade stellar client to use the new stellar node
- https://github.com/threefoldtech/js-sdk/pull/3287
- https://github.com/threefoldtech/js-sdk/pull/3280
=> upgrade stellar client to use the new stellar node

jumpscale/packages/auth/bottle/auth.py
example signing in that will pop up on phone
- https://github.com/threefoldtech/js-sdk/issues/3339
=> add stellar wallet address to tf connect authentication endpoint

jumpscale/packages/vdc_dashboard/frontend/components/MarkdownViewer.vue
=> vdc_dashboard: convert marked() to marked.parse() after new update

jumpscale/packages/admin/frontend/components/base/MarkdownViewer.vue, jumpscale/packages/chatflows/frontend/components/Markdown.vue, jumpscale/packages/marketplace/frontend/components/MarkdownViewer.vue, jumpscale/packages/threebot_deployer/frontend/components/MarkdownViewer.vue, jumpscale/packages/vdc/frontend/components/MarkdownViewer.vue
fix markdown in vdc also and admin panel
=> fix markdown in all places

jumpscale/tools/vdc/reporting/__init__.py
=> make sure reporting doesn't crash in case master is down

jumpscale/packages/admin/frontend/index.html, jumpscale/packages/chatflows/frontend/index.html, jumpscale/packages/marketplace/frontend/index.html, jumpscale/packages/vdc/frontend/index.html
Fix admin dashboard / 3bot deployers by sticking to vue2
- https://github.com/threefoldtech/tf_operations/issues/681
=> stick to vue 2 which supported for admin dashboard and packages

pyproject.toml
=>  bump js-sdk version to b12

jumpscale/clients/stellar/balance.py, jumpscale/clients/stellar/stellar.py
=> Stellar: fix getting balance from an account with liquidity pool shares

jumpscale/clients/stellar/balance.py, jumpscale/clients/stellar/stellar.py
Fixes for stellar transfer due to updates/removal of some fields/functions in newer stellar-sdk.
=> fix stellar client transfers due to version upgrade of stellar-sdk

jumpscale/clients/stellar/stellar.py
=> Fix stellar client trustline adding

jumpscale/clients/stellar/balance.py
=> Fix escrow account unlock time parsing again

jumpscale/clients/stellar/stellar.py
=> Fix stellar token transfers for non-TFT/xlm

pyproject.toml
release v11.5-b18
v11.5-b17 -> v11.5-b18
=> release v11.5-b18

jumpscale/clients/stellar/vesting.py
=> Adapt stellar client vesting account recognisition to stellar_sdk 8.x

jumpscale/clients/stellar/stellar.py
=> Adapt claiming locked tokens to stellar_sdk 8.x

.github/workflows/black-docstr.yml
fix black actions
- https://github.com/threefoldtech/js-sdk/issues/3415
=> fix black actions
