threefoldtech/js-sdk

- jumpscale/packages/chatflows/package.toml
- jumpscale/sals/nginx/nginx.py
- jumpscale/sals/nginx/templates/website.conf
issue: https://github.com/threefoldtech/js-sdk/issues/16
> fail back to self-signed certs if certbot failed

- jumpscale/servers/threebot/threebot.py
see https://github.com/threefoldtech/js-sdk/issues/35
> clone repo when adding package using the giturl instead of using the api

- jumpscale/packages/admin/actors/packages.py
- jumpscale/packages/chatflows/bottle/bottle.py
- jumpscale/servers/threebot/__init__.py
- jumpscale/servers/threebot/threebot.py
issue: https://github.com/threefoldtech/js-sdk/issues/65
> Development threebot running server

- docs/wiki/threebot.md
for issue: https://github.com/threefoldtech/js-sdk/issues/56
> add docs for nginx start without root

- jumpscale/sals/nginx/templates/website.conf
for issue: https://github.com/threefoldtech/js-ng/issues/312
> increase request timeout

- jumpscale/packages/codeserver/codeserver-install.sh
- jumpscale/packages/codeserver/package.py
See https://github.com/threefoldtech/js-sdk/issues/62
> Added codeserver installation on adding package

- jumpscale/packages/chatflows/actors/chatbot.py
- jumpscale/packages/chatflows/frontend/App.vue
- jumpscale/sals/chatflows/chatflows.py
see https://github.com/threefoldtech/js-sdk/issues/51
> port chatflow state

- jumpscale/packages/tfgrid_solutions/chats/ubuntu_deploy.py
- jumpscale/sals/reservation_chatflow/reservation_chatflow.py
- Add parent_network to metadata of any reservation that adds nodes to an existing network
- when deleting a network from admin panel that has a parent network(or more), all parent networks are cancelled from the explorer as well
- fix use of DistType .SSD enum value and name in ubuntu solution deploy
https://github.com/threefoldtech/js-sdk/issues/48
> Development network solutions

- jumpscale/sals/reservation_chatflow/reservation_chatflow.py
issue: https://github.com/threefoldtech/js-sdk/issues/89
depends on: https://github.com/threefoldtech/js-ng/pull/366
> show seconds

- jumpscale/sals/nginx/nginx.py
- jumpscale/sals/nginx/templates/location.conf
- poetry.lock
issue: https://github.com/threefoldtech/js-sdk/issues/31
disable auth if threebot_connect is False
> remove auth if thrrebot_connect is false

- jumpscale/servers/threebot/threebot.py
- jumpscale/tools/nginx/nginxserver.py
- jumpscale/tools/redis/redis.py
See https://github.com/threefoldtech/js-sdk/issues/64
> Checking all dependencies are installed before starting threebot

- jumpscale/entry_points/threebot.py
issue: https://github.com/threefoldtech/js-sdk/issues/106
> wait for threebot ports

- jumpscale/clients/explorer/__init__.py
- jumpscale/core/identity/__init__.py
issue: https://github.com/threefoldtech/js-sdk/issues/113
> Fix identity set default and explorer set default addr

- tests/clients/github/test_githubclient.py
resolves https://github.com/threefoldtech/js-ng/issues/372
> move sdk related tests

- jumpscale/packages/weblibs/package.py
issue: https://github.com/threefoldtech/js-sdk/issues/103
> handled cloning weblibs failure

- docs/wiki/threebot.md
- docs/wiki/tutorials/deploying_website_and_packages.md
- jumpscale/entry_points/threebot.py
- jumpscale/packages/admin/actors/packages.py
- jumpscale/packages/chatflows/bottle/bottle.py
- jumpscale/servers/threebot/__init__.py
- jumpscale/servers/threebot/threebot.py
issue: https://github.com/threefoldtech/js-sdk/issues/117
> threebot status/restart

- jumpscale/clients/stellar/stellar.py
- jumpscale/sals/zos/billing.py
Fix get_belance for other wallet addresses
See: #127 and https://github.com/threefoldtech/jumpscaleX_libs/issues/237
> Raise exception when wallet does not have funds/trustlines

- jumpscale/clients/digitalocean/digitalocean.py
Related to this issue https://github.com/threefoldtech/js-ng/issues/156
Fix bugs in the digital ocean client and update the docs
> fix bugs in Digital Ocean client and update its docs

- jumpscale/clients/stellar/stellar.py
see: https://laboratory.stellar.org/#explorer?resource=payments&endpoint=for_transaction&values=eyJ0cmFuc2FjdGlvbiI6IjAxODJjM2E2M2MyZDdhZjFhN2Q0YzcwNzQyMDNjZGYwYjA0ZTEwM2QyMGY4MzUyMDFjYjNhOWZmZDk3NzEwOTQifQ%3D%3D&network=test
> add method to get sender address from transaction

- jumpscale/clients/digitalocean/digitalocean.py
code refactoring and fixing bugs
> Development digital ocean

- jumpscale/entry_points/threebot.py
- jumpscale/tools/nginx/nginxserver.py
> Improvements in starting/stopping nginx for threebot

- jumpscale/packages/tfgrid_solutions/chats/minio_deploy.py
- jumpscale/sals/reservation_chatflow/reservation_chatflow.py
issue: https://github.com/threefoldtech/js-sdk/issues/135
> update minio for zdb result & accept form_info without chatflow key

- jumpscale/servers/threebot/threebot.py
- jumpscale/tools/nginx/nginxserver.py
> Make threebostart use the correct nginx config

- jumpscale/entry_points/threebot.py
- jumpscale/servers/threebot/threebot.py
> Add some logs to threebot start and allow foreground start

- jumpscale/core/identity/__init__.py
> Prevent getting empty explorer

- jumpscale/clients/stellar/stellar.py
Some transactions doesn't have an amount like activating the wallet
This helper method to help in iterating in transactions
> add method to stellar client to check transactions for amount

- jumpscale/packages/admin/actors/admin.py
- jumpscale/packages/admin/actors/alerts.py
- jumpscale/packages/admin/actors/health.py
- jumpscale/packages/admin/actors/logs.py
- jumpscale/packages/admin/actors/packages.py
- jumpscale/packages/admin/actors/wallet.py
- jumpscale/packages/kyc/actors/api.py
- jumpscale/packages/kyc/bottle/bottle.py
- jumpscale/packages/kyc/package.py
- jumpscale/sals/chatflows/polls.py
use new loader
https://github.com/threefoldtech/js-sdk/issues/147
> replace old loader with new loader

- jumpscale/install/Dockerfile
- jumpscale/install/codeserver-install.py
Fixing https://github.com/threefoldtech/js-ng/issues/84
> Added Dockerfile for js-sdk

- jumpscale/servers/threebot/threebot.py
Fixing issue  https://github.com/threefoldtech/js-sdk/issues/136
- Check if an error happened during loading and installing packages
- If the error happened so I stop the server
> fixing issue related to starting threebot and there is an error in package

- jumpscale/servers/threebot/threebot.py
This is related to issue https://github.com/threefoldtech/js-sdk/issues/126
I have prevented the method from being public
> change install_all method from being public

- jumpscale/entry_points/threebot.py
- jumpscale/tools/redis/redis.py
https://github.com/threefoldtech/js-sdk/issues/179
> refactor redis tool

- jumpscale/packages/chatflows/actors/chatbot.py
- jumpscale/packages/chatflows/frontend/App.vue
- jumpscale/packages/tfgrid_solutions/chats/4to6gw.py
- jumpscale/packages/tfgrid_solutions/chats/domain_delegation.py
- jumpscale/packages/tfgrid_solutions/chats/flist_deploy.py
- jumpscale/packages/tfgrid_solutions/chats/gitea_deploy.py
- jumpscale/packages/tfgrid_solutions/chats/kubernetes_deploy.py
- jumpscale/packages/tfgrid_solutions/chats/minio_deploy.py
- jumpscale/packages/tfgrid_solutions/chats/monitoring_deploy.py
- jumpscale/packages/tfgrid_solutions/chats/network_deploy.py
- jumpscale/packages/tfgrid_solutions/chats/solution_expose.py
- jumpscale/packages/tfgrid_solutions/chats/ubuntu_deploy.py
- jumpscale/sals/chatflows/chatflows.py
Fixing https://github.com/threefoldtech/js-sdk/issues/166
> Added chatflow title property

- docs/wiki/threebot.md
- jumpscale/entry_points/threebot.py
- jumpscale/servers/threebot/threebot.py
Add some docs about packages
Improve log lines inside threebot
See: #189
> Improve nginx config for checking local ports

- docs/wiki/identity.md
- jumpscale/core/identity/__init__.py
> Improve error message when setting up an identity

- jumpscale/packages/admin/frontend/api.js
- jumpscale/packages/admin/frontend/components/solutions/Info.vue
- jumpscale/packages/admin/frontend/components/solutions/Solutions.vue
- jumpscale/packages/admin/frontend/data.js
- jumpscale/sals/reservation_chatflow/reservation_chatflow.py
issue : https://github.com/threefoldtech/js-sdk/issues/71
> Added old reservation view

- jumpscale/packages/chatflows/actors/chatbot.py
- jumpscale/packages/chatflows/frontend/App.vue
- jumpscale/packages/tfgrid_solutions/chats/4to6gw.py
- jumpscale/packages/tfgrid_solutions/chats/domain_delegation.py
- jumpscale/packages/tfgrid_solutions/chats/flist_deploy.py
- jumpscale/packages/tfgrid_solutions/chats/gitea_deploy.py
- jumpscale/packages/tfgrid_solutions/chats/kubernetes_deploy.py
- jumpscale/packages/tfgrid_solutions/chats/minio_deploy.py
- jumpscale/packages/tfgrid_solutions/chats/monitoring_deploy.py
- jumpscale/packages/tfgrid_solutions/chats/network_deploy.py
- jumpscale/packages/tfgrid_solutions/chats/solution_expose.py
- jumpscale/packages/tfgrid_solutions/chats/ubuntu_deploy.py
See https://github.com/threefoldtech/js-sdk/issues/177
- Session is invalidated on client side on server restart instead of showing "Chat ended"
- Now when you refresh on the last step, it ends the chatflow.
> Chatflows session invalidation on server restart

- jumpscale/packages/chatflows/actors/chatbot.py
This allows relative imports inside the chatflow and the package it
belongs into
> Attempt to load chatflow inside the correct package

- jumpscale/packages/admin/frontend/components/solutions/Solutions.vue
- jumpscale/sals/reservation_chatflow/reservation_chatflow.py
issue: https://github.com/threefoldtech/js-sdk/issues/71
> handle missing domains in old reservation

- jumpscale/sals/reservation_chatflow/reservation_chatflow.py
issue: https://github.com/threefoldtech/js-ng/issues/409
> fixed chatflow types checks

- jumpscale/entry_points/threebot.py
- jumpscale/sals/nginx/nginx.py
> fixes typo for is port listening

- jumpscale/packages/admin/frontend/api.js
- jumpscale/packages/admin/frontend/components/solutions/CancelSolution.vue
- jumpscale/packages/admin/frontend/components/solutions/Info.vue
See https://github.com/threefoldtech/js-sdk/issues/218
> Added cancel reservation in admin dashboard

- jumpscale/core/identity/__init__.py
See https://github.com/threefoldtech/js-sdk/issues/222
> Fixing duplicate admins in identity

- jumpscale/packages/admin/actors/admin.py
See https://github.com/threefoldtech/js-sdk/issues/222
> Added checks in admin add/remove actors

- jumpscale/packages/chatflows/frontend/components/Markdown.vue
- jumpscale/packages/polls/chats/threefold.py
see https://github.com/threefoldtech/js-sdk/issues/239
> make links in polls opens in new tab

- jumpscale/sals/nginx/templates/location.conf
- jumpscale/servers/threebot/threebot.py
> nginx: fix accessing locations without slashes

- jumpscale/sals/chatflows/polls.py
for issue: https://github.com/threefoldtech/js-sdk/issues/212
> add locked funds to calculations

- jumpscale/packages/admin/actors/wallet.py
- jumpscale/packages/admin_old/actors/wallet.py
- jumpscale/packages/farmmanagement/actors/farm_management.py
- jumpscale/sals/reservation_chatflow/reservation_chatflow.py
- jumpscale/sals/zos/zos.py
for issue: https://github.com/threefoldtech/js-sdk/issues/250
> fix default explorer to be taken from the identity rather than client

- jumpscale/packages/admin/actors/wallet.py
- jumpscale/packages/admin/frontend/components/wallets/Import.vue
> Add validations for wallet imports from admin dasshboard

- jumpscale/packages/admin/frontend/components/external/Notebooks.vue
- jumpscale/packages/admin/frontend/index.js
- jumpscale/packages/notebooks/package.py
- jumpscale/packages/notebooks/package.toml
- jumpscale/servers/threebot/threebot.py
isssue: https://github.com/threefoldtech/js-sdk/issues/263
> Added notebooks package

- jumpscale/packages/polls/chats/threefold.py
issue: https://github.com/threefoldtech/js-sdk/issues/279
> remove the where did you get your tokens question ant its %

- jumpscale/packages/polls/bottle/__init__.py
- jumpscale/packages/polls/bottle/polls_bottle.py
- jumpscale/packages/polls/chats/threefold.py
- jumpscale/packages/polls/package.toml
- jumpscale/sals/chatflows/models/voter_model.py
- jumpscale/sals/chatflows/polls.py
for issue: https://github.com/threefoldfoundation/home/issues/69
added endpoints 
for tf council
added:
/api/names
/api/results
> Development threefold poll update

- jumpscale/packages/tfgrid_solutions/chats/publisher.py
issue: https://github.com/threefoldtech/js-sdk/issues/293
> use trc inside publisher flist

- jumpscale/packages/marketplace/package.py
- jumpscale/packages/marketplace/package.toml
https://github.com/threefoldtech/js-sdk/issues/331
> redirect / to marketplace on prod domain

- jumpscale/packages/stellar_stats/README.md
- jumpscale/packages/stellar_stats/bottle/stats_service.py
- jumpscale/packages/stellar_stats/bottle/stellar_stats.py
- jumpscale/packages/stellar_stats/package.toml
for issue: https://github.com/threefoldfoundation/tft-stellar/issues/182
> add stellar stats package

- jumpscale/packages/marketplace/chats/publisher.py
- jumpscale/packages/tfgrid_solutions/chats/publisher.py
fixes: https://github.com/threefoldtech/js-sdk/issues/337
> validate domains

- jumpscale/packages/marketplace/frontend/components/Home.vue
- jumpscale/packages/marketplace/frontend/components/License.vue
> update dashboard landing

- jumpscale/packages/marketplace/chats/minio.py
- jumpscale/packages/tfgrid_solutions/chats/minio_deploy.py
> fix minio network

- jumpscale/packages/admin/frontend/components/solutions/Info.vue
- jumpscale/packages/admin/frontend/components/solutions/Solutions.vue
- jumpscale/packages/admin/frontend/index.html
issue : https://github.com/threefoldtech/js-sdk/issues/354
Added new details view
and used new json viewer
> update solution details info view

- jumpscale/clients/bcdb/auth.py
- jumpscale/packages/marketplace/actors/backup.py
- jumpscale/packages/tfgrid_solutions/scripts/threebot/entrypoint.py
- jumpscale/sals/marketplace/deployer.py
- jumpscale/servers/threebot/threebot.py
Related #367 
should fix this https://github.com/threefoldtech/js-sdk/issues/370
> fix docs generation and adding the same package twice

- jumpscale/sals/marketplace/chatflow.py
to be able  to verify against session
```
> /home/waleed/js-sdk/jumpscale/sals/marketplace/chatflow.py(13)_validate_user()
-> user_factory = StoredFactory(UserEntry)
(Pdb) '0xIslamTaha.3bot'
(Pdb) > /home/waleed/js-sdk/jumpscale/sals/marketplace/chatflow.py(14)_validate_user()
-> explorer_url = j.core.identity.me.explorer.url
(Pdb) > /home/waleed/js-sdk/jumpscale/sals/marketplace/chatflow.py(16)_validate_user()
-> if "testnet" in explorer_url:
(Pdb) {'testnet_waleedhammam', 'testnet_0xislamtaha', 'testnet_0xwaleedhammam'}
(Pdb)  11            pdb.set_trace()
12            tname = self.user_info()["username"]
13            user_factory = StoredFactory(UserEntry)
14            explorer_url = j.core.identity.me.explorer.url
15    
16  ->          if "testnet" in explorer_url:
17 …
```
> unifiy all 3bot names to be lower case

- jumpscale/clients/explorer/__init__.py
- jumpscale/clients/explorer/explorer.py
- jumpscale/core/identity/__init__.py
> clean up identity

- jumpscale/sals/marketplace/deployer.py
in case threebot name starts with a number
> add prefix to threebot naming

- tests/loadtesting/README.md
- tests/loadtesting/admin.py
- tests/loadtesting/run_locust.sh
https://github.com/threefoldtech/js-sdk/issues/339
- Create load testing
- Add bash script to run the load testing
- Add docs
> Development load testing

- tests/loadtesting/README.md
- tests/loadtesting/admin_gedis.py
- tests/loadtesting/run_locust.sh
regarding this issue 
https://github.com/threefoldtech/js-sdk/issues/339
- Separate `Gedis` script in a different file.
> update the code to directly use the host and separate the gedis endpoint

- jumpscale/packages/admin/frontend/components/solutions/Solutions.vue
- jumpscale/packages/marketplace/chats/kubernetes.py
- jumpscale/packages/tfgrid_solutions/actors/solutions.py
- jumpscale/packages/tfgrid_solutions/chats/kubernetes_deploy.py
- jumpscale/sals/marketplace/deployer.py
- jumpscale/sals/reservation_chatflow/deployer.py
1- change pools button to `create/extend` https://github.com/threefoldtech/js-sdk/issues/385
2- show farm name next to pool id 
3- distribute k8s cluster nodes on different nodes https://github.com/threefoldtech/zos/issues/881#issuecomment-669130600
4- show workload type in all workloads view
> Development capacitypool improvements

- jumpscale/packages/admin/frontend/components/settings/IdentityInfo.vue
- jumpscale/sals/chatflows/chatflows.py
- issue: https://github.com/threefoldtech/js-sdk/issues/416
include alert id for non admin users and alert's page link for admins
- issue: https://github.com/threefoldtech/js-sdk/issues/383
reload admin page after changing identity
> Development capacitypool changes

- jumpscale/packages/marketplace/chats/gollum.py
- jumpscale/packages/marketplace/frontend/App.vue
- jumpscale/packages/marketplace/frontend/components/solutions/Solutions.vue
- jumpscale/sals/marketplace/solutions.py
See https://github.com/threefoldtech/js-sdk/issues/429
> Adding gollum chatflow in marketplace

- jumpscale/packages/admin/frontend/data.js
- jumpscale/packages/marketplace/chats/blog.py
- jumpscale/packages/marketplace/chats/website.py
- jumpscale/packages/marketplace/chats/wiki.py
- jumpscale/packages/marketplace/frontend/App.vue
- jumpscale/packages/marketplace/frontend/components/solutions/Solutions.vue
- jumpscale/packages/tfgrid_solutions/chats/blog_deploy.py
- jumpscale/packages/tfgrid_solutions/chats/publisher.py
- jumpscale/packages/tfgrid_solutions/chats/website_deploy.py
- jumpscale/packages/tfgrid_solutions/chats/wiki_deploy.py
- jumpscale/sals/reservation_chatflow/solutions.py
for issue: https://github.com/threefoldtech/js-sdk/issues/433
admin
marketplace
individual
> refactor publisher into three chatflows

- jumpscale/packages/admin/frontend/api.js
- jumpscale/packages/admin/frontend/components/dashboard/Pools.vue
- jumpscale/packages/admin/frontend/components/pools/HidePool.vue
- jumpscale/packages/admin/frontend/components/pools/Pool.vue
- jumpscale/packages/admin/frontend/components/pools/Pools.vue
- jumpscale/packages/admin/frontend/components/workloads/CancelWorkload.vue
- jumpscale/packages/admin/frontend/components/workloads/PatchCancel.vue
- jumpscale/packages/admin/frontend/components/workloads/Workload.vue
- jumpscale/packages/admin/frontend/components/workloads/Workloads.vue
- jumpscale/packages/tfgrid_solutions/actors/solutions.py
- jumpscale/packages/tfgrid_solutions/chats/network_deploy.py
- jumpscale/packages/tfgrid_solutions/chats/pools_reservation.py
- jumpscale/packages/tfgrid_solutions/models/__init__.py
- jumpscale/sals/marketplace/deployer.py
- jumpscale/sals/reservation_chatflow/deployer.py
- jumpscale/sals/reservation_chatflow/solutions.py
naming and hiding pools. issue: https://github.com/threefoldtech/js-sdk/issues/382
patch delete for workloads
> Development capacitypool hidden pools

- jumpscale/sals/reservation_chatflow/deployer.py
> Adds expose_and_create_certificate for solutions

- jumpscale/clients/explorer/models.py
Hopefully helps in the UI part to show the location next to the farm if available
> improve to str for farms and locations

- jumpscale/packages/admin/frontend/api.js
- jumpscale/packages/admin/frontend/components/pools/HiddenPools.vue
- jumpscale/packages/admin/frontend/components/pools/Pool.vue
- jumpscale/packages/admin/frontend/components/pools/Pools.vue
- jumpscale/packages/admin/frontend/components/workloads/CancelWorkload.vue
- jumpscale/packages/admin/frontend/components/workloads/PatchCancel.vue
- jumpscale/packages/admin/frontend/components/workloads/Workloads.vue
- jumpscale/packages/tfgrid_solutions/actors/solutions.py
manage hidden pools: https://github.com/threefoldtech/js-sdk/issues/382
> manage hidden pools

- jumpscale/packages/tfgrid_solutions/chats/publisher.py
- jumpscale/sals/reservation_chatflow/reservation_chatflow.py
- jumpscale/sals/zos/network.py
for issues: https://github.com/threefoldtech/js-sdk/issues/463, https://github.com/threefoldtech/js-sdk/issues/457, https://github.com/threefoldtech/js-sdk/issues/459
> Development solutionshotfixes

- jumpscale/packages/auth/bottle/auth.py
- jumpscale/sals/reservation_chatflow/deployer.py
> Development capacitypool auth

- jumpscale/packages/farmmanagement/actors/farm_management.py
- jumpscale/packages/farmmanagement/frontend/services/farmmanagementServices.js
- jumpscale/packages/farmmanagement/frontend/store/farmmanagement.js
- jumpscale/packages/farmmanagement/frontend/views/farmmanagement/farmmanagement.html
- jumpscale/packages/farmmanagement/frontend/views/farmmanagement/farmmanagement.js
> farm management: allow to change the owner of a farm

- jumpscale/sals/reservation_chatflow/deployer.py
- added option testcert to avoid ratelimit in debugging
> add testcert option for nginx container

- .github/workflows/js-sdk.yml
- Makefile
- conftest.py
- pyproject.toml
- tests/README.md
- tests/integration/test_payment.py
> add payment tests

- jumpscale/packages/admin/frontend/components/solutions/Info.vue
- jumpscale/packages/admin/frontend/components/workloads/Workload.vue
- jumpscale/packages/admin/frontend/components/workloads/Workloads.vue
- jumpscale/packages/admin/frontend/data.js
issue: https://github.com/threefoldtech/js-sdk/issues/476
Added three filters on workload data:
1. `KeysIgnored` : to ignore keys in workload tab view
2. `KeysWithTypeList` : to view keys with type list in `v-chip` tag
3. `KeysWithTypeDict` : to view keys with type dict in `v-chip` tag with pattern `key : value`
> Development capacitypool ui improve

- jumpscale/packages/marketplace/chats/network.py
- jumpscale/packages/tfgrid_solutions/chats/network_deploy.py
- jumpscale/sals/marketplace/deployer.py
- jumpscale/sals/reservation_chatflow/deployer.py
- jumpscale/sals/reservation_chatflow/reservation_chatflow.py
- jumpscale/sals/zos/node_finder.py
https://github.com/threefoldtech/js-sdk/issues/487
> schedule according to nodes in pool

- jumpscale/servers/threebot/threebot.py
https://github.com/threefoldtech/js-sdk/issues/518
I have used a list method to take a snapshot of the dictionary to be able to remove from it during iteration without raise a runtime exception
> Take a a snapshot of the dict to be able to delete in runtime

- jumpscale/sals/chatflows/chatflows.py
stop the chatflow when an error occurs
jumpscale/sals/chatflows/chatflows.py
https://github.com/threefoldtech/js-sdk/issues/471
> stop the chatflow on erros

- jumpscale/sals/nginx/nginx.py
- jumpscale/sals/nginx/templates/nginx.conf
Cherry-picked the nginx-dirs-fix commit on development
- jumpscale/sals/nginx/templates/nginx.conf
- jumpscale/sals/nginx/nginx.py
- https://github.com/threefoldtech/js-sdk/pull/519
> Cherry-pick nginx-dirs-fix from development

- jumpscale/packages/admin/frontend/Identity.vue
- jumpscale/packages/admin/frontend/components/settings/AddAdmin.vue
- jumpscale/packages/admin/frontend/components/settings/AddIdentity.vue
- jumpscale/packages/admin/frontend/components/settings/IdentityInfo.vue
- jumpscale/packages/admin/frontend/data.js
- jumpscale/packages/auth/__init__.py
- jumpscale/packages/auth/bottle/auth.py
- jumpscale/packages/auth/bottle/templates/access_denied.html
- jumpscale/packages/farmmanagement/frontend/views/farmmanagement/farmmanagement.html
- jumpscale/packages/marketplace/actors/backup.py
- jumpscale/packages/marketplace/chats/ubuntu_simple.py
- jumpscale/packages/marketplace/frontend/App.vue
- jumpscale/packages/marketplace/frontend/components/Home.vue
- jumpscale/packages/marketplace/frontend/components/solutions/Solutions.vue
- jumpscale/packages/tfgrid_solutions/chats/publisher.py
- jumpscale/packages/tfgrid_solutions/chats/threebot.py
- jumpscale/sals/marketplace/solutions.py
- jumpscale/sals/reservation_chatflow/README.md
- jumpscale/sals/reservation_chatflow/deployer.py
- jumpscale/sals/reservation_chatflow/reservation_chatflow.py
1. Change threebot to 3Bot in marketplace and admin dashboard.
2. Enhance payment statement.
3. Typo in taiga.
> rename threebot->3Bot, enhance payment statement

- jumpscale/sals/reservation_chatflow/solutions.py
refactor solutions listing in admin
solutions.py
....
> refactor listing

- jumpscale/packages/tfgrid_solutions/chats/gollum_deploy.py
- jumpscale/packages/tfgrid_solutions/chats/mattermost.py
- jumpscale/packages/tfgrid_solutions/chats/peertube.py
- jumpscale/packages/tfgrid_solutions/chats/threebot.py
- jumpscale/sals/zos/gateway.py
> Adds domain correction method for invalid chars

- jumpscale/packages/tfgrid_solutions/chats/publisher.py
- jumpscale/sals/reservation_chatflow/solutions.py
> fix publisher

- jumpscale/sals/marketplace/deployer.py
- jumpscale/sals/reservation_chatflow/deployer.py
- jumpscale/sals/reservation_chatflow/solutions.py
improve payment message
sals/marketplace/deployer.py
sals/reservation_chatflow/deployer.py
https://github.com/threefoldtech/js-sdk/issues/561
> Development cp payment message

- jumpscale/packages/admin/frontend/components/alerts/Alerts.vue
- jumpscale/packages/admin/frontend/components/base/Dialog.vue
- jumpscale/packages/admin/frontend/components/dashboard/Pools.vue
- jumpscale/packages/admin/frontend/components/dashboard/Processes.vue
- changed cursor when hovering row of data tables
- remove the persistent feature from the dialog
- [Alerts view doesn't show the rows as clickable](https://github.com/threefoldtech/js-sdk/issues/535)
- [escape doesn't close dialogs](https://github.com/threefoldtech/js-sdk/issues/532)
- [all dialogs should be closed on pressing escape](https://github.com/threefoldtech/js-sdk/issues/536)
> Development capacitypool ui fix

- jumpscale/packages/admin/frontend/data.js
Updated solutions descriptions
https://github.com/threefoldtech/js-sdk/issues/556
> Updating solutions descriptions

- jumpscale/packages/marketplace/chats/cryptpad.py
- jumpscale/packages/marketplace/chats/mattermost.py
- jumpscale/packages/marketplace/chats/peertube.py
- jumpscale/packages/tfgrid_solutions/chats/cryptpad_deploy.py
- jumpscale/packages/tfgrid_solutions/chats/flist_deploy.py
- jumpscale/packages/tfgrid_solutions/chats/mattermost.py
- jumpscale/packages/tfgrid_solutions/chats/peertube.py
- jumpscale/sals/crtsh/__init__.py
- jumpscale/sals/reservation_chatflow/deployer.py
> fix error messages for volumes

- jumpscale/sals/marketplace/apps_chatflow.py
improve wiregaurd message in app chatflows
https://github.com/threefoldtech/js-sdk/issues/564
> fix message

- jumpscale/sals/marketplace/deployer.py
> fix minio placement

- jumpscale/sals/marketplace/deployer.py
Added chatflow payment wait message
https://github.com/threefoldtech/js-sdk/issues/562
> Chatflow payment wait message

- docs/wiki/tutorials/add_marketplace_chatflow.md
- jumpscale/packages/marketplace/chats/cryptpad.py
- jumpscale/packages/marketplace/chats/discourse.py
- jumpscale/packages/marketplace/chats/mattermost.py
- jumpscale/packages/marketplace/chats/peertube.py
- jumpscale/packages/marketplace/chats/publisher.py
changed overview title from `Confirmation` to `Deployment Information`
- [solution confirmation asking me for more than I choose](https://github.com/threefoldtech/js-sdk/issues/563)
> changed apps overview title

- jumpscale/sals/reservation_chatflow/solutions.py
> fix marketplace filtering

- jumpscale/sals/marketplace/apps_chatflow.py
> check letsencrypt limit

- jumpscale/sals/crtsh/__init__.py
> fix rate limit check

- jumpscale/packages/tfgrid_solutions/chats/peertube.py
This is to make the admin dashboard peertube solution compatible with the new image changes. It now uses nginx certbot to create a test certificates and serve the given domain name.
> use nginx for certificates in admin dashboard

- jumpscale/packages/marketplace/chats/peertube.py
> improve peertube success message

- jumpscale/packages/marketplace/chats/peertube.py
- jumpscale/sals/marketplace/solutions.py
- jumpscale/sals/reservation_chatflow/reservation_chatflow.py
- jumpscale/sals/reservation_chatflow/solutions.py
> Development cp overprovisioning

- jumpscale/packages/backup/actors/marketplace.py
- jumpscale/packages/marketplace/chats/discourse.py
- jumpscale/packages/marketplace/chats/peertube.py
- jumpscale/packages/marketplace/chats/taiga.py
- jumpscale/packages/tfgrid_solutions/chats/discourse.py
- jumpscale/packages/tfgrid_solutions/chats/peertube.py
- jumpscale/packages/tfgrid_solutions/chats/publisher.py
- jumpscale/packages/tfgrid_solutions/chats/taiga_deploy.py
- jumpscale/sals/reservation_chatflow/deployer.py
- jumpscale/sals/reservation_chatflow/solutions.py
> use test_cert globally

- jumpscale/packages/admin/frontend/components/packages/Package.vue
Fixed random height of package section according to package path length
- Increased height of section
- Trimmed long pacakge path
https://github.com/threefoldtech/js-sdk/issues/580
> UI long package path fix

- jumpscale/sals/marketplace/solutions.py
Fixed typo in marketplace sals of listing discourse apps
> Discourse typo fix in sals listing of discourse solutions

- jumpscale/packages/marketplace/chats/cryptpad.py
- jumpscale/packages/marketplace/chats/taiga.py
- jumpscale/packages/tfgrid_solutions/chats/cryptpad_deploy.py
- jumpscale/packages/tfgrid_solutions/chats/discourse.py
- jumpscale/packages/tfgrid_solutions/chats/taiga_deploy.py
Fixed solutions metadata in apps
https://github.com/threefoldtech/js-sdk/issues/547
> Fixed solutions metadata in apps

- jumpscale/packages/tfgrid_solutions/scripts/threebot/entrypoint.py
> fix threebot entrypoint

- jumpscale/packages/admin/frontend/index.html
- jumpscale/packages/marketplace/frontend/index.html
add title and favicon for admin and marketplace
> Development cp titles

- docs/wiki/tutorials/add_marketplace_chatflow.md
- jumpscale/packages/marketplace/chats/cryptpad.py
- jumpscale/packages/marketplace/chats/discourse.py
- jumpscale/packages/marketplace/chats/mattermost.py
- jumpscale/packages/marketplace/chats/peertube.py
- jumpscale/packages/marketplace/chats/publisher.py
- jumpscale/sals/marketplace/apps_chatflow.py
Fix solution name step conflict with attribute name
https://github.com/threefoldtech/js-sdk/issues/579
> Fix solution name step conflict with attribute name

- jumpscale/packages/tfgrid_solutions/chats/threebot.py
- jumpscale/packages/tfgrid_solutions/scripts/threebot/entrypoint.py
Generate self signed certificate if test_cert is set to true.
> Development capacitypool threebot testcert

- jumpscale/packages/admin/frontend/components/packages/Package.vue
Added packages UI icons tooltips
https://github.com/threefoldtech/js-sdk/issues/624
> Added packages UI icons tooltips

- jumpscale/packages/marketplace/chats/cryptpad.py
- jumpscale/packages/marketplace/chats/discourse.py
- jumpscale/packages/marketplace/chats/mattermost.py
- jumpscale/packages/marketplace/chats/peertube.py
- jumpscale/packages/marketplace/chats/publisher.py
Disable previous step button after payment in apps chatflow
https://github.com/threefoldtech/js-sdk/issues/620
> Disable previous step button after payment in apps chatflow

- jumpscale/packages/marketplace/chats/taiga.py
- jumpscale/packages/tfgrid_solutions/chats/taiga_deploy.py
Hotfix to avoid hardcoding flask secret in taiga solution
Use idgenerator to generate a flask secret
> Development taigahotfix

- jumpscale/sals/marketplace/apps_chatflow.py
- jumpscale/sals/marketplace/deployer.py
- show pools with minimum cu/su enough for the solution in marketplace
- pass resource query in app chatflows
https://github.com/threefoldtech/js-sdk/issues/603
> fix query and pool selection in marketplace

- jumpscale/servers/threebot/threebot.py
Handle the deletion of corrupted package, prevent it from raising an exception, remove it from the configuration dictionary, and raise a warning in this case. 
https://github.com/threefoldtech/js-sdk/issues/143
> Development  delete corrupted package

- jumpscale/packages/marketplace/frontend/data.js
Fixed bad merge of taiga description
> Fixed taiga description after merging capacitypool

- jumpscale/packages/marketplace/chats/kubernetes.py
> fix start in k8s marketplace

- jumpscale/packages/marketplace/chats/publisher.py
- jumpscale/packages/tfgrid_solutions/chats/publisher.py
- make publisher to repect test_cert in marketplace
- fix domain in publisher tfgrid solutions
thanks @AhmedHanafy725
> publisher hotfixes

- jumpscale/packages/marketplace/frontend/components/solutions/Info.vue
Restore old json render (leftover from dark theme pr).
> restore old json render

- jumpscale/packages/admin/frontend/components/dashboard/Pools.vue
Fixed error in console on opening dashboard
- Checking selection of pool to render pools-info component
https://github.com/threefoldtech/js-sdk/issues/654
> Fixed error in console on opening dashboard

- docs/wiki/marketplace/deployment.md
- jumpscale/packages/marketplace/scripts/backup.sh
> update marketplace backup docs

- jumpscale/packages/marketplace/chats/taiga.py
Fix taiga not listing its solutions in the marketplace
Add the solution name and chatflow to the metadata before deployment.
> add solution metadata before deploying taiga

- jumpscale/packages/admin/frontend/components/solutions/Solutions.vue
- jumpscale/packages/marketplace/frontend/components/Home.vue
- renamed advanced solutions to Infrastructure solutions and add tooltip `Threefold grid primitives`
- added tooltip for apps: `Threefold end user applications`
- [rename advanced solutions -> Infrastructure solutions](https://github.com/threefoldtech/js-sdk/issues/668)
> renamed advanced solutions to Infrastructure solutions and add tooltip

- jumpscale/packages/marketplace/chats/threebot.py
- jumpscale/packages/marketplace/frontend/data.js
- jumpscale/packages/tfgrid_solutions/chats/threebot.py
- jumpscale/sals/reservation_chatflow/__init__.py
> simplified threebot

- jumpscale/packages/marketplace/chats/threebot.py
> fix marketplace backup url

- jumpscale/packages/tfgrid_solutions/chats/network.py
- jumpscale/sals/reservation_chatflow/deployer.py
- Fix pool capacity error message
- respect `OVER_PROVISIONING` in pool selection
- pass all metadata to network in add access instead of just owner
> respect over provisioning in pool selection & better error message

- jumpscale/packages/marketplace/chats/mattermost.py
- jumpscale/packages/marketplace/chats/publisher.py
- jumpscale/packages/marketplace/chats/ubuntu_simple.py
- jumpscale/packages/tfgrid_solutions/chats/cryptpad.py
- jumpscale/packages/tfgrid_solutions/chats/discourse.py
- jumpscale/packages/tfgrid_solutions/chats/exposed.py
- jumpscale/packages/tfgrid_solutions/chats/flist.py
- jumpscale/packages/tfgrid_solutions/chats/gitea.py
- jumpscale/packages/tfgrid_solutions/chats/gollum.py
- jumpscale/packages/tfgrid_solutions/chats/kubernetes.py
- jumpscale/packages/tfgrid_solutions/chats/mattermost.py
- jumpscale/packages/tfgrid_solutions/chats/minio.py
- jumpscale/packages/tfgrid_solutions/chats/monitoring.py
- jumpscale/packages/tfgrid_solutions/chats/network.py
- jumpscale/packages/tfgrid_solutions/chats/publisher.py
- jumpscale/packages/tfgrid_solutions/chats/taiga.py
- jumpscale/packages/tfgrid_solutions/chats/threebot.py
- jumpscale/packages/tfgrid_solutions/chats/ubuntu.py
- jumpscale/sals/marketplace/apps_chatflow.py
- jumpscale/sals/reservation_chatflow/deployer.py
Tolerate nodes that don't respond to network updates if they are not a target for container/vm deployment
https://github.com/threefoldtech/js-sdk/issues/638
> tolerate non responsive nodes on network updates

- jumpscale/packages/admin/frontend/components/solutions/Solutions.vue
- jumpscale/packages/admin/frontend/data.js
- jumpscale/packages/marketplace/chats/threebot.py
- jumpscale/packages/marketplace/frontend/App.vue
- jumpscale/packages/marketplace/frontend/components/Home.vue
- jumpscale/packages/marketplace/frontend/components/License.vue
- jumpscale/packages/marketplace/frontend/data.js
- jumpscale/packages/marketplace/frontend/index.html
address ui issues
https://github.com/threefoldtech/js-sdk/issues/688
https://github.com/threefoldtech/js-sdk/issues/677
https://github.com/threefoldtech/js-sdk/issues/680
https://github.com/threefoldtech/js-sdk/issues/689
> address ui issues

- jumpscale/packages/admin/frontend/data.js
- jumpscale/packages/tfgrid_solutions/chats/flist.py
fix success message in generic container and allow user to retry on flist url step
https://github.com/threefoldtech/js-sdk/issues/696
https://github.com/threefoldtech/js-sdk/issues/695
> generic container chatflow fixes

- jumpscale/packages/marketplace/chats/cryptpad.py
- jumpscale/packages/marketplace/chats/discourse.py
- jumpscale/packages/marketplace/chats/mattermost.py
- jumpscale/packages/marketplace/chats/peertube.py
- jumpscale/packages/marketplace/chats/publisher.py
- jumpscale/packages/marketplace/chats/taiga.py
- jumpscale/packages/marketplace/chats/threebot.py
- jumpscale/sals/marketplace/apps_chatflow.py
Update market place soultions apps to use HTTP check to make sure that the Domain is running
https://github.com/threefoldtech/js-sdk/issues/567
> UPdate market place apps to use http check

- jumpscale/packages/chatflows/frontend/mixins/field.js
- jumpscale/packages/marketplace/chats/exposed.py
- jumpscale/packages/marketplace/chats/ubuntu_simple.py
- jumpscale/packages/tfgrid_solutions/chats/exposed.py
- jumpscale/packages/tfgrid_solutions/chats/publisher.py
- jumpscale/sals/marketplace/apps_chatflow.py
- jumpscale/sals/reservation_chatflow/deployer.py
make solution names a valid identifiers 
https://github.com/threefoldtech/js-sdk/issues/675
> add is_identifier option to string field in chatflow

- jumpscale/sals/marketplace/solutions.py
- jumpscale/sals/reservation_chatflow/solutions.py
> fix listing cryptpad solutions

- jumpscale/packages/chatflows/frontend/style.css
Make the text color of tables white in dark mode.
> Lighten the tables text

- jumpscale/packages/marketplace/chats/taiga.py
- jumpscale/packages/tfgrid_solutions/chats/taiga.py
Fix taiga listing in admin solutions, the metadata wasn't updated in the subdomain container
- Add the metadata in the correctplace
- Remove duplicate from marketplace 
> fix taiga listing in admin solutions

- jumpscale/packages/tfgrid_solutions/scripts/threebot/entrypoint.py
Change default identity to testnet
- https://github.com/threefoldtech/js-sdk/issues/728
> change default identity on threebot solution

- jumpscale/packages/backup/actors/marketplace.py
- jumpscale/packages/marketplace/frontend/App.vue
- jumpscale/packages/marketplace/frontend/components/Home.vue
- jumpscale/packages/marketplace/frontend/components/solutions/Solution.vue
- jumpscale/packages/marketplace/frontend/data.js
- jumpscale/packages/marketplace/frontend/index.html
- jumpscale/packages/marketplace/package.toml
Remove primitives from marketplace chatflows and convert it to grid demo
- https://github.com/threefoldtech/js-sdk/issues/738
> remove primitve solutions from marketplace

- jumpscale/sals/chatflows/chatflows.py
tell user to restart the chatflow after error messages
https://github.com/threefoldtech/js-sdk/issues/723
> add refresh chatflow in error message

- jumpscale/packages/admin/frontend/data.js
- jumpscale/packages/tfgrid_solutions/chats/minio.py
rename minio solution to s3
https://github.com/threefoldtech/js-sdk/issues/721
> rename minio solution to s3

- jumpscale/packages/admin/frontend/data.js
remove 3bot solution from infra solutions
https://github.com/threefoldtech/js-sdk/issues/727
> remove 3bot solution from infra solutions

- jumpscale/packages/admin/frontend/components/solutions/Solutions.vue
rename infrastructor solutions into solutions
- https://github.com/threefoldtech/js-sdk/issues/726
> rename infrastructor solutions into solutions

- jumpscale/packages/admin/frontend/components/solutions/Solution.vue
- jumpscale/packages/admin/frontend/components/solutions/Solutions.vue
- jumpscale/packages/marketplace/frontend/components/Home.vue
- jumpscale/packages/marketplace/frontend/components/solutions/Solution.vue
- added info icon for demo apps
- added info icon for tfgrid_solutions
- [Add about solution to solutions card](https://github.com/threefoldtech/js-sdk/issues/731)
> Chatflow info ui

- jumpscale/packages/tfgrid_solutions/chats/exposed.py
Added checking in solutions listing in solution expose
https://github.com/threefoldtech/js-sdk/issues/729
> Added checking in solutions listing in solution expose

- jumpscale/packages/admin/actors/admin.py
- jumpscale/packages/admin/frontend/api.js
- jumpscale/packages/admin/frontend/components/settings/Settings.vue
Added developer options configuration from settign tab in UI
https://github.com/threefoldtech/js-sdk/issues/739
> Added developer options configuration from settign tab in UI

- jumpscale/packages/tfgrid_solutions/chats/exposed.py
- jumpscale/sals/marketplace/apps_chatflow.py
- jumpscale/sals/reservation_chatflow/deployer.py
- use all farms in app chatflows.
- show gateway location in domain delegation and solution expose
https://github.com/threefoldtech/js-sdk/issues/724
https://github.com/threefoldtech/js-sdk/issues/736
> chatflow improvements

- jumpscale/packages/admin/frontend/data.js
resolves: https://github.com/threefoldtech/js-sdk/issues/721
> improve s3 storage description

- jumpscale/packages/marketplace/frontend/data.js
> disable gitea solution in demo apps

- jumpscale/packages/admin/frontend/components/solutions/Solutions.vue
- jumpscale/packages/admin/frontend/data.js
> remove apps from admin dashboard

- jumpscale/packages/admin/frontend/components/dashboard/Solutions.vue
- jumpscale/packages/admin/frontend/components/solutions/Solution.vue
> fix removing apps from admin

- jumpscale/packages/admin/frontend/components/backup/marketplace/Backup.vue
> fix backup msgs

- jumpscale/packages/admin/frontend/components/base/Component.vue
- jumpscale/packages/admin/frontend/components/pools/Pools.vue
- jumpscale/packages/admin/frontend/components/workloads/Workloads.vue
- added spinner in the base component.
- [Add a spinner in the time of loading in workloads view and pools view](https://github.com/threefoldtech/js-sdk/issues/719)
> added spinner in base component

- jumpscale/packages/marketplace/chats/cryptpad.py
- jumpscale/sals/marketplace/apps_chatflow.py
use consistent domain names that include the solution type in the subdomain for app chatflows
List of changes this PR includ
https://github.com/threefoldtech/js-sdk/issues/735
> consistent domain names for apps

- jumpscale/entry_points/threebot.py
pass start args in restart command in threebot
> accept start arguments in threebot restart command issue #781

- jumpscale/packages/admin/frontend/index.js
reordering the items in the admin sidebar
- updated data.js file in admin package
#778 
> update admin sidebar order

- jumpscale/sals/marketplace/apps_chatflow.py
- Added user_wgconf_check
- [don't show wireguard configs at all or make it an optional screen in the end of the solution](https://github.com/threefoldtech/js-sdk/issues/768)
> Development user wgconf check

- jumpscale/packages/tfgrid_solutions/chats/exposed.py
- jumpscale/sals/zos/gateway.py
> Adds fix expose solution

- jumpscale/packages/marketplace/chats/cryptpad.py
- jumpscale/packages/marketplace/chats/mattermost.py
- jumpscale/packages/marketplace/chats/peertube.py
- jumpscale/sals/marketplace/apps_chatflow.py
- jumpscale/sals/marketplace/deployer.py
- jumpscale/sals/reservation_chatflow/deployer.py
update steps and messages in apps chatflows
https://github.com/threefoldtech/js-sdk/issues/788
> review apps chatflow

- jumpscale/packages/tfgrid_solutions/chats/flist.py
- jumpscale/packages/tfgrid_solutions/chats/kubernetes.py
- jumpscale/packages/tfgrid_solutions/chats/minio.py
- jumpscale/packages/tfgrid_solutions/chats/monitoring.py
- jumpscale/packages/tfgrid_solutions/chats/network.py
- jumpscale/packages/tfgrid_solutions/chats/publisher.py
- jumpscale/packages/tfgrid_solutions/chats/threebot.py
- jumpscale/packages/tfgrid_solutions/chats/ubuntu.py
- jumpscale/sals/reservation_chatflow/deployer.py
check for pools and networks early in chatflows
https://github.com/threefoldtech/js-sdk/issues/792
> solutions sanity checks

- jumpscale/sals/reservation_chatflow/solutions.py
Add farm information to the solutions details.
#636
1. I checked and in some cases the node contains location but the farm doesn't. This PR only adds the farm info (name and location).
2. It makes two api calls per node to fetch its farm which might slow down the listing in case there's a lot of solutions.
> Development farm name in solutions

- jumpscale/packages/tfgrid_solutions/chats/pools.py
ask for pool names at the beginning of the chatflow as mandatory field
pools chatflow in tfgrid_solutions
https://github.com/threefoldtech/js-sdk/issues/773
> ask for pool names at the beginning and make it mandatory

- jumpscale/sals/marketplace/apps_chatflow.py
> fix display name

- docs/wiki/threebot_deployer/threebot_deployer.md
> add threebot deployer docs

- jumpscale/sals/reservation_chatflow/deployer.py
- update billing details message
- https://github.com/threefoldtech/js-sdk/issues/795
> update billing details message

- jumpscale/packages/farmmanagement/frontend/services/farmmanagementServices.js
- jumpscale/packages/farmmanagement/frontend/store/farmmanagement.js
> fix farm management url

- jumpscale/packages/tfgrid_solutions/chats/pools.py
fix previous step in pools chatflow
https://github.com/threefoldtech/js-sdk/issues/851
> fix previous step in pools

- jumpscale/packages/marketplace/package.toml
- jumpscale/packages/threebot_deployer/package.toml
https://github.com/threefoldtech/js-sdk/pull/539#issuecomment-684082508
> fix threebot start local by removing packages defined default ports

- jumpscale/packages/marketplace/frontend/data.js
- update soluions description
- https://github.com/threefoldtech/js-sdk/issues/832
> update soluions description

- jumpscale/packages/marketplace/chats/gitea.py
- jumpscale/packages/tfgrid_solutions/chats/gitea.py
- jumpscale/packages/threebot_deployer/frontend/components/solutions/SolutionChatflow.vue
1. Fix finish redirection in threebot_deploy package.
2. Modify default gitea config to match the default in the container in tfgrid_solutions.
3. Bug fix in gitea before success message.
> fix finish redirection in threebot_deploy

- jumpscale/packages/threebot_deployer/chats/threebot.py
- jumpscale/sals/marketplace/apps_chatflow.py
- jumpscale/sals/marketplace/deployer.py
Fixes #815 and removes the branch used and force it to development
> remove version of 3bot and expiration phrasing

- jumpscale/packages/threebot_deployer/frontend/components/solutions/Workloads.vue
- jumpscale/sals/reservation_chatflow/solutions.py
- Add expiration time of pool for 3bot deployed in 3bot display table
- Add expiration to the list solutions of reservation chatflow sal
red color if expiration is in 2 days:
https://github.com/threefoldtech/js-sdk/issues/858
> Add pool expiration 3bots deployed from 3bot deployer package

- jumpscale/packages/threebot_deployer/chats/extend.py
- jumpscale/packages/threebot_deployer/frontend/components/solutions/Workloads.vue
- jumpscale/sals/marketplace/deployer.py
- added extended 3Bot chatflow
- added extend 3bot in frontend
- https://github.com/threefoldtech/js-sdk/issues/783
> Development 3bot deployer

- jumpscale/packages/admin/frontend/components/solutions/Solution.vue
showing solutions as a list
showing solutions as alist
https://github.com/threefoldtech/js-sdk/issues/789
> solutions list as table

- jumpscale/sals/marketplace/apps_chatflow.py
- jumpscale/sals/marketplace/deployer.py
reuse free pools in app chatflows
> reuse pools

- jumpscale/packages/tfgrid_solutions/chats/network.py
- jumpscale/sals/reservation_chatflow/solutions.py
- jumpscale/sals/zos/network.py
- fix network add access
- speed up network listing a bit
https://github.com/threefoldtech/js-sdk/issues/859
> fix network access & slow network loading

- jumpscale/packages/admin/frontend/components/solutions/SolutionChatflow.vue
- jumpscale/packages/tfgrid_solutions/chats/kubernetes.py
- jumpscale/packages/tfgrid_solutions/chats/minio.py
- jumpscale/packages/tfgrid_solutions/chats/monitoring.py
- jumpscale/packages/tfgrid_solutions/chats/pools.py
pass final_step in the last step of the chatflows.
#896
> Development final step button fix

- jumpscale/packages/admin/frontend/components/solutions/SolutionChatflow.vue
Pool was handled as a normal solution. It's now handled as a special case.
#884
> fix redirect pool chatflow

- jumpscale/packages/marketplace/bottle/solutions.py
- jumpscale/packages/threebot_deployer/bottle/solutions.py
- jumpscale/packages/threebot_deployer/chats/extend.py
- jumpscale/sals/marketplace/deployer.py
- jumpscale/sals/marketplace/solutions.py
- jumpscale/sals/reservation_chatflow/deployer.py
- deasscoiate user pool when the user deletes the associated app
- wait for pool extension
https://github.com/threefoldtech/js-sdk/issues/867
https://github.com/threefoldtech/js-sdk/issues/871
> wait for pool extension

- jumpscale/sals/reservation_chatflow/deployer.py
specify time to live for pool resources
pool extension and creation in reseveration_chatflow sal
https://github.com/threefoldtech/js-sdk/issues/860
> specify number of days in pool reservation

- jumpscale/sals/marketplace/apps_chatflow.py
change mattermost to solution type in initialization error message.
> fix hardcoded initialization message

- jumpscale/sals/marketplace/apps_chatflow.py
- jumpscale/sals/marketplace/deployer.py
fix attribute error and use int to extend pool
https://github.com/threefoldtech/js-sdk/issues/918
> fix underfit app pool extension

- jumpscale/packages/marketplace/chats/gitea.py
Remove ip and db password from gitea success page
#912
> Remove ip and db password

- poetry.lock
- pyproject.toml
> fix python version

- jumpscale/sals/reservation_chatflow/deployer.py
Fixed pool names in pools listing
Showed names at the end of the entry
https://github.com/threefoldtech/js-sdk/issues/911
> Fixed pool names in pools listing

- jumpscale/sals/marketplace/apps_chatflow.py
> fix missing attr

- jumpscale/packages/marketplace/chats/4to6gw.py
- jumpscale/packages/marketplace/chats/pools.py
- jumpscale/packages/marketplace/chats/ubuntu_simple.py
- jumpscale/packages/tfgrid_solutions/chats/4to6gw.py
- jumpscale/packages/tfgrid_solutions/chats/delegated_domain.py
- jumpscale/packages/tfgrid_solutions/chats/gollum.py
- jumpscale/packages/tfgrid_solutions/chats/network.py
Added rest of missing values of final_step=True in some chatflows.
#896
> Add missing final_step=True missing params

- jumpscale/packages/admin/actors/wallet.py
Delete wallet if imported with invalid secret
https://github.com/threefoldtech/js-sdk/issues/920
> Delete wallet if imported with invalid secret

- jumpscale/packages/threebot_deployer/chats/extend.py
Add comments to explain extending pool expiration time scenarios
Add comments in set expiration time of the extending of pool in threebot deployer
https://github.com/threefoldtech/js-sdk/issues/932
https://github.com/threefoldtech/js-sdk/pull/951#discussion_r482936835
> Add comments to explain extending pool expiration time scenarios

- jumpscale/packages/threebot_deployer/bottle/backup.py
- jumpscale/packages/threebot_deployer/frontend/api.js
- jumpscale/packages/threebot_deployer/frontend/components/base/Dialog.vue
- jumpscale/packages/threebot_deployer/frontend/components/solutions/Delete.vue
- jumpscale/packages/threebot_deployer/frontend/components/solutions/Workloads.vue
- jumpscale/packages/threebot_deployer/frontend/index.js
- jumpscale/packages/threebot_deployer/frontend/mixins/dialog.js
- jumpscale/packages/threebot_deployer/package.toml
- jumpscale/sals/reservation_chatflow/solutions.py
- Add destroy method
- Added delete backup check in delete confiramtion
- https://github.com/threefoldtech/js-sdk/issues/783
> 3Bot backup enhancments

- jumpscale/packages/tfgrid_solutions/chats/network.py
- jumpscale/sals/reservation_chatflow/deployer.py
- update network name message
-https://github.com/threefoldtech/js-sdk/issues/945
> update network name message

- jumpscale/sals/reservation_chatflow/deployer.py
remove qr_code from waiting for payment screen when payment is done with wallet
> remove qr code when payment is done with a wallet

- jumpscale/sals/marketplace/apps_chatflow.py
https://github.com/threefoldtech/js-sdk/issues/974
> fix extension currency

- jumpscale/sals/reservation_chatflow/deployer.py
Fix typo in asking workload name in reservation chatflow sal
you workload --> your workload
https://github.com/threefoldtech/js-sdk/issues/966
> Fix typo in asking workload name in reservation chatflow sal

- jumpscale/packages/admin/frontend/components/solutions/Solution.vue
- jumpscale/packages/marketplace/frontend/components/solutions/Solution.vue
- unify the listing of solutions and apps
- https://github.com/threefoldtech/js-sdk/issues/988
> unify the listing of solutions and apps

- jumpscale/packages/tfgrid_solutions/chats/network.py
Join  the wireguard please install message .. etc with the download file screen to be consistent with the other ones.
- https://github.com/threefoldtech/js-sdk/issues/949
> join wireguard screens in networkchatflow

- jumpscale/packages/marketplace/chats/peertube.py
> fix pool id in peertube

- jumpscale/packages/admin/frontend/data.js
Small edits in the solution descriptions shown in the admin dashboard
Edits done in the description shown in the frontend of the solutions in admin dashboard
> Update solution descriptions in admin dashboard

- jumpscale/packages/threebot_deployer/chats/threebot.py
- jumpscale/sals/marketplace/apps_chatflow.py
improve error message for threebot and non reachable urls
> improve error messages for threebot failure and non-reachable websites

- jumpscale/packages/marketplace/chats/cryptpad.py
- jumpscale/packages/marketplace/chats/discourse.py
- jumpscale/packages/marketplace/chats/gitea.py
- jumpscale/packages/marketplace/chats/mattermost.py
- jumpscale/packages/marketplace/chats/peertube.py
- jumpscale/packages/marketplace/chats/publisher.py
- jumpscale/packages/marketplace/chats/taiga.py
- jumpscale/packages/tfgrid_solutions/chats/exposed.py
- jumpscale/packages/tfgrid_solutions/chats/flist.py
- jumpscale/packages/tfgrid_solutions/chats/kubernetes.py
- jumpscale/packages/tfgrid_solutions/chats/minio.py
- jumpscale/packages/tfgrid_solutions/chats/monitoring.py
- jumpscale/packages/tfgrid_solutions/chats/network.py
- jumpscale/packages/tfgrid_solutions/chats/ubuntu.py
- jumpscale/packages/threebot_deployer/chats/threebot.py
- jumpscale/sals/marketplace/apps_chatflow.py
- jumpscale/sals/marketplace/deployer.py
- jumpscale/sals/reservation_chatflow/__init__.py
- jumpscale/sals/reservation_chatflow/deployer.py
- jumpscale/sals/reservation_chatflow/reservation_chatflow.py
- jumpscale/sals/zos/pools.py
block misbehaving nodes for sometime
https://github.com/threefoldtech/js-sdk/issues/761
> block failing nodes for sometime

- jumpscale/packages/backup/actors/threebot_deployer.py
- jumpscale/packages/threebot_deployer/actors/backup.py
- jumpscale/packages/threebot_deployer/bottle/backup.py
- jumpscale/packages/threebot_deployer/chats/threebot.py
- jumpscale/packages/threebot_deployer/models/backup_tokens.py
- jumpscale/packages/threebot_deployer/models/backup_tokens_sal.py
Add one time token to  create backup users for threebot
- https://github.com/threefoldtech/js-sdk/issues/1006
> add one time token for threebot to authorize the requests

- jumpscale/packages/tfgrid_solutions/chats/network.py
Typo in network chatflow in tfgrid solutions used in admin dashboard
fix typo 
https://github.com/threefoldtech/js-sdk/issues/966
> Fix typo in network chatflow

- jumpscale/packages/tfgrid_solutions/scripts/threebot/entrypoint.sh
- jumpscale/packages/threebot_deployer/chats/threebot.py
> Development backupfix

- jumpscale/packages/backup/actors/threebot_deployer.py
- jumpscale/packages/tfgrid_solutions/scripts/threebot/entrypoint.sh
- jumpscale/packages/threebot_deployer/actors/backup.py
- jumpscale/packages/threebot_deployer/bottle/backup.py
- jumpscale/packages/threebot_deployer/chats/threebot.py
- jumpscale/packages/threebot_deployer/models/backup_tokens.py
- jumpscale/packages/threebot_deployer/models/backup_tokens_sal.py
> Revert backupchanges

- jumpscale/packages/admin/actors/admin.py
Deleted identities on creation failure in add_identity actor
#1011
> Deleted identities on creation failure

- jumpscale/packages/admin/frontend/components/solutions/Solution.vue
- jumpscale/packages/tfgrid_solutions/chats/minio.py
- update minio success message and add loading flag
- https://github.com/threefoldtech/js-sdk/issues/1016
- https://github.com/threefoldtech/js-sdk/issues/898
> update minio success message and add loading flag

- jumpscale/packages/tfgrid_solutions/chats/exposed.py
fix custom domain in solution expose
https://github.com/threefoldtech/js-sdk/issues/1039
> fix custom domain

- jumpscale/packages/admin/frontend/components/backup/marketplace/Backup.vue
- jumpscale/packages/admin/frontend/components/backup/minio/Backup.vue
- jumpscale/packages/admin/frontend/components/base/Dialog.vue
- jumpscale/packages/admin/frontend/components/workloads/CancelWorkload.vue
- jumpscale/packages/admin/frontend/components/workloads/PatchCancel.vue
- jumpscale/packages/admin/frontend/mixins/dialog.js
Changed workload delete message in case of already  deleted workloads
> Changed workload delete message in case of already deleted workloads

- jumpscale/sals/marketplace/deployer.py
delete the newly created app network when it times out
> delete new user network when its workloads timeout

- jumpscale/packages/admin/frontend/components/backup/marketplace/Backup.vue
- jumpscale/packages/threebot_deployer/chats/extend.py
- jumpscale/packages/threebot_deployer/chats/threebot.py
updates for 3bot solution
- autobackup should be enabled
- less expiration time for 3bot (14 days)
- less resources {"cru": 1, "mru": 1, "sru": 2}
https://github.com/threefoldtech/js-sdk/issues/854
> Development 3botupdates

- jumpscale/packages/admin/bottle/admin.py
- jumpscale/packages/admin/bottle/models.py
- jumpscale/packages/admin/frontend/api.js
- jumpscale/packages/admin/frontend/components/legal/License.vue
- jumpscale/packages/admin/frontend/index.js
- jumpscale/packages/admin/package.toml
user should accept terms and conditions in order to access the admin panel
- https://github.com/threefoldtech/js-sdk/issues/1037
> Adds accept terms and conditions to 3bot

- jumpscale/sals/reservation_chatflow/deployer.py
block nodes in manual selection in chatflows
> block nodes in chatflow manual selection

- jumpscale/packages/admin/actors/admin.py
provide defaults for testcert and overprovisioning flags
> default options for test_cert and overprovisioning

- jumpscale/packages/marketplace/chats/cryptpad.py
- jumpscale/packages/marketplace/chats/discourse.py
- jumpscale/packages/marketplace/chats/gitea.py
- jumpscale/packages/marketplace/chats/mattermost.py
- jumpscale/packages/marketplace/chats/peertube.py
- jumpscale/packages/marketplace/chats/publisher.py
- jumpscale/packages/marketplace/chats/taiga.py
- jumpscale/packages/threebot_deployer/chats/threebot.py
- jumpscale/sals/marketplace/apps_chatflow.py
- jumpscale/sals/marketplace/deployer.py
> explain reuse in apps error messages

- jumpscale/packages/marketplace/frontend/components/solutions/Solution.vue
Add _blank as a target for the "Open.." button.
- Marketplace UI: Solutions component
#1028
> apps: open solution url in a new tab

- jumpscale/sals/marketplace/apps_chatflow.py
- Remove wireguard screen from apps/3bot
- https://github.com/threefoldtech/js-sdk/issues/1053
> remove wireguard screen

- jumpscale/packages/tfgrid_solutions/chats/exposed.py
- https://github.com/threefoldtech/js-sdk/issues/1041
> fix solution expose typo

- jumpscale/packages/admin/frontend/components/wikis/Wikis.vue
- jumpscale/packages/admin/frontend/data.js
- jumpscale/packages/admin/frontend/index.js
>  update links of wikis on 'wikis' section #1062

- jumpscale/packages/admin/frontend/components/alerts/Alerts.vue
- jumpscale/packages/admin/frontend/components/dashboard/Pools.vue
- jumpscale/packages/admin/frontend/components/dashboard/Processes.vue
- jumpscale/packages/admin/frontend/components/logs/Logs.vue
- jumpscale/packages/admin/frontend/components/pools/Pools.vue
- jumpscale/packages/admin/frontend/components/solutions/Solution.vue
- jumpscale/packages/admin/frontend/components/workloads/Workloads.vue
- jumpscale/packages/marketplace/frontend/components/solutions/Solution.vue
- jumpscale/packages/threebot_deployer/frontend/components/solutions/Workloads.vue
Changed no-data slot text in datatables
> Changed no-data slot text in datatables

- jumpscale/sals/reservation_chatflow/deployer.py
better handling of down nodes when waiting for workloads (mainly for network updates)
> update wait_workload to handle down nodes better

- jumpscale/entry_points/threebot.py
- fix stop order in threebot stop to avoid killing killed tmux windows
> fix threebot stop

- jumpscale/entry_points/threebot.py
Kill the process by hand if it was started in foreground (without --background).
#934 #999
> Send SIGTERM if the threebot wasn't started in background

- jumpscale/sals/marketplace/deployer.py
> fix marketplace network listing

- jumpscale/packages/marketplace/chats/publisher.py
- jumpscale/packages/marketplace/chats/wiki.py
> fix md messages in publishing tools

- jumpscale/packages/threebot_deployer/frontend/components/solutions/Info.vue
-fix canceled 3Bot from the details view
- https://github.com/threefoldtech/js-sdk/issues/1072
> fix canceled 3Bot from details view

- jumpscale/sals/reservation_chatflow/deployer.py
fix wait_pool_payment for tfgrid_solutions
> fix show_payment

- jumpscale/packages/backup/actors/marketplace.py
- jumpscale/packages/backup/actors/threebot_deployer.py
- jumpscale/packages/marketplace/package.toml
- jumpscale/packages/threebot_deployer/package.toml
> update domains for threebot deployer and apps

- jumpscale/packages/marketplace/chats/cryptpad.py
- jumpscale/packages/marketplace/chats/discourse.py
- jumpscale/packages/marketplace/chats/gitea.py
- jumpscale/packages/marketplace/chats/mattermost.py
- jumpscale/packages/marketplace/chats/peertube.py
- jumpscale/packages/marketplace/chats/publisher.py
- jumpscale/packages/marketplace/chats/taiga.py
- jumpscale/packages/threebot_deployer/chats/extend.py
- jumpscale/packages/threebot_deployer/chats/threebot.py
- jumpscale/sals/marketplace/apps_chatflow.py
- jumpscale/sals/reservation_chatflow/deployer.py
use TFT only for tfgrid_Solutions and demos. (threebot will be replaced in https://github.com/threefoldtech/js-sdk/pull/1086)
https://github.com/threefoldtech/js-sdk/issues/1083
> use TFT only

- jumpscale/packages/tfgrid_solutions/chats/network.py
Hotfix in network success md
#1090
> Hotfix in network success md

- jumpscale/packages/threebot_deployer/chats/threebot.py
- override creating pool in threebot chatflow
-  remove other currencies
- [update threebot deployer to use TFT and the user payment flow](https://github.com/threefoldtech/js-sdk/issues/1085)
> override creating pool in threebot chatflow and remove other currencies

- jumpscale/packages/tfgrid_solutions/chats/network.py
Remove duplicate last steps in network chatflow
https://github.com/threefoldtech/js-sdk/issues/1089
> Remove duplicate last steps in network chatflow

- .github/workflows/black-docstr.yml
Fix black formatting version used in github actions
> Fix black version

- jumpscale/sals/marketplace/apps_chatflow.py
- jumpscale/sals/marketplace/deployer.py
- jumpscale/sals/reservation_chatflow/deployer.py
move pool payment to apps chatflow class instead of sal
https://github.com/threefoldtech/js-sdk/issues/1100
> remove payment from marketplace sal

- jumpscale/packages/threebot_deployer/chats/threebot.py
- jumpscale/sals/marketplace/apps_chatflow.py
fix payment
https://github.com/threefoldtech/js-sdk/issues/1100
> fix show payment

- jumpscale/clients/stellar/__init__.py
- jumpscale/packages/admin/actors/wallet.py
- jumpscale/packages/admin/frontend/api.js
- jumpscale/packages/admin/frontend/components/wallets/CreateTestFunded.vue
- jumpscale/packages/admin/frontend/components/wallets/Wallets.vue
- jumpscale/packages/tfgrid_solutions/scripts/threebot/entrypoint.py
- Add method to create funded wallet
- Add it to the threebot entry point
- https://github.com/threefoldtech/js-sdk/issues/1102
> Add creating funded test wallet option to stellar client

- examplescripts/ubuntu.py
Script to deploy ubuntu and expose core x on a domain.
> Development end2end ubuntu expose

- jumpscale/entry_points/threebot.py
- deletes alerts
- asks for permission to remove jumpscale config
> wip for cleanup command

- jumpscale/servers/threebot/threebot.py
- Fix package deletion
https://github.com/threefoldtech/js-sdk/issues/1130
> fix package delete in threebot server

- jumpscale/servers/threebot/threebot.py
we do package install already in https://github.com/threefoldtech/js-sdk/blob/27cd38f0c481202509604052afeb4b1bd4115b8e/jumpscale/servers/threebot/threebot.py#L409 with kwargs
- https://github.com/threefoldtech/js-sdk/issues/1109
> fix packagemanager package registering actors

- jumpscale/packages/threebot_deployer/chats/threebot.py
- jumpscale/sals/chatflows/chatflows.py
- jumpscale/sals/marketplace/apps_chatflow.py
user_info()["username"] to be in a variable
> use a variable to save user_info

- jumpscale/packages/weblibs/package.py
- jumpscale/servers/threebot/threebot.py
> fix packages installation

- jumpscale/packages/tfgrid_solutions/chats/network.py
- jumpscale/sals/marketplace/apps_chatflow.py
- jumpscale/sals/marketplace/deployer.py
- jumpscale/sals/reservation_chatflow/deployer.py
check if pool.empty_at < now then the pool is expired and won't accept workloads
https://github.com/threefoldtech/js-sdk/issues/1128
> use empty_at in empty pools check

- jumpscale/packages/chatflows/frontend/components/Error.vue
- jumpscale/sals/reservation_chatflow/reservation_chatflow.py
Changed message on failing to deploy resources
#1091
> Changed message on failing to deploy resources

- jumpscale/packages/tfgrid_solutions/chats/4to6gw.py
https://github.com/threefoldtech/js-sdk/issues/1144
https://github.com/threefoldtech/js-sdk/issues/1145
https://github.com/threefoldtech/js-sdk/issues/1146
> fix steps and wg config in chatflow

- jumpscale/packages/tfgrid_solutions/chats/4to6gw.py
https://github.com/threefoldtech/js-sdk/issues/1146#issuecomment-692023079
> revert keys step

- jumpscale/packages/marketplace/chats/discourse.py
- jumpscale/packages/marketplace/chats/taiga.py
Unifies the messages between taiga and discourse 
#1147
> unify messages between discourse and taiga

- examplescripts/kubernetes.py
Adds script to deploy kubernets cluster
- https://github.com/threefoldtech/js-sdk/issues/1106
> Adds script to deploy k8s

- jumpscale/packages/marketplace/chats/discourse.py
> Add md arg in discourse message

- jumpscale/packages/admin/frontend/components/legal/License.vue
- jumpscale/packages/marketplace/frontend/components/License.vue
- jumpscale/packages/threebot_deployer/frontend/components/License.vue
Updated license message in threebot admin, demo, threebot deployer
#1161
> Updated license message

- examplescripts/kubernetes.py
> changing wallet name

- examplescripts/minio.py
> Development minio script

- jumpscale/packages/chatflows/frontend/components/DateTime.vue
- added default value to time picker
- https://github.com/threefoldtech/js-sdk/issues/961
> added default value to time picker

- docs/architecture/decisions/0007-payment-for-3bot-deployer.md
- add adr for Payment for 3bot deployer
> add threebot payment adr

- examplescripts/kubernetes.py
- jumpscale/sals/reservation_chatflow/deployer.py
add auto create wallet to kubernets script
https://github.com/threefoldtech/js-sdk/issues/1106
> Adds auto create wallet for kubernets

- jumpscale/packages/marketplace/package.toml
use marketplace.threefold.me and marketplace.threefold.io for marketplace (demo) package
https://github.com/threefoldtech/js-sdk/issues/1185
> update marketplace domain names

- jumpscale/packages/marketplace/package.toml
https://github.com/threefoldtech/js-sdk/issues/1185
> add location to me server

- examplescripts/kubernetes.py
> reverse nodes list when choosing nodes for kubernetes

- jumpscale/packages/tfgrid_solutions/chats/ubuntu.py
Update the ubuntu success message 
I have updated the success message in `tfgrid_solutions/chats/ubuntu.py`
https://github.com/threefoldtech/js-sdk/issues/959
> Update ubuntu success message

- jumpscale/packages/admin/frontend/components/backup/minio/Backup.vue
- jumpscale/packages/backup/actors/minio.py
- Hardens minio backup view in case of failure
- Deletes the created instance in case of failure
> harden minio on failure of initialization

- jumpscale/packages/tfgrid_solutions/chats/4to6gw.py
- jumpscale/packages/tfgrid_solutions/chats/delegated_domain.py
- jumpscale/sals/reservation_chatflow/deployer.py
https://github.com/threefoldtech/js-sdk/issues/1191
> show pool related error message in gateways

- examplescripts/minio.py
Network creation was a weak link in the script. It failed when a network was created on Mazr3a as they don't have access nodes.
1. Remove bad nodes (no longer bad).
2. Try network creation before reserving pools.
3. Pick the master node to be in freefarm.
#1107
> fix network issues

- jumpscale/clients/stellar/__init__.py
- jumpscale/packages/tfgrid_solutions/chats/pools.py
- jumpscale/sals/marketplace/apps_chatflow.py
- added check_stellar_service
- used check_stellar_service before starting the pools and apps chatflow
- https://github.com/threefoldtech/js-sdk/issues/1165
> Development stellar check

- jumpscale/packages/marketplace/package.py
- jumpscale/packages/threebot_deployer/chats/threebot.py
- jumpscale/packages/threebot_deployer/package.py
- jumpscale/sals/marketplace/apps_chatflow.py
- jumpscale/sals/marketplace/deployer.py
- 3Bot deployer to start with a funded wallet
- when the user wants to create an instance, we create a pool for this instance using the funded wallet for 15 mins (that should be enough for the initialization step).
- When we manage to deploy and initialize the 3Bot, we ask the user to extend the lifetime of the 3Bot in the same chatflow
- In case of pool extension failure they will be refunded from the explorer
- https://github.com/threefoldtech/js-sdk/issues/1167
> Development threebotdeployerwallet

- jumpscale/packages/admin/frontend/components/alerts/Alerts.vue
- jumpscale/packages/admin/frontend/index.js
- jumpscale/sals/chatflows/chatflows.py
When an error pops up in the chatflow. Redirect to the alert page and open its dialog.
Add a new alert component that accepts the alert id and does the required.
#1168
> Development directed alert

- jumpscale/sals/marketplace/apps_chatflow.py
The failure to fetch certificates info or absence or managed domains on the gateways reports the same error.
Add two messages for the two scenarios.
#1030
> Development certs http check

- jumpscale/packages/chatflows/frontend/components/DateTime.vue
- jumpscale/packages/threebot_deployer/chats/extend.py
- jumpscale/packages/threebot_deployer/chats/threebot.py
- jumpscale/sals/marketplace/apps_chatflow.py
- jumpscale/sals/marketplace/deployer.py
- jumpscale/sals/reservation_chatflow/deployer.py
- Fix wrong calculation for the expiration date in 3bot deployer
- Fix time in DateTime picker
- Fix threebot create/extend query
- Fix Pool extension equation
- Fix times from now to utc now
- Reuse the extension code
- https://github.com/threefoldtech/js-sdk/issues/1198
> threebot deployer extend enhancments and fixes

- jumpscale/servers/threebot/__init__.py
don't override domains if its configured already
> fix threebot start default

- jumpscale/packages/admin/frontend/components/base/Component.vue
- jumpscale/packages/admin/frontend/components/solutions/Solution.vue
align admin solutions to use menu button
> align admin solutions to use menu button

- jumpscale/clients/stellar/stellar.py
Fix method call in stellar client
https://github.com/threefoldfoundation/tft-stellar/issues/199
> Fix method call in stellar client

- jumpscale/packages/admin/frontend/components/solutions/Solution.vue
- show the workloads page and load inside to allow interaction while workloads loading complete
> fix solution loading

- jumpscale/packages/threebot_deployer/chats/threebot.py
Initial deploy of 3bot using deployer changed to 30 mins instead of 15 mins
https://github.com/threefoldtech/js-sdk/issues/1213
> Update deployed 3bot initial time to 30 mins instead of 15 mins

- jumpscale/packages/marketplace/chats/taiga.py
> fix taiga solution error method

- jumpscale/packages/marketplace/chats/taiga.py
> fix taiga solution deployment flow and query

- jumpscale/packages/chatflows/frontend/mixins/field.js
Update the validator to only accept lower case letters and numbers (using regex by @xmonader).
- Update fields.js in chatflows package.
#1212
> solutions: fix identifier validator

- jumpscale/core/identity/__init__.py
- Save explorer instance after upgrading the url
> save explorer instance after changing

- jumpscale/core/identity/__init__.py
save explorer instance after changing
> save explorer instance after changing (#1230)

- jumpscale/core/identity/__init__.py
- https://github.com/threefoldtech/js-sdk/issues/1234
> fix explorer endpoints

- jumpscale/servers/threebot/threebot.py
Fixing an issue related to adding  a not correct package
I have update the code to make the code to do installing the package and if it succeeded i will add the package to our packages if not I will raise exception
- jumpscale/servers/threebot/threebot.py
https://github.com/threefoldtech/js-sdk/issues/1246
> fix an issue related to adding wrong package

- jumpscale/packages/threebot_deployer/chats/threebot.py
- restore ssh (optional) for 3Bot deployment
> restore ssh (optional) for 3Bot deployment

- jumpscale/packages/marketplace/frontend/components/solutions/Info.vue
- fix expiration date formating
- https://github.com/threefoldtech/js-sdk/issues/1242
> fix expiration date formating

- jumpscale/clients/explorer/models.py
- jumpscale/sals/zos/container.py
Please only merge this after the tfexplorer change is merged
- Add new attribute `secret_stdout`
- Add new attribute `secret_stderr`
- Encrypt user intpu
- https://github.com/threefoldtech/zos/issues/945
> Encrypt logs url with node public key

- jumpscale/sals/marketplace/apps_chatflow.py
- jumpscale/sals/marketplace/deployer.py
add empty pool with gateways to be able to deploy apps with farms that don't have gateways
- https://github.com/threefoldtech/js-sdk/issues/1254
> add empty pool with gateways

- jumpscale/packages/farmmanagement/frontend/views/farmmanagement/farmmanagement.html
mark some fields optional in farm create form
mark some fields optional in farm create form
fixes #1066
> farm management: mark some fields optional in farm create form

- jumpscale/clients/explorer/explorer.py
- jumpscale/sals/marketplace/deployer.py
- jumpscale/sals/reservation_chatflow/deployer.py
fixes
- https://github.com/threefoldtech/js-sdk/issues/1254
> some fixes to gateways selection

- jumpscale/packages/marketplace/chats/cryptpad.py
- jumpscale/packages/marketplace/chats/discourse.py
- jumpscale/packages/marketplace/chats/gitea.py
- jumpscale/packages/marketplace/chats/mattermost.py
- jumpscale/packages/marketplace/chats/peertube.py
- jumpscale/packages/marketplace/chats/taiga.py
- https://github.com/threefoldtech/js-sdk/issues/1253
> fix subdomain solutions to deploy on farms without gateways

- jumpscale/packages/marketplace/chats/blog.py
- jumpscale/packages/marketplace/chats/publisher.py
- jumpscale/packages/marketplace/chats/website.py
- jumpscale/packages/marketplace/chats/wiki.py
clean publisher intro example msgs
- Add example blog, website too
> clean publisher intro example msgs

- jumpscale/packages/tfgrid_solutions/actors/solutions.py
- jumpscale/packages/tfgrid_solutions/chats/flist.py
- jumpscale/packages/tfgrid_solutions/chats/minio.py
- jumpscale/packages/tfgrid_solutions/chats/ubuntu.py
- jumpscale/sals/reservation_chatflow/deployer.py
- ipv6 step before node selection to be used in node query
- select ipv6 enabled nodes for zdb in minio
- speed up pools listing in admin dashboard
> use ip_version in solutions query for ipv6 and update pools listing

- jumpscale/sals/marketplace/apps_chatflow.py
> query nodes by public ipv6

- jumpscale/sals/marketplace/apps_chatflow.py
> handle invalid gws

- examplescripts/minio.py
There was a lag between workload deployment and namespace assignment. In this PR, the MinIO workload waits the zdb namespace to be assigned.
> Wait for namespaces to be deployed

- jumpscale/packages/threebot_deployer/chats/threebot.py
> add threebot deployer ipv6 nodes query

- jumpscale/sals/marketplace/apps_chatflow.py
- jumpscale/sals/marketplace/deployer.py
- jumpscale/sals/reservation_chatflow/deployer.py
https://github.com/threefoldtech/js-sdk/issues/1249
> Fix find pool capacity and no resources available in this pool

- docs/architecture/decisions/0008-add-kwargs-to-3bot-start.md
- jumpscale/servers/threebot/threebot.py
Save kwargs in package of 3bot server locally
Save kwargs in package of 3bot server locally
Needed for package used in this issue to pass kwargs during package add
https://github.com/threefoldfoundation/tft-stellar/issues/199
> Save kwargs in package of 3bot server locally

- jumpscale/sals/marketplace/apps_chatflow.py
- jumpscale/sals/marketplace/deployer.py
- jumpscale/sals/reservation_chatflow/deployer.py
check for ip version in farms to see if access nodes are availabe
> check for ip version in farm selection

- jumpscale/packages/marketplace/package.py
- jumpscale/packages/threebot_deployer/package.py
make threebot deploy and marketplace packages accept kwargs in start to align with new kwargs
> make threebot deploy and marketplace packages accept kwargs in start

- jumpscale/packages/tfgrid_solutions/chats/network.py
allow users to choose access node and pool id of access workloads
network chatflow in tfgrid_solutions
> optionally ask user for access node and pool

- jumpscale/clients/explorer/explorer.py
- jumpscale/packages/admin/actors/admin.py
- jumpscale/packages/admin/frontend/api.js
- jumpscale/packages/admin/frontend/components/settings/Settings.vue
- jumpscale/packages/threebot_deployer/chats/threebot.py
- jumpscale/sals/marketplace/apps_chatflow.py
- jumpscale/sals/reservation_chatflow/deployer.py
add option to disable explorer logs #1281
add wireguard screen to threebot deployer #1290
add more checks on selecting farms
> Development fixes

- jumpscale/packages/threebot_deployer/chats/threebot.py
- jumpscale/sals/marketplace/apps_chatflow.py
> block unreachable gateways and add ip to 3Bot final message

- jumpscale/packages/threebot_deployer/chats/threebot.py
> increase threebot deployment duration for slow deployments

- docs/wiki/tutorials/add_marketplace_chatflow.md
- jumpscale/packages/marketplace/frontend/components/Home.vue
- jumpscale/packages/marketplace/frontend/components/base/SolutionsSection.vue
- jumpscale/packages/marketplace/frontend/components/solutions/Solution.vue
- jumpscale/packages/marketplace/frontend/data.js
- Added solutions sections component
- Updated the structure of data.js
- Updated search bar UI
- Allow the option to deactivate the solution by hiding it in the UI 
- Updated docs for adding new marketplace application
[Provide an easy way to more categories / apps in the marketplace](https://github.com/threefoldtech/js-sdk/issues/1292)
> Added solutions sections component

- jumpscale/packages/tfgrid_solutions/scripts/threebot/entrypoint.py
https://github.com/threefoldtech/js-sdk/issues/1322
> make mainnet identity default

- jumpscale/clients/sendgrid/sendgrid.py
fixing an issue in sandgrid related to instantiation of objects
jumpscale/clients/sendgrid/sendgrid.py
https://github.com/threefoldtech/js-sdk/issues/1318
> fixing issue in the init of sandgrid

- .github/workflows/build_image.yml
- .github/workflows/build_tagged_image.yml
- jumpscale/install/Dockerfile
Build docker images and flist with pushing in development branch, and also with tags
> Development build images

- .github/workflows/js-sdk.yml
- tests/tools/restic/test_restic.py
> Add restic tests

- jumpscale/packages/tfgrid_solutions/scripts/threebot/entrypoint.py
- Check if old user but deleted backups, it can init backup again
- https://github.com/threefoldtech/js-sdk/issues/1301
> fix backup init for old users who deleted backups

- jumpscale/packages/backup/actors/threebot_deployer.py
allow backup for ~/sandbox/var/downloaded_packages and user developement space a for hosted 3bot
- https://github.com/threefoldtech/js-sdk/issues/1228
> add downloaded packages and user development space dir to backup

- jumpscale/sals/marketplace/apps_chatflow.py
should use the type specified in metadata not the cleaned up one for domains
> use the defined chatflow type not the cleaned one

- jumpscale/sals/zos/container.py
restore container logs until updating mainnet
> restore container logs until updating mainnet

- jumpscale/packages/admin/frontend/App.vue
- jumpscale/packages/admin/frontend/components/dashboard/HealthChecks.vue
- jumpscale/packages/admin/frontend/index.js
> Fix darkMode #902

- jumpscale/packages/tfgrid_solutions/chats/exposed.py
- jumpscale/packages/threebot_deployer/chats/threebot.py
- jumpscale/sals/marketplace/apps_chatflow.py
- jumpscale/sals/reservation_chatflow/deployer.py
Use zinit in the trc image. Tested with threebot deployer.
Tested on threebot and solution exposing.
> Use zinit in trc

- jumpscale/sals/reservation_chatflow/deployer.py
clean minio workloads when volumes fail to deploy and block respective nodes
> Development clean minio workloads

- jumpscale/packages/marketplace/bottle/solutions.py
- jumpscale/packages/marketplace/chats/cryptpad.py
- jumpscale/packages/marketplace/chats/discourse.py
- jumpscale/packages/marketplace/chats/gitea.py
- jumpscale/packages/marketplace/chats/mattermost.py
- jumpscale/packages/marketplace/chats/peertube.py
- jumpscale/packages/marketplace/chats/publisher.py
- jumpscale/packages/marketplace/chats/taiga.py
- jumpscale/packages/threebot_deployer/chats/threebot.py
- jumpscale/sals/marketplace/apps_chatflow.py
- jumpscale/sals/reservation_chatflow/__init__.py
- jumpscale/sals/reservation_chatflow/deployer.py
retry deployment on another node on failure in app chatflows
> Development retry deployment

- jumpscale/servers/threebot/threebot.py
add check by port to redis incase it's running with systemd
- fix misleading threebot status
> add check by port to redis incase it's running with systemd

- jumpscale/sals/marketplace/apps_chatflow.py
- jumpscale/sals/reservation_chatflow/deployer.py
- jumpscale/sals/reservation_chatflow/reservation_chatflow.py
block managed domains that fail to populate subdomains
app chatflows
> block managed domains that fail to populate

- examplescripts/ubuntu_server.py
Add Ubuntu server script to test gateway failover.
> Add Ubuntu server script to test gateway failover

- tests/clients/sendgrid/test_sendgrid.py
> Hot fix in tests

- jumpscale/packages/marketplace/chats/cryptpad.py
- update cryptpad image to make use of volumes
- update the deprecated docker image
- allow using backups if right env is passed
> update cryptpad image to make use of volumes

- jumpscale/sals/reservation_chatflow/deployer.py
make payment method required and retrurn if total amount is 0 in escrow
show payment in deployer
https://github.com/threefoldtech/js-sdk/issues/1366
> change payment method to required

- jumpscale/packages/threebot_deployer/chats/threebot.py
- jumpscale/sals/marketplace/apps_chatflow.py
- jumpscale/sals/marketplace/solutions.py
- jumpscale/sals/reservation_chatflow/solutions.py
- solutions_automation/deployer.py
- solutions_automation/threebot/deploy.py
- solutions_automation/utils/gedispatch.py
- solutions_automation/utils/utils.py
Custom domains for apps
- allow custom domains usage in apps_chatflow base
- enable custom domains in apps chatflow
> allow apps to use a custom domain and enable it in threebot chatflow

- jumpscale/packages/chatflows/frontend/components/UploadFile.vue
- updating uploadFile component in chatflow package
- https://github.com/threefoldtech/js-sdk/issues/825
> updating uploadFile component in chatflow package

- jumpscale/packages/marketplace/chats/cryptpad.py
- jumpscale/packages/marketplace/chats/discourse.py
- jumpscale/packages/marketplace/chats/gitea.py
- jumpscale/packages/marketplace/chats/mattermost.py
- jumpscale/packages/marketplace/chats/peertube.py
- jumpscale/packages/marketplace/chats/taiga.py
- fix query in all apps
- https://github.com/threefoldtech/js-sdk/issues/1202
> fix apps query

- docs/architecture/decisions/0012-use-poetry-lock-file-to-install-instead-of-poetry-update.md
add adr for using poetry lock instead of poetry update
> add adr for using poetry lock instead of poetry update

- docs/architecture/decisions/0010-update-3bot-deployer-image-to-use-ubuntu-20-04.md
Update 3bot deployer image to use ubuntu 20.04
> create adr for 3bot image update

- docs/architecture/decisions/0009-add-logs-in-trc-and-nginx-container.md
Add feature to stream logs from trc and nginx container for better debugging
> add adr for logs in nginx and trc containers

- docs/architecture/decisions/0013-update-cryptpad-flist.md
> add adr for cryptpad flist update

- docs/architecture/decisions/0014-managed-domain-verification-and-blocking-in-apps.md
ADR for verifying and blocking managed domains
> Development block managed domains adr

- docs/architecture/decisions/0011-nginx-expose-option.md
- jumpscale/packages/tfgrid_solutions/chats/exposed.py
- solutions_automation/dashboard_solutions/exposed.py
- solutions_automation/deployer.py
option to expose solutions in chatflow with nginx
> option to expose solutions with nginx in chatflow

- docs/architecture/decisions/0015-parameterize-zos-sal-in-identity.md
Parameterize zos sal in identity so if we want to switch identity at certain point we can for example to deploy workloads with that identity
> add adr for parametrizing zos sal

- jumpscale/clients/mail/mail.py
> fix mail client

- jumpscale/clients/mail/mail.py
- jumpscale/clients/s3/s3.py
- jumpscale/clients/syncthing/syncthing.py
- jumpscale/clients/taiga/taiga.py
- jumpscale/clients/zerotier/zerotier.py
Fix clients args and kwargs.
https://github.com/threefoldtech/js-sdk/issues/1310
> Fix clients kwargs

- jumpscale/packages/tfgrid_solutions/chats/exposed.py
Show the link with the appropriate protocol favoring https.
https://github.com/threefoldtech/js-sdk/issues/1346
> Check for exposed solution protocol

- jumpscale/sals/zos/container.py
- jumpscale/sals/zos/crypto.py
relates to https://github.com/threefoldtech/zos/pull/993
> change the way secret are encrypted into the it contract

- jumpscale/packages/admin/frontend/index.js
> change farm management icon

- jumpscale/sals/zos/container.py
- jumpscale/sals/zos/crypto.py
This reverts commit c8588e546e09f942934a45dad7a111286eb977db.
this is to unblock development
> Revert "change the way secret are encrypted into the it contract"

- jumpscale/packages/admin/frontend/components/packages/Add.vue
clearify package parameters when adding new package
- https://github.com/threefoldtech/js-sdk/issues/941
> Clearify package extra parameters when adding new package

- docs/wiki/tutorials/taiga_client.md
- jumpscale/clients/taiga/taiga.py
Adding more methods for Taiga to get and export data into markdown files
`jumpscale/clients/taiga/taiga.py`
https://github.com/threefoldtech/home/issues/773
> update taiga client with more methods to get and export data

- jumpscale/sals/chatflows/chatflows.py
Clear message in chat flow when not enough funds
https://github.com/threefoldtech/js-sdk/issues/1077
> Adds clear message when not enough funds

- Makefile
- conftest.py
- docs/tests/README.md
- docs/tests/clients/digitalocean/test_digitalocean.md
- docs/tests/clients/sendgrid/test_sendgrid.md
- docs/tests/core/identity/test_identity.md
- docs/tests/sals/zos/test_pools.md
- docs/tests/servers/threebot/test_threebot.md
- docs/tests/tools/nginx/test_nginx.md
- docs/tests/tools/redis/test_redis.md
- docs/tests/tools/restic/test_restic.md
- tests/README.md
- tests/base_tests.py
- tests/clients/digitalocean/test_digitalocean.py
- tests/clients/sendgrid/test_sendgrid.py
- tests/conftest.py
- tests/core/identity/test_identity.py
- tests/sals/zos/test_pools.py
- tests/servers/threebot/test_threebot.py
- tests/tools/nginx/test_nginx.py
- tests/tools/redis/test_redis.py
- tests/tools/restic/test_restic.py
- Fix docstring of the tests
- Add tests scenarios to repo's docs
#1316
> Add docs for tests scenarios

- jumpscale/sals/chatflows/chatflows.py
> fixes typo

- .github/workflows/js-sdk.yml
- docs/tests/README.md
- docs/tests/clients/github/test_github.md
- tests/clients/github/test_github.py
- tests/clients/github/test_githubclient.py
Create test coverage for Github
https://github.com/threefoldtech/js-sdk/issues/1265
> add github test

- CODEOWNERS
> Add Hanafy as code owner

- jumpscale/sals/marketplace/solutions.py
remove custom domain listing of threebot
> remove threebot custom domain listing

- jumpscale/packages/admin/frontend/components/solutions/Info.vue
- jumpscale/sals/reservation_chatflow/solutions.py
Add volume description in a `generic container` solution
https://github.com/threefoldtech/js-sdk/issues/1347
> Development flist volumes info main net

- jumpscale/packages/admin/frontend/index.js
> Update text color in dark mode

- jumpscale/packages/threebot_deployer/chats/threebot.py
- jumpscale/sals/marketplace/apps_chatflow.py
- jumpscale/sals/marketplace/deployer.py
Choose the location of the 3Bot
#1415
> Allow 3Bot user to choose the location to deploy on

- docs/wiki/tutorials/taiga_client.md
- jumpscale/clients/taiga/taiga.py
Add host to initialization in taiga docs.
> Add host to initialization in the docs

- jumpscale/entry_points/threebot.py
- jumpscale/packages/admin/bottle/admin.py
- jumpscale/packages/admin/frontend/App.vue
- jumpscale/packages/admin/frontend/api.js
- jumpscale/packages/tfgrid_solutions/scripts/threebot/entrypoint.py
Create a mainnet wallet on creation. And display a pop up with the information about the mainnet wallet and auto extension feature.
https://github.com/threefoldtech/js-sdk/issues/1414
> Development create wallet on creation

- jumpscale/packages/admin/frontend/components/workloads/PatchCancel.vue
- added deleted flag in patch cancel view and change the title
- https://github.com/threefoldtech/js-sdk/issues/1378
> added deleted flag in patch cancel view and change the title

- jumpscale/packages/admin/frontend/components/settings/Settings.vue
> Fix current identity color

- jumpscale/packages/admin/frontend/components/settings/AddIdentity.vue
- set mainnet as the default choice in adding a new identity.
- https://github.com/threefoldtech/js-sdk/issues/1453
> set mainnet as default choice in adding new identity

- jumpscale/sals/marketplace/apps_chatflow.py
- jumpscale/sals/marketplace/deployer.py
speed up farm and gateway selection in apps chatflow by using the first available object.
> select the first available farm and gateway

- jumpscale/packages/admin/actors/admin.py
- jumpscale/packages/admin/frontend/api.js
- jumpscale/packages/admin/frontend/components/settings/ConfigrationsInfo.vue
- jumpscale/packages/admin/frontend/components/settings/ConfigurationsInfo.vue
- jumpscale/packages/admin/frontend/components/settings/Settings.vue
- added show 3Bot config to the dashboard.
- https://github.com/threefoldtech/js-sdk/issues/743
> added show 3Bot config to the dashboard in dev options

- jumpscale/sals/reservation_chatflow/deployer.py
change the way for listing pools to use dropdown list instead of single choice
https://github.com/threefoldtech/js-sdk/issues/1463
> change the way for listing pools to use dropdown list instead of single choice

- jumpscale/packages/marketplace/chats/taiga.py
- jumpscale/packages/tfgrid_solutions/chats/cryptpad_advanced.py
- jumpscale/packages/tfgrid_solutions/chats/gitea_advanced.py
- jumpscale/packages/tfgrid_solutions/chats/taiga_advanced.py
- jumpscale/packages/tfgrid_solutions/scripts/threebot/entrypoint.py
- jumpscale/packages/tfgrid_solutions/scripts/threebot/entrypoint.sh
- jumpscale/packages/threebot_deployer/chats/threebot.py
- jumpscale/sals/marketplace/apps_chatflow.py
- jumpscale/sals/marketplace/deployer.py
- jumpscale/sals/marketplace/solutions.py
- jumpscale/sals/reservation_chatflow/solutions.py
- jumpscale/tools/restic/restic.py
- Creating a production infrastructure with backups
- https://github.com/threefoldtech/js-sdk/issues/1395
> Add solutions backup monitor and example cryptpad

- jumpscale/packages/threebot_deployer/chats/threebot.py
change the 3bot flist to the superfast one
- https://github.com/threefoldtech/js-sdk/issues/1465
> change the 3bot flist to the superfast one

- jumpscale/packages/auth/bottle/auth.py
fix access denied redirection to reidrect to / instead of none
- https://github.com/threefoldtech/js-sdk/issues/1446
> fix access denied redirection to reidrect to / instead of none

- docs/architecture/decisions/0016-update-threebot-deployer-flist.md
add adr for updating threebot deployer flist
> add adr for updating threebot deployer flist

- jumpscale/packages/threebot_deployer/bottle/backup.py
- jumpscale/packages/threebot_deployer/chats/threebot.py
- Check user against explorer
- Fix env variables
> fix 3bot solution backup and env variables

- jumpscale/packages/admin/actors/packages.py
- jumpscale/packages/admin/frontend/api.js
- jumpscale/packages/admin/frontend/components/packages/Add.vue
- jumpscale/packages/admin/frontend/components/packages/Chats.vue
- jumpscale/packages/admin/frontend/components/packages/Package.vue
- jumpscale/servers/threebot/threebot.py
Add chatflows listing and redirecting in packages of admin dashboard
- Add chatflows button in installed packages card that have chatflows that opens a popup with clickable chatflows names
- The check for the chatflows is added and passed in the package info in listing them
https://github.com/threefoldtech/js-sdk/issues/834
> Development listing chatflows

- jumpscale/packages/threebot_deployer/chats/threebot.py
- jumpscale/sals/chatflows/chatflows.py
change chatflow restart msg to include chat title
- https://github.com/threefoldtech/js-sdk/issues/1469
> Development chatflowmsg

- jumpscale/packages/tfgrid_solutions/chats/minio.py
The zdb size was fixed to the default of 10, when it should be taken from the user
Add option to take the zdb size of minio from the user
https://github.com/threefoldtech/js-sdk/issues/1221
> Add zdb size user input in minio chatflow of admin dashboard

- solutions_automation/deployer.py
- solutions_automation/threebot/deploy.py
add email settings to threebot gedis patch
> add email settings to threebot gedis patch

- tests/clients/github/test_github.py
Test coverage for Github
https://github.com/threefoldtech/js-sdk/issues/1314
> add wait for create repo

- docs/wiki/tutorials/taiga_client.md
- jumpscale/clients/taiga/models.py
- jumpscale/clients/taiga/taiga.py
wip for https://github.com/threefoldtech/circles_reporting_tool/blob/master/specs/
> circles tool

- jumpscale/packages/admin/actors/wallet.py
clean invalid wallet creation instances on failure in admin dashboard
- https://github.com/threefoldtech/js-sdk/issues/1512
> clean invalid wallet creation instances on failure in admin dashboard

- jumpscale/packages/admin/actors/admin.py
- jumpscale/packages/admin/frontend/api.js
- jumpscale/packages/admin/frontend/components/settings/Settings.vue
- jumpscale/sals/reservation_chatflow/deployer.py
- jumpscale/sals/reservation_chatflow/reservation_chatflow.py
option to sort nodes by free sru for nodes selection used in chatflows
https://github.com/threefoldtech/js-sdk/issues/1409
> option to sort nodes by sru for nodes selection

- jumpscale/packages/marketplace/frontend/App.vue
- jumpscale/packages/marketplace/frontend/components/License.vue
- Add popup for first time
- Update the tooltip to be persistent 
- Popup
- red banner
- https://github.com/threefoldtech/js-sdk/issues/1517
> add welcome popup and update the tooltip for marketplace

- jumpscale/servers/threebot/threebot.py
Add check for package services before stopping them in delete package
> Add check for services in delete package

- jumpscale/packages/admin/actors/admin.py
- jumpscale/packages/admin/frontend/api.js
- jumpscale/packages/admin/frontend/components/settings/IdentityInfo.vue
- jumpscale/packages/admin/frontend/components/settings/Settings.vue
> Development fix current identity

- jumpscale/packages/marketplace/chats/blog.py
- jumpscale/packages/marketplace/chats/website.py
- jumpscale/packages/marketplace/chats/wiki.py
- update repos links used in chatflows
- https://github.com/threefoldtech/js-sdk/issues/1523
> update repos links used in chatflows

- tests/servers/threebot/test_threebot.py
Fix for threebot packages tests to handle paths
> Fix for threebot packages tests to handle paths

- .github/workflows/frontend.yml
- tests/sals/automated_chatflows/chatflows_base.py
- tests/sals/automated_chatflows/test_marketplace_apps.py
- tests/sals/automated_chatflows/test_solutions.py
- tests/sals/automated_chatflows/test_threebot_deployer.py
- Add requests timeout to chatflows tests
- Install missing package in frontend workflow
> Add requests timeout to chatflows tests

- jumpscale/sals/reservation_chatflow/deployer.py
check for over provisioning flag when checking farm capacity
> respect over provisioning in farm capacity check

- jumpscale/sals/zos/network.py
- allow to load a network from any customer tid
- also fix a small typo in the code of load_network method
> zos sal: allow to load a network from any customer tid

- jumpscale/packages/admin/actors/admin.py
- jumpscale/packages/admin/frontend/api.js
- jumpscale/packages/admin/frontend/components/settings/AddSshkey.vue
- jumpscale/packages/admin/frontend/components/settings/Settings.vue
- jumpscale/packages/admin/frontend/components/settings/SshkeyInfo.vue
Added widget for configuring ssh keys from UI. Should be used later in chatflows to select sshkeys configured by user.
See https://github.com/threefoldtech/js-sdk/issues/1538
https://github.com/threefoldtech/js-sdk/issues/1294
> Added widget for configuring ssh keys from UI

- jumpscale/packages/admin/frontend/components/settings/EmailServerConfig.vue
- jumpscale/packages/admin/frontend/components/settings/Settings.vue
Update UI of email server config in admin dashboard settings
- Changed title to configurations
- removed property/ value
- add a tooltip to row items of the email server config table
https://github.com/threefoldtech/js-sdk/issues/1540
> Update email server config in admin dashboard vue to include tooltips

- jumpscale/packages/admin/actors/admin.py
- jumpscale/packages/admin/frontend/api.js
- jumpscale/packages/admin/frontend/components/settings/AddIdentity.vue
Separate the display name and the tname
https://github.com/threefoldtech/js-sdk/issues/1445
> Revert back to display name and tname

- jumpscale/sals/reservation_chatflow/deployer.py
> if no nodes added don't update the network

- jumpscale/packages/marketplace/frontend/data.js
Please update categories on Marketplace according to now2.threefold.io sidebar, so both marketplace and wiki are in-line.
-  Web & Social = Decentralised WE
- Collaboration Tools = Decentralised Office
- Developer Tools = Decentralised Developer
[TF NOW: Update categories on Marketplace](https://github.com/threefoldtech/js-sdk/issues/1564)
> Update categories on Marketplace

- jumpscale/packages/marketplace/frontend/data.js
-  Web & Social = Decentralized WE
- Collaboration Tools = Decentralized Office
- Developer Tools = Decentralized Developer
[TF NOW: Update categories on Marketplace](https://github.com/threefoldtech/js-sdk/issues/1564)
> renamed maketplace categories

- examplescripts/kubernetes.py
k8s script to reuse the management network properly
k8s example script
https://github.com/threefoldtech/js-sdk/issues/1578
> update k8s example script to use management network

- jumpscale/sals/reservation_chatflow/reservation_chatflow.py
show query params when there is not enough resources
https://github.com/threefoldtech/js-sdk/issues/1577
> Adds show query params when there is not enough resources

- jumpscale/packages/chatflows/frontend/App.vue
> chatflows: retry for 60 seconds if connectivity error

- examplescripts/ubuntu.py
Update ubuntu script to use `management` network with the correct IP, if we are not able to load the network then we create a new one.
examplescripts/ubuntu.py
https://github.com/threefoldtech/js-sdk/issues/1578
> Update ubuntu deploy script to use management network with the new ip

- jumpscale/packages/threebot_deployer/chats/threebot.py
- jumpscale/sals/marketplace/apps_chatflow.py
delete the identity in reservation method after retries
https://github.com/threefoldtech/js-sdk/issues/1601
> move identity context to the beginning of chatflow step

- jumpscale/packages/threebot_deployer/bottle/utils.py
> fix incorrect self

- jumpscale/packages/tfgrid_solutions/chats/exposed.py
- jumpscale/packages/threebot_deployer/bottle/utils.py
- jumpscale/packages/threebot_deployer/chats/threebot.py
- jumpscale/sals/marketplace/apps_chatflow.py
change redis channel names to include username
redis channel names to include username
https://github.com/threefoldtech/js-sdk/issues/1570
> Adds change redis channel name for solutions

- jumpscale/packages/marketplace/frontend/App.vue
- jumpscale/packages/marketplace/frontend/components/License.vue
> update marketplace info messages

- jumpscale/packages/threebot_deployer/bottle/utils.py
- jumpscale/packages/threebot_deployer/chats/change_location.py
- jumpscale/packages/threebot_deployer/chats/change_size.py
- jumpscale/packages/threebot_deployer/chats/restart_threebot.py
- tests/sals/automated_chatflows/test_threebot_deployer.py
update threebot deployer testcases
https://github.com/threefoldtech/js-sdk/issues/1543
> update threebot deployer tests

- examplescripts/ubuntu_server.py
https://github.com/threefoldtech/js-sdk/issues/1578
> update ubuntu_server examplescript to use management network

- jumpscale/packages/admin/frontend/components/solutions/Solution.vue
- jumpscale/packages/admin/frontend/components/solutions/Solutions.vue
- jumpscale/packages/marketplace/frontend/components/base/SolutionsSection.vue
- jumpscale/packages/marketplace/frontend/components/solutions/Solution.vue
> update tooltip link to use Wiki instead of manual

- jumpscale/packages/farmmanagement/actors/farm_management.py
- jumpscale/packages/farmmanagement/frontend/services/farmmanagementServices.js
- jumpscale/packages/farmmanagement/frontend/store/farmmanagement.js
Fixes https://github.com/threefoldtech/js-sdk/issues/1151 by using signed requests from gedis actor
> update listing farms to be with signed requests to retrieve farmer email

- jumpscale/packages/threebot_deployer/frontend/components/base/Table.vue
- jumpscale/packages/threebot_deployer/frontend/components/solutions/Delete.vue
Updated
[#1576](https://github.com/threefoldtech/js-sdk/issues/1576)
[#1575](https://github.com/threefoldtech/js-sdk/issues/1575)
> 3bot sort actions

- jumpscale/packages/threebot_deployer/chats/threebot.py
- jumpscale/sals/marketplace/deployer.py
show explicit messages about what actions has been taked
threebot chatflow
https://github.com/threefoldtech/js-sdk/issues/1416
> show detailed messages

- examplescripts/kubernetes.py
- examplescripts/minio.py
- examplescripts/ubuntu.py
- examplescripts/ubuntu_server.py
basic docs for example scripts
https://github.com/threefoldtech/js-sdk/issues/1589
> add docs for example scripts

- .github/workflows/build_image.yml
- .github/workflows/build_tagged_image.yml
Refresh the IYO token before using it
> Refresh the IYO token before using it

- jumpscale/packages/tfgrid_solutions/chats/minio.py
fixes https://github.com/threefoldtech/js-sdk/issues/1655
> add size unit for minio chatflow

- jumpscale/packages/threebot_deployer/bottle/solutions.py
- jumpscale/packages/threebot_deployer/bottle/utils.py
- jumpscale/packages/threebot_deployer/chats/change_location.py
- jumpscale/packages/threebot_deployer/chats/change_size.py
- jumpscale/packages/threebot_deployer/chats/restart_threebot.py
- jumpscale/packages/threebot_deployer/chats/threebot.py
- jumpscale/packages/threebot_deployer/models/user_solutions.py
> verify 3bot

- docs/api/jumpscale/sals/marketplace/apps_chatflow.html
- jumpscale/sals/marketplace/apps_chatflow.py
- solutions_automation/utils/gedispatch.py
> to use typo fixes 1668

- jumpscale/sals/reservation_chatflow/reservation_chatflow.py
> bool->pool typo

- docs/api/jumpscale/packages/auth/bottle/auth.html
- docs/api/jumpscale/packages/auth/index.html
- docs/api/jumpscale/packages/index.html
- docs/api/jumpscale/sals/reservation_chatflow/reservation_chatflow.html
- docs/api/jumpscale/threesdk/identitymanager.html
- docs/wiki/identity.md
- docs/wiki/marketplace/deployment.md
- docs/wiki/threebot_deployer/threebot_deployer.md
- jumpscale/packages/auth/__init__.py
- jumpscale/packages/auth/bottle/auth.py
- jumpscale/packages/auth/bottle/templates/login.html
- jumpscale/packages/threebot_deployer/models/user_solutions.py
- jumpscale/sals/reservation_chatflow/reservation_chatflow.py
- tests/frontend/tests/base_tests.py
> update 3bot connect -> Threefold Connect

- jumpscale/packages/admin/frontend/App.vue
…llet
Only a single wallet is created.
https://github.com/threefoldtech/js-sdk/issues/1663
> Modify the quick start message to reflect the creation of a single wallet 

- tests/sals/automated_chatflows/test_marketplace_apps.py
- tests/sals/automated_chatflows/test_pools.py
- tests/sals/automated_chatflows/test_solutions.py
- tests/sals/automated_chatflows/test_threebot_deployer.py
> Skip failing tests in automated chatflows 

- jumpscale/clients/explorer/models.py
> update usage tool

- jumpscale/packages/stellar_stats/README.md
- jumpscale/packages/stellar_stats/bottle/stellar_stats.py
Add total_tft and total_unlocked_tft endpoints for stellar_stats
- Fix threefoldfoundation/tft-stellar#206
> Add total_tft and total_unlocked_tft Endpoints

- jumpscale/packages/tfgrid_solutions/chats/gollum.py
- jumpscale/packages/tfgrid_solutions/chats/kubernetes.py
- jumpscale/packages/tfgrid_solutions/chats/minio.py
- jumpscale/packages/tfgrid_solutions/chats/monitoring.py
- jumpscale/packages/tfgrid_solutions/chats/ubuntu.py
properly strip uploaded ssh keys
> fix ssh key cleaning

- jumpscale/install/Dockerfile
- jumpscale/sals/reservation_chatflow/deployer.py
- fix threebot deployer docker file
- fix wg network locations
- https://github.com/threefoldtech/js-sdk/issues/1721
> fix wg locations and threebot deployer image build

- pyproject.toml
> bump version b13

- .typo-ci.yml
add .typo-ci.yml file to root of project to configure how Typo CI will behave 
https://github.com/threefoldtech/js-sdk/issues/1717
> add typo-ci file to ignore python files

- jumpscale/clients/stellar/stellar.py
> Fix sending locked tokens

- docs/wiki/tutorials/taiga_client.md
- jumpscale/clients/taiga/models.py
- jumpscale/clients/taiga/taiga.py
- jumpscale/clients/taiga/template.html
- Update models, get and validate custom fields in funnel circle as described in [funnel custom fields](https://github.com/threefoldtech/circles_reporting_tool/blob/master/specs/funnel.md#custom-fields).
- Check export work as expected.
- Create ArchiveCircle Model and exclude it from export.
- Fix export as YAML and include all the object attributes in the exported files.
- Create export every 5 min and add an option to update the modified objects only.
- Import from Yaml "Some Values will be replaced with default one".
- Enhance Cross linking in the wiki _"md_files"_.
- Wiki can be used with publishingtools.
- Update documentations.
- Update models with the latest specs.
- Create get_issue_custom_fields function.
- Create get_user_story_custom_fields functions.
- Create …
> circle_tool_v2 project

- jumpscale/packages/admin/actors/admin.py
- jumpscale/packages/admin/frontend/App.vue
- jumpscale/packages/admin/frontend/api.js
- [Add 3bot version info on the dashboard](https://github.com/threefoldtech/js-sdk/issues/1746)
> Show sdk version in admin dashboard

- jumpscale/packages/tfgrid_solutions/utils.py
> harden payment info in 3bot deployer

- jumpscale/packages/tfgrid_solutions/services/s3_auto_topup.py
alertraise receives `app_name` with underscore.
> use app_name instead of appname

- jumpscale/sals/vdc/threebot.py
The minimal_entrypoint fails with this error:
> cast to int before converting to str

- poetry.lock
- pyproject.toml
> update js-ng to 11.0b10 (#1770)

- jumpscale/packages/tfgrid_solutions/scripts/threebot/entrypoint.sh
- jumpscale/packages/tfgrid_solutions/scripts/threebot/initialize.sh
Update the init script with the new scheme.
> Development vdc move init out

- jumpscale/packages/tfgrid_solutions/scripts/threebot/entrypoint.sh
> Fix relative path in the entrypoint

- jumpscale/packages/auth/bottle/auth.py
- jumpscale/sals/nginx/nginx.py
- jumpscale/sals/nginx/templates/location.conf
- jumpscale/servers/threebot/threebot.py
https://github.com/threefoldtech/js-sdk/issues/1776
> package level authorization
