jumpscale/tools/nginx/nginxserver.py
- Fix nginx start and install
- Special cases
you can add cmd.ports, cmd.process_strings_regex or cmd.process_strings_regex to reach the process pid
for issue https://github.com/threefoldtech/js-ng/issues/341
updated docs: https://github.com/threefoldtech/js-ng/commit/b9975b784a5b26747996e469b19958c1f1525f88
=> fix nginx start by adding ports

jumpscale/tools/nginx/nginxserver.py
- Match process by name regex instead of port, cause in sometimes process couldn't be accessed with normal user after increasing its cap
=> fix nginx startupcmd

jumpscale/entry_points/threebot.py, jumpscale/packages/admin/package.toml, jumpscale/packages/admin_old/package.toml, jumpscale/packages/auth/package.toml, jumpscale/packages/chatflows/package.toml, jumpscale/packages/codeserver/package.toml, jumpscale/packages/farmmanagement/package.toml, jumpscale/packages/tfgrid_solutions/package.toml, jumpscale/packages/weblibs/package.toml, jumpscale/sals/nginx/nginx.py, jumpscale/servers/threebot/__init__.py, jumpscale/servers/threebot/threebot.py
ports
`threebstart start` now takes an extra optional paramater `--local` which will configure nginx to use ports in the 8xxx range
And extra check was added that when nginx can not bind to port 80 it
will raise error intrusction you to either use setcap or start threboot
with local flag
All `defaults` ports have been removed from the builtin packages
=> Make it possible to run threebot locally withouth requiring privileged

jumpscale/packages/admin/actors/admin.py, jumpscale/packages/admin/frontend/api.js, jumpscale/packages/admin/frontend/components/settings/AddIdentity.vue, jumpscale/packages/admin/frontend/components/settings/IdentityInfo.vue, jumpscale/packages/admin/frontend/components/settings/Settings.vue, jumpscale/packages/admin/frontend/components/wallets/Wallet.vue
Identities
- Add/register new identity from dashboard settings
- View identities in dashboard settings
- Delete identity from dashboard
- Change default identity used from dashboard (will be set in ` j.core.identity.me`)
Wallets
- Add update known trustline option for wallets from dashboard
=> Add identities updating  option in dashboard

jumpscale/packages/admin/frontend/components/base/Dialog.vue, jumpscale/packages/admin/frontend/components/workloads/CancelWorkload.vue, jumpscale/packages/admin/frontend/components/workloads/PatchCancel.vue, jumpscale/packages/admin/frontend/components/workloads/Workload.vue, jumpscale/packages/admin/frontend/components/workloads/Workloads.vue, jumpscale/packages/admin/frontend/mixins/dialog.js
Instead we now just update the required field on the workload object and
close the dialog window
=> avoid reloading the entire page when cancelling workloads

jumpscale/packages/admin/frontend/components/logs/Logs.vue
it makes it more explicit for user they can clock on the row to get a
detailed view of the log
fixes #381
=> use pointer cursor when hovering row of the table logs

jumpscale/packages/admin/frontend/components/pools/Pool.vue
1. Renaming `HIDE` button to `HIDE POOL`
2. Hide edit textbox after save the new pool name
https://github.com/threefoldtech/js-sdk/issues/533
https://github.com/threefoldtech/js-sdk/issues/534
=> fix edit pool name

jumpscale/clients/explorer/models.py, jumpscale/sals/zos/container.py, jumpscale/sals/zos/signature.py
Allow container workloads to have an yggdrasil network interface
Add extra argument into the container create method
https://github.com/threefoldtech/zos/issues/868
=> allow containers to have an yggdrasil interface

jumpscale/packages/admin/frontend/components/solutions/Solution.vue, jumpscale/packages/marketplace/frontend/components/solutions/Solution.vue
Showing workload info was not working in marketplace (small bug in code) 
- Fixed showInfo method in marketplace
- Unified dialogs info data in marketplace and admin solutions
https://github.com/threefoldtech/js-sdk/issues/652
=> Fixed showInfo method in marketplace worklaods

jumpscale/packages/tfgrid_solutions/chats/ubuntu.py
- remove ubuntu:19.10 from version choice
[Remove 19.10 release from ubuntu solution](#684)
=> remove ubuntu:19.10 from version choice

jumpscale/packages/tfgrid_solutions/chats/flist.py
Fixes https://github.com/threefoldtech/js-sdk/issues/776
Replaces the results link with http
Fixes https://github.com/threefoldtech/js-sdk/issues/776
=> remove https links from coreX it listens on http

jumpscale/sals/nginx/nginx.py, jumpscale/sals/nginx/templates/location.conf
Use the correct port with https redirection when starting local threebot.
Update the nginx configuration in nginx sal.
#249.
=> use the correct port with https redirection when starting local threebot

jumpscale/packages/admin/actors/identity.py
Adds explorer url to identity actor to be used from other things like farmmgmt
- typo in unknown in case of devnet
- returning explorer url tied to the running identity
=> add explorer url to identity actor

jumpscale/sals/chatflows/chatflows.py, jumpscale/sals/reservation_chatflow/deployer.py
log failed workloads
log failed workloads in wait_workload method in deployer.py
https://github.com/threefoldtech/js-sdk/issues/798
due to {} is empty because this is manually raised before the workload has a result
=> log failed workloads due to explorer errors

jumpscale/packages/admin/frontend/components/solutions/SolutionChatflow.vue, jumpscale/packages/chatflows/frontend/App.vue, jumpscale/packages/marketplace/frontend/components/solutions/SolutionChatflow.vue, jumpscale/packages/threebot_deployer/frontend/components/solutions/SolutionChatflow.vue
Instead of viewing chatflow has ended, redirect directly to the solution page.
The next button's text is changed to "Finish" at the final step.
#793
=> redirect to solutions page at the chatflow end

jumpscale/packages/admin/frontend/components/solutions/Solution.vue, jumpscale/packages/admin/frontend/components/solutions/Solutions.vue, jumpscale/packages/marketplace/frontend/components/Home.vue, jumpscale/packages/marketplace/frontend/components/solutions/Solution.vue
Renamed chatflow info tooltip to "Go to manual"
https://github.com/threefoldtech/js-sdk/issues/833
=> Renamed chatflow info tooltip

jumpscale/packages/threebot_deployer/frontend/components/solutions/Info.vue
Class added to the data object is removed from the dict to avoid being shown in the info card
before:
after:
-
=> Remove class from 3bot info json object in deployer UI

jumpscale/packages/admin/frontend/components/workloads/Workloads.vue
Change `epoch` to `Creation Date` in workload info view in admin dashboard
https://github.com/threefoldtech/js-sdk/issues/876
=> Change epoch to Creation date in workload info in admin dashboard

jumpscale/packages/admin/frontend/index.html
Forces headers to be aligned
I think it's caused by small screen
here's how it looks when i zoomed out 
and now on small screen
#924 
https://github.com/vuetifyjs/vuetify/issues/10164
=> whitespace nowrap for datatable headers

jumpscale/packages/admin/frontend/components/settings/Settings.vue
Fixed developer options in setting in admin panel
initialized the loading variable
https://github.com/threefoldtech/js-sdk/issues/921
=> Fixed developer options in setting in admin panel

jumpscale/packages/admin/frontend/components/settings/AddIdentity.vue
Change identity instance name to name in new identity of admin dahboard
`Identity instance name` field changed to `Identity name`
https://github.com/threefoldtech/js-sdk/issues/942
=> Change identity instance name to name in new identity of admin dahboard

jumpscale/packages/threebot_deployer/chats/extend.py, jumpscale/sals/marketplace/deployer.py
Change default and add min date and time for pool extension in threebot deployer to be current pool time left
- Add default 
- Add minimum validation check to disable a date before the current pool expiry time
When a pool has nothing consuming it, the empty_at is a max number, so if it its tht max number then the min and default are 1 hour from now. If not then they are the current pool empty_at value
https://github.com/threefoldtech/js-sdk/issues/932
=> Change default and add min date and time for pool extension 

jumpscale/sals/reservation_chatflow/deployer.py
Add spacing in deploying message of loading in reservation chatflow sal
Added spacing between deploying and the workload ID:
https://github.com/threefoldtech/js-sdk/issues/965
=> Add spacing in deploying message of loading in reservation chatflow sal

jumpscale/packages/marketplace/chats/cryptpad.py, jumpscale/packages/marketplace/chats/discourse.py, jumpscale/packages/marketplace/chats/gitea.py, jumpscale/packages/marketplace/chats/mattermost.py, jumpscale/packages/marketplace/chats/publisher.py, jumpscale/packages/marketplace/chats/taiga.py, jumpscale/packages/threebot_deployer/chats/threebot.py, jumpscale/sals/reservation_chatflow/__init__.py, jumpscale/sals/reservation_chatflow/solutions.py
use context to clean chatflow workloads in app chatflows to allow pool reuse
app chatflows in marketplace and threebot deployer
https://github.com/threefoldtech/js-sdk/issues/602
=> clean workloads in app chatflows using context

jumpscale/packages/tfgrid_solutions/chats/4to6gw.py, jumpscale/packages/tfgrid_solutions/chats/network.py
Fix the issue that a user has to click finish through multiple steps in network and 4to6 gateway chatflows for it to actually end.
1. Remove "click next" at the last step of network deployment.
2. Split the download and success message into two separate steps.
#978
=> split the last step to two in network and 4to6

jumpscale/packages/tfgrid_solutions/chats/network.py
Make IPv4 the default version in new network chatflow
Once directed to this step the default is already IPv4
https://github.com/threefoldtech/js-sdk/issues/946
=> Make IPv4 the default version in new network chatflow

jumpscale/packages/admin/frontend/components/solutions/SolutionChatflow.vue, jumpscale/packages/chatflows/frontend/App.vue, jumpscale/packages/marketplace/frontend/components/solutions/SolutionChatflow.vue, jumpscale/packages/threebot_deployer/frontend/components/solutions/SolutionChatflow.vue
The redirection should not be based on `this` object since after component rerendering the actual component object that is present in the DOM is different than the one created the event handler. So the event handler in the old code accesses the data of the old destroyed object. The solution name now is passed to the event listener in the message.
#971
=> resolve redirect state change issue

jumpscale/packages/threebot_deployer/chats/extend.py, jumpscale/sals/marketplace/deployer.py
When extending a 3Bot instance. The cus and sus required where calculated from the deployment old start date until the new expiration date. So the user will pay twice for the old period (he will get an over extended expiration date he didn't ask for).
Calculate the current curs and rus and pay only for the difference.
#936
=> extend to fit to the new expiration date

jumpscale/packages/admin/frontend/components/backup/marketplace/Backup.vue, jumpscale/packages/admin/frontend/components/backup/marketplace/InitRepos.vue, jumpscale/packages/admin/frontend/components/backup/minio/Backup.vue, jumpscale/packages/backup/actors/threebot_deployer.py, jumpscale/packages/tfgrid_solutions/scripts/threebot/entrypoint.sh, jumpscale/packages/threebot_deployer/actors/backup.py, jumpscale/packages/threebot_deployer/bottle/backup.py, jumpscale/packages/threebot_deployer/chats/threebot.py, jumpscale/packages/threebot_deployer/models/backup_tokens.py, jumpscale/packages/threebot_deployer/models/backup_tokens_sal.py
Updates for 3Bot solution backup
- add one time token for threebot to authorize the requests
- Enhance error message if anyone tried to backup locally which is not supported
```python
JS-NG> requests.post("https://waleed.threefold.io/threebot_deployer/actors/backup/init", json={"threebot_name":"waleedhammam.3bot", "passwd":"123456"}, headers={"Content-Type": "application/json"})         
2020-09-07 11:07:29.778 | INFO     | jumpscale.servers.gedis.server:_on_connection:269 - Executing method init from actor threebot_deployer_backup to client ('127.0.0.1', 37372)
127.0.0.1 - - [2020-09-07 11:07:29] "POST /threebot_deployer/backup/init HTTP/1.0" 403 230 0.095599
<Response [403]>
JS-NG> _.json() …
```
=> add one time token for threebot to authorize the requests

jumpscale/packages/farmmanagement/frontend/services/farmmanagementServices.js, jumpscale/packages/farmmanagement/frontend/store/farmmanagement.js, jumpscale/packages/farmmanagement/frontend/views/farmmanagement/farmmanagement.js
use the server's default identity in farm management instead of the logged in user
https://github.com/threefoldtech/js-sdk/issues/1043
=> use default identity instead of the logged in one

jumpscale/packages/threebot_deployer/chats/threebot.py
1. Step get a 3bot name to 3Bot name (as it can be and old one so he's not getting a new name).
2. Password messages.
3. Name scenarios:
- recover -> name deployed (The specified 3Bot name already exists. please choose another name.) 
- recover -> not deployed and doesn't exist (The specified 3Bot name doesn't exist.)
- recover -> not deployed and exists (correct scenario) 
- create -> name deployed (The specified 3Bot name already exists. please choose another name.)
- create -> not deployed but exists before (The specified 3Bot name was deployed before. Please go to the previous step and choose recover or enter a new name.)
- create -> not deployed and wasn't deployed before (correct scenario)
#1065
=> More clear password and recovery messages

jumpscale/packages/admin/actors/admin.py, jumpscale/packages/admin/frontend/components/settings/IdentityInfo.vue
- Enable showing the words of the identities in the admin dashboard
- https://github.com/threefoldtech/js-sdk/issues/1099
=> Enable showing the words of the identities in the admin dashboard

jumpscale/packages/tfgrid_solutions/actors/solutions.py, jumpscale/sals/reservation_chatflow/deployer.py
exclude the workloads deployed on deleted nodes when building the network view.
replace farm_id remaining in node selection with pool_id
=> exclude workloads on deleted nodes when building a network view

jumpscale/packages/admin/frontend/components/pools/Pools.vue, jumpscale/packages/admin/frontend/components/workloads/Workloads.vue
- changed the loading to be on the table not on base-component
- reverse workloads ans pools table to show newest first
- https://github.com/threefoldtech/js-sdk/issues/1133
=> changed the loading to be on the table not on base-component

jumpscale/clients/explorer/auth.py, jumpscale/clients/explorer/conversion.py, jumpscale/clients/explorer/farms.py
The client was not sending the date used to generated the signature of
the request to the server. This lead to the server using its own local
time to verify the signature which can lead to errors if both client and
server are not perfectly synchronized and/or the network is slow
Send the date used to generate the request signature to the server
fixes #1123
=> Fix authentication error to the explorer API

jumpscale/servers/threebot/threebot.py
Reload gedis http internal client when installing package.
- Update `PackcakgeManager.install` to reload gedis http internal client.
#1109.
=> gedis http: reload internal client when installing a package

docs/wiki/threebot_deployer/threebot_deployer.md, jumpscale/install/Dockerfile, jumpscale/install/rootfs/etc/zinit/init.yaml, jumpscale/install/rootfs/etc/zinit/start.yaml, jumpscale/packages/tfgrid_solutions/scripts/threebot/entrypoint.py, jumpscale/packages/threebot_deployer/chats/threebot.py, jumpscale/packages/threebot_deployer/package.py
- Use Zinit to start 3Bot flist
- Use Zinit to start 3Bot flist
- Clean threebot entrypoint
- Add option/docs to stream logs to remote redis
- https://github.com/threefoldtech/js-sdk/issues/1174
=> Development 3bot zinit

jumpscale/packages/marketplace/chats/blog.py, jumpscale/packages/marketplace/chats/discourse.py, jumpscale/packages/marketplace/chats/mattermost.py, jumpscale/packages/marketplace/chats/peertube.py, jumpscale/packages/marketplace/chats/publisher.py, jumpscale/packages/marketplace/chats/taiga.py, jumpscale/packages/marketplace/chats/website.py, jumpscale/packages/marketplace/chats/wiki.py
The chatflow listens for payloads from the backend and depending on their type, it disables or enables the next button. The issue is that calling self.user_info is a method that sends a payload to the chatflow with a type for which the next button is enabled. If the user clicks on the next again, it registers two transitions and that causes the step to come to be skipped. I moved it to the beginning of the step so that the next button don't get re-enabled.
#1171
=> fetch user info at the beginning

jumpscale/servers/threebot/threebot.py
Return a copy when listing packages.
- PackageManager.list_all()
#1097
=> return a copy of threebot package keys in list_all()

jumpscale/packages/marketplace/frontend/App.vue
-added demo label in the marketplace app bar
- [disclaimer banner on marketplace.threefold.me/demo/...](https://github.com/threefoldtech/js-sdk/issues/1177)
=> added demo label in marketplace app bar

jumpscale/core/identity/__init__.py, jumpscale/packages/tfgrid_solutions/scripts/threebot/entrypoint.py
- auto upgrade mainnet
- save explorers in js-configs to reuse later
- After migration is complete we will trigger this update by setting new config `has_migrated=True`
- https://github.com/threefoldtech/js-sdk/issues/1071
=> add upgrade mainnet identity

poetry.lock, pyproject.toml
Force this version until the broken ABI is fixed in newer versions.
- Updated `pyproject.toml` and `poetry.lock`
https://github.com/threefoldtech/js-ng/issues/458
=> force greenlet version to 0.4.16

jumpscale/core/identity/__init__.py
instead of creating identity and then  go to `j.core.identity.set_default("newme")` we can `identityobj.set_default()`
=> add set_default on identity object

jumpscale/sals/reservation_chatflow/deployer.py
ip version is not mandatory but required for node filter
- https://github.com/threefoldtech/js-sdk/issues/1302
=> check for using ip before using node filter

jumpscale/install/Dockerfile
- instead of the deprecated 19.10
- fixes poetry issues
=> use base image 20.04 in 3bot image

jumpscale/packages/admin/frontend/components/workloads/Workloads.vue
Apparently, adding page.sync attribute makes the data table return to a page with entries after filtering. But it's mainly an issue in Vuetify https://github.com/vuetifyjs/vuetify/issues/10949.
https://github.com/threefoldtech/js-sdk/issues/835
=> Workaround to make the datatable go to page with entries after filtering

jumpscale/tools/nginx/nginxserver.py
StoredFactory  uses the property `name` in a special way. So it can't be added as a field. It's renamed to server_name in this PR.
=> rename name to server_name to make it usable

jumpscale/packages/admin/frontend/App.vue, jumpscale/packages/admin/frontend/components/alerts/Alerts.vue, jumpscale/packages/admin/frontend/components/backup/marketplace/Backup.vue, jumpscale/packages/admin/frontend/components/backup/minio/Backup.vue, jumpscale/packages/admin/frontend/components/dashboard/Pools.vue, jumpscale/packages/admin/frontend/components/logs/Logs.vue, jumpscale/packages/admin/frontend/components/pools/Pools.vue, jumpscale/packages/admin/frontend/components/workloads/Workloads.vue, jumpscale/packages/chatflows/frontend/components/DateTime.vue, jumpscale/packages/marketplace/frontend/components/solutions/Info.vue, jumpscale/packages/marketplace/frontend/components/solutions/Solution.vue, jumpscale/packages/threebot_deployer/frontend/components/solutions/Workloads.vue
- formatting all date in the dashboard
- [UX/Workloads page: date is formated as mm/dd/yyyy](https://github.com/threefoldtech/js-sdk/issues/838)
=> formatting all date in the dashboard

jumpscale/sals/marketplace/deployer.py, jumpscale/sals/marketplace/models.py
The gateway pool is identified only by the farm name. This causes issues when switching identities, since the pool owner changes and the gateways available on mainnet are different from testnet. In this PR, a check is added for the owner and a new pool is created in case of mismatch.
=> check if the owner is the same as the pool owner

jumpscale/sals/zos/container.py, jumpscale/sals/zos/crypto.py, jumpscale/sals/zos/gateway.py, jumpscale/sals/zos/kubernetes.py, jumpscale/sals/zos/zdb.py, jumpscale/sals/zos/zos.py
Extract from https://en.wikipedia.org/wiki/Elliptic-curve_Diffie%E2%80%93Hellman#Key_establishment_protocol:
> While the shared secret may be used directly as a key, it can be desirable to hash the secret to remove weak bits due to the Diffie–Hellman exchange.
DO NOT MERGE YET.
=> do hash the shared secret generated to decrypt workloads sensitive in formation

jumpscale/sals/marketplace/apps_chatflow.py
fix managed domain selection. should be shuffled to avoid hitting letsencrypt rate limit fast and to have varity of domains
=> shuffle managed domains as well

jumpscale/packages/admin/actors/admin.py, jumpscale/packages/admin/frontend/api.js, jumpscale/packages/admin/frontend/components/settings/AddEscalationEmail.vue, jumpscale/packages/admin/frontend/components/settings/Settings.vue
- Update the front-end and back-end for escalating emails.
- Add toggle bottom to enable escalating emails.
jumpscale/packages/admin/actors/admin.py
jumpscale/packages/admin/frontend/api.js
jumpscale/packages/admin/frontend/components/settings/AddEscalationEmail.vue
jumpscale/packages/admin/frontend/components/settings/Settings.vue
https://github.com/threefoldtech/js-sdk/issues/1413
=> Development 3botdeployer escalation emails

jumpscale/sals/reservation_chatflow/deployer.py
When paying for pool, wallets with not enough balance appear in the options and so fail if chosen
Check for wallet balance against the amount to be payed for the pool and filter out wallets with enough balance
- no wallets with enough balance:
- wallet with enough balance added:
https://github.com/threefoldtech/js-sdk/issues/1018
=> Show wallets with enough balance when paying for pools

jumpscale/sals/reservation_chatflow/deployer.py
Fix balance comparison type in showing  wallets with enough balance when paying for pools
change type of balance in check to float instead of strings
https://github.com/threefoldtech/js-sdk/issues/1018
=> Fix balance comparison type

poetry.lock, pyproject.toml
Update js-ng to v11.0b7, which contains some needed features and fixes.
* `pyproject.toml`
* `poetry.lock`
Needs `poetry install` locally.
=> update js-ng to v11.0b7

docs/wiki/threebot/threebot.md, jumpscale/servers/threebot/threebot.py
gedis server now supports reloading actors in the new js-ng version.
* Pass `force_reload=True` when registering package actors.
#888
=> force reloading actors when adding a package

jumpscale/core/identity/__init__.py, jumpscale/packages/admin/actors/admin.py, jumpscale/packages/admin/frontend/api.js, jumpscale/packages/admin/frontend/components/settings/AddIdentity.vue
Replace instance name and tname with display_name 
1. Create identity with instance name "{display_name}_{network used}" to allow registering the same tname on testnet and mainnet.
2. Tooltip with message "The name to be registered on TFGrid, used to reference your created 3Bot identity.". 
https://github.com/threefoldtech/js-sdk/issues/1445
=> use display name only

jumpscale/entry_points/threebot.py, jumpscale/packages/admin/actors/wallet.py
The mainnet wallet network was being determined by the default identity, which incorrectly assumed that is always a mainnet identity. Now it should be independent.
=> Separate mainnet wallet from identity

jumpscale/packages/admin/actors/admin.py, jumpscale/packages/admin/frontend/api.js, jumpscale/packages/admin/frontend/components/base/Dialog.vue, jumpscale/packages/admin/frontend/components/settings/AddIdentity.vue
1.  Added button to create mnemonics
2. More checks in adding a new identity before submit:
- added instance name duplicated check
- added tname check in the explorer
- disable submit button until all fields pass checks
- [Add button to generate mnemonics in Add Identity view](https://github.com/threefoldtech/js-sdk/issues/1243)
=> Add button to create mnemonics

jumpscale/entry_points/threebot.py
- Create test wallet for testnet and std wallet for mainnet
- https://github.com/threefoldtech/js-sdk/issues/1572
=> add wallet according to the source of deployment in 3bot deployer

jumpscale/packages/marketplace/chats/taiga.py
Remove secret key from user inputs in taiga deployment  chatflow and generate it
generate the secret key of 15 randomly generated characters
Remove secret key from user inputs in taiga deployment  chatflow and generate it
=> remove secret key from taiga inputs and generate it

jumpscale/packages/codeserver/codeserver-install.sh
Use curl instead of wget. for some reason wget doesn't work.
https://github.com/threefoldtech/js-sdk/issues/1599
=> use curl instead of wget

jumpscale/packages/tfgrid_solutions/scripts/threebot/entrypoint.sh
Flists doesn't contain the hosts so it have to be added so that the well known hosts becode resolvable.
=> add hostname so gevent can resolve it

jumpscale/packages/admin/frontend/App.vue
Removes email of the subidentity showing up on the topleft for #1616
=> remove email from the sidebar topleft

jumpscale/packages/chatflows/frontend/components/DateTime.vue, jumpscale/sals/marketplace/deployer.py
- Added min date option to the DateTime picker (previous dates disabled)
- Set a minimum of DateTime picker in the marketplace to be one day.
- https://github.com/threefoldtech/js-sdk/issues/1581
=> Added min date option to the datetime picker component

jumpscale/sals/reservation_chatflow/deployer.py
retry deployment when network dry run fails
raise DeploymentFailed on dry run failure instead of StopChatflow
https://github.com/threefoldtech/js-sdk/issues/1642
=> retry deploymemts on dry run failures

jumpscale/clients/explorer/models.py, jumpscale/tools/zos/consumption/__init__.py, jumpscale/tools/zos/consumption/readme.md, jumpscale/tools/zos/consumption/usage.py, tests/clients/explorer/test_models.py
Add a new `consumption` section in `j.tools.zos` which allow to compute how much cloud units are consumed by a workload object
- Add new module in j.tools.zos
- Add `resource_units` methods on all the workloads model
fixes #1423
=> add new tools to compute how much cloud units is used by a workload

jumpscale/packages/admin/actors/wallet.py
When creating or updating a wallet, only TFT trustline is added.
https://github.com/threefoldtech/js-sdk/issues/1664
=> use tft only in wallets

jumpscale/sals/chatflows/chatflows.py, poetry.lock, pyproject.toml
Traceback not added in alerts raised from chatflows
- Get traceback of last exception and add it to the raised alert
- Update dependency version of js-ng to 11.0-b8
Example with adding bug in a chatflow to trigger an error
Based on changes in PR: https://github.com/threefoldtech/js-ng/pull/503
https://github.com/threefoldtech/js-sdk/issues/1639
=> Add traceback in raised alerts of chatflows

jumpscale/packages/threebot_deployer/bottle/solutions.py, jumpscale/packages/threebot_deployer/frontend/components/base/Dialog.vue, jumpscale/packages/threebot_deployer/frontend/components/solutions/ActionConfirmation.vue, jumpscale/packages/threebot_deployer/frontend/components/solutions/Delete.vue, jumpscale/packages/threebot_deployer/frontend/components/solutions/Stop.vue
- Added new action confirmation component
- Use `Enter` key to submitted action.
- use the base action component in stop and delete actions
- Added persistent option to the base dialog
- handle permission exception in stop and destroy threebot
[3Bot Deployer on testnet: can not destroy 3Bot](https://github.com/threefoldtech/js-sdk/issues/1659)
=> 3Bot deployer action dialogs hardening

jumpscale/packages/marketplace/chats/gitea.py, jumpscale/packages/marketplace/chats/mattermost.py, jumpscale/packages/marketplace/chats/meetings.py, jumpscale/packages/marketplace/chats/publisher.py, jumpscale/packages/marketplace/chats/taiga.py, jumpscale/packages/threebot_deployer/chats/threebot.py, jumpscale/sals/marketplace/apps_chatflow.py
only ipv4 is required
Change farm selection to choose farms with ipv4
- Remove public_ipv6 from container deployment in apps and threebot
- Change threebot deployer farm selector to include all farms
```
jumpscale/packages/marketplace/chats/gitea.py          |  1 -
jumpscale/packages/marketplace/chats/mattermost.py     |  1 -
jumpscale/packages/marketplace/chats/meetings.py       |  1 -
jumpscale/packages/marketplace/chats/publisher.py      |  1 -
jumpscale/packages/marketplace/chats/taiga.py          |  1 -
jumpscale/packages/threebot_deployer/chats/threebot.py |  3 +--
jumpscale/sals/marketplace/apps_chatflow.py            | 10 +++-------
7 files changed, 4 insertions(+), 14 deletions(-)
```
=> remove ipv6 check for farms selection

jumpscale/sals/marketplace/apps_chatflow.py
don't check certificate limit if test_cert is enabled
https://github.com/threefoldtech/js-sdk/issues/1672
=> check test cert before certificate limit

poetry.lock, pyproject.toml
Update js-ng version to 11.0b10 which contains custom alert handlers support.
pyproject.toml and poetry.lock
=> update js-ng to 11.0b10

jumpscale/packages/tfgrid_solutions/scripts/threebot/minimal_entrypoint.py, jumpscale/servers/threebot/threebot.py
zinit starts executes the entrypoint then starts the 3bot server as a different service. So the registered handler doesn't apply to the new process.
Should be merged after poetry dependency is updated with the register_handler commit (currently, it fails).
=> Move alert handler from the entrypoint to server start

jumpscale/packages/tfgrid_solutions/scripts/threebot/entrypoint.sh, jumpscale/packages/tfgrid_solutions/scripts/threebot/initialize.sh
Putting `SDK_VERSiON=development_vdc` to the development image doesn't execute the development_vdc code since it had begun already executing entrypoint script. So in this PR, the logic is moved to a new file, and a couple of checks is added to make sure all the current branches will work without any changes.
=> move init logic out of the entrypoint

jumpscale/packages/tfgrid_solutions/scripts/threebot/entrypoint.sh
When specifying a branch that is added after the development image build, the `poetry.lock` check fails with this error.
=> fetch remote branches before diffing poetry.lock

jumpscale/packages/vdc_dashboard/frontend/components/base/Kubernetes.vue
The list of nodes in kubernetes shows the private ip of the node in the network when it should be the public ip that is accessible
Replace private ip to public ip in k8s list of vdc ui
https://github.com/threefoldtech/vdc/issues/65
=> Replace private ip to public ip in k8s list of vdc ui

jumpscale/packages/vdc_dashboard/frontend/components/base/Sidebar.vue
Update vdc wallet dialog width to be bigger
[VDC wallet information popup is too small](https://github.com/threefoldtech/vdc/issues/61)
=> Update vdc wallet dialog width to be bigger

jumpscale/packages/vdc_dashboard/frontend/components/base/Kubernetes.vue, jumpscale/packages/vdc_dashboard/frontend/components/base/S3.vue
The size in the k8s and s3 tables don't indicate what it is.
- Change column title to Disk Size
- Add the unit to the size value
https://github.com/threefoldtech/vdc/issues/66
https://github.com/threefoldtech/vdc/issues/63
=> Add units to k8s and s3 disk size in ui

jumpscale/packages/vdc_dashboard/frontend/components/base/Kubernetes.vue, jumpscale/packages/vdc_dashboard/frontend/data.js
Sizes are represented as a map that maps to vCPU,memory and storage. The key is not an indication of the actual size in the UI of kubernetes table in vdc UI
Size is divided into vCPU, memory and storage in the UI instad of a single size colomn
https://github.com/threefoldtech/vdc/issues/66
=> Update kubernetess vm sizes in ui

jumpscale/packages/admin/frontend/components/settings/Settings.vue
Restore ssh keys section in Settings UI
Was merged here https://github.com/threefoldtech/js-sdk/pull/1537 but removed UI only part because of conflicts. Now restored in ths PR
https://github.com/threefoldtech/js-sdk/issues/1750
=> Restore ssh keys section in Settings UI

jumpscale/sals/vdc/threebot.py
To differentiate between explorers, the explorer name is included in the redis channel name.
=> add explorer to redis channel

jumpscale/packages/vdc/chats/new_vdc.py, jumpscale/packages/vdc_dashboard/bottle/deployments.py, jumpscale/packages/vdc_dashboard/frontend/api.js, jumpscale/packages/vdc_dashboard/frontend/components/base/Kubernetes.vue, jumpscale/packages/vdc_dashboard/frontend/components/solutions/DownloadKubeconfig.vue
- Add button to download kubeconfig file
- Add warning in the chatflow
- https://github.com/threefoldtech/vdc/issues/80
- [] Documentation
=> add button to download kubeconfig file

docs/wiki/threebot/threebot.md, jumpscale/packages/admin/services/diskcheck.py, jumpscale/packages/admin/services/heartbeat.py, jumpscale/packages/admin/services/stellar.py, jumpscale/packages/billing/services/billing.py, jumpscale/packages/tfgrid_solutions/services/auto_extend_pools.py, jumpscale/packages/vdc_dashboard/services/provision_wallet_billing.py, jumpscale/packages/vdc_dashboard/services/s3_auto_topup.py, jumpscale/packages/vdc_dashboard/services/transaction_from_prepaid_to_provision_wallet.py, jumpscale/servers/threebot/threebot.py, jumpscale/tools/servicemanager/servicemanager.py
Removed service name attribute to be passed on package installation. The current convention for the packages services naming is packagename_servicefilename e.g: admin_healthcheck, threebot_auto_extend_pool, ...
https://github.com/threefoldtech/js-sdk/issues/1815
=> Fix services naming to be passed on package installation

jumpscale/packages/vdc_dashboard/bottle/deployments.py, jumpscale/packages/vdc_dashboard/frontend/components/vdcSettings/Home.vue, jumpscale/packages/vdc_dashboard/frontend/components/vdcSettings/Wallet.vue
- Show dialog with a color error if the balance lower than two days and a color warning if lower than 14 days.
- Change the wallet balance color based on expiration days.
- https://github.com/threefoldtech/vdc/issues/101
=> Show alert for the VDC with low balance

jumpscale/packages/admin/frontend/App.vue, jumpscale/packages/admin/frontend/components/external/FarmManagement.vue, jumpscale/packages/admin/frontend/components/packages/Packages.vue
- Hide farm management item from the sidebar if not installed
-  Fix `github` key error.
- [Farm mgmt in main 3bot menu while irrelevant for non farmers](https://github.com/threefoldtech/js-sdk/issues/1824)
=> Hide farm management item from the sidebar if not installed

jumpscale/tools/zos/consumption/__init__.py, jumpscale/tools/zos/consumption/usage.py
```
(.venv) ➜  js-sdk git:(development_vdc_prices) ✗ jsng
JS-NG> j.tools.zos.consumption.calculate_vdc_price("silver")                                         
'256.2518592 TFT'
JS-NG> j.tools.zos.consumption.calculate_vdc_price("gold")                                           
'751.2634656 TFT'
JS-NG> j.tools.zos.consumption.calculate_vdc_price("platinum")                                       
'2498.1102432 TFT'
JS-NG> j.tools.zos.consumption.calculate_vdc_price("gold")                                           
'751.2634656 TFT'
```
- Add tool to calculate VDC price which contains (Kubernetes cluster, ZDB storage, 3Bot container)
=> add tool to calculate vdc price

jumpscale/packages/vdc_dashboard/sals/solutions_chatflow.py, jumpscale/sals/vdc/namemanager.py, jumpscale/sals/vdc/proxy.py, jumpscale/sals/vdc/size.py, jumpscale/sals/vdc/threebot.py
to use set it in the config manager
gateway: `j.config.set("VDC_DOMAIN_SOURCE", "gateway")`
name.com: `j.config.set("VDC_DOMAIN_SOURCE", "namecom")`
default value will be using `gateway` which defaults to `csfarmer`, to make development locally easier
=> add option to use csfarmer or name.com

jumpscale/entry_points/threebot.py, jumpscale/packages/threebot_deployer/package.py
- Limit 3bot deployer to only use STD wallets
- Limit 3bot deployer demos wallet to be STD
- https://github.com/threefoldtech/js-sdk/issues/2059
=> migrate threebot deployer and threebot server to use STD wallet

jumpscale/clients/stellar/stellar.py, tests/clients/stellar/test_stellarclient.py, tests/frontend/tests/test_wallets.py, tests/sals/zos/test_pools.py
Disable tests that include wallet creation until a proper cleanup is presented.
https://github.com/threefoldtech/js-sdk/issues/2062
=> disable wallet tests and add return xlms to activation wallet method

jumpscale/packages/vdc_dashboard/chats/taiga.py
A conflict happens in two different releases of taiga because the postgres subchart name was fixed.
Include the release name in the postgres subchart name
=> change the postgres subchart across different deployments

jumpscale/packages/vdc_dashboard/sals/solutions_chatflow.py
When the pod requests resources not available in the cluster, it gets stuck at "PENDING" state. In this PR it waits for the pods in the chart deployment for two minutes, if at any moment all pods got to RUNNING state it assumes there's enough resources. Otherwise,  after the two minutes it checks it at least on of the pods is pending and the last error message contained "Insufficient", if so it decides that there's no enough resources and removes chart.
Summary:
1. It deploys the chart and waits for it to fail to decide insufficient resources.
=> Fail if chart didn't deploy because of low resources

jumpscale/packages/vdc_dashboard/frontend/components/marketplace/Solution.vue, jumpscale/packages/vdc_dashboard/sals/vdc_dashboard_sals.py
- Fix if release haven't domain to show `-`
- [VDC: If the chart haven't any ingress applied, break listing releases](https://github.com/threefoldtech/js-sdk/issues/2086)
=> Fix if release haven't domain to show -

jumpscale/packages/tfgrid_solutions/scripts/threebot/minimal_entrypoint.py
The vdc instance were created even if it doesn't exist, which causes the entrypoint to fail.
=> Don't fail in 3bot entrypoint if run twice

jumpscale/packages/vdc_dashboard/bottle/deployments.py, jumpscale/packages/vdc_dashboard/frontend/api.js, jumpscale/packages/vdc_dashboard/frontend/components/vdcSettings/S3.vue
- [VDC: generate 0-stor config file to utilize the zdbs](https://github.com/threefoldtech/js-sdk/issues/2102)
=> Add two buttons to download z-stor config and zdbs data

jumpscale/sals/reservation_chatflow/deployer.py
```
JS-NG> j.sals.reservation_chatflow.deployer.block_managed_domain("3bottest.grid.tf")                 
JS-NG> j.sals.reservation_chatflow.deployer.list_blocked_managed_domains()                           
{'3bottest.grid.tf': {'expiration': 1610311404, 'failure_count': 2}}
JS-NG> j.sals.reservation_chatflow.deployer.list_blocked_managed_domains()                           
{'3bottest.grid.tf': {'expiration': 1610311404, 'failure_count': 2}}
JS-NG> j.sals.reservation_chatflow.deployer.clear_blocked_managed_domains()                          
True
JS-NG> j.sals.reservation_chatflow.deployer.list_blocked_managed_domains()                           
{}
```
- https://github.com/threefoldtech/js-sdk/issues/2154
=> add option to clear blocked domains

jumpscale/packages/vdc_dashboard/sals/solutions_chatflow.py, jumpscale/sals/marketplace/apps_chatflow.py
LetsIncrypt errors shouldn't be an issue as zerossl is now used instead. The final error should be beacuase of misconfigured gateways or gateways not correctly functioning
Change the failure message when using gateways
https://github.com/threefoldtech/js-sdk/issues/2153
=> Update failure message if misconfigured gateways were found

jumpscale/sals/vdc/deployer.py, jumpscale/sals/vdc/kubernetes_auto_extend.py, jumpscale/sals/vdc/vdc.py
include 0.1 * 24 * 30 when calculating how long the wallets can cover for the vdc
=> Development funded period

jumpscale/sals/vdc/deployer.py
change initial vdc deployment to use only one worker for all flavors 
https://github.com/threefoldtech/js-sdk/issues/2123
=> start vdc with only one worker for all flavors

jumpscale/servers/threebot/threebot.py
Add option to add custom locations to the default server instead of custom servers
- Add locations from package.toml that would be added for example in the following custom location
```
[[locations]]
name = "custom"
type = "custom"
custom_config = """
location /customlocation/ {
rewrite /customlocation/(.*)$ /customlocation_redirection/$1;
}
"""
```
- To be used for https://github.com/threefoldfoundation/tft-stellar/issues/262 to add multiple custom locations for different packages in the same location server(default)
=> Add locations from package.toml for default server

jumpscale/clients/stellar/stellar.py
Two fields were missing in the definition of the stellar client, resulting in an AttributeError when reaching code that depends on them.
This fixes [Error in the tx funding service](https://github.com/threefoldfoundation/tft-stellar/issues/264)
=> Add missing fields in the stellar client

jumpscale/packages/threebot_deployer/bottle/utils.py
raise DeploymentFailed when all retries fail instead of return empty
https://github.com/threefoldtech/js-sdk/issues/2319
=> raise DeploymentFailed when all retries fail to redeploy 3bot

docs/vdc/forwarding_ports_using_socat.md, jumpscale/packages/tfgrid_solutions/scripts/threebot/minimal_entrypoint.py, jumpscale/packages/vdc_dashboard/bottle/deployments.py, jumpscale/packages/vdc_dashboard/sals/solutions_chatflow.py, jumpscale/sals/kubernetes/manager.py, jumpscale/sals/vdc/deployer.py, jumpscale/sals/vdc/threebot.py, jumpscale/sals/vdc/vdc.py
This pr adds support for exposing ports of services using `socat`
- Generates keys to `vdc threebot` and adds public keys to the cluster
- Adds method in solutions_chatflow.py to expose ports
- Validate if the port already exposed to prevent conflicts
- Create a service for Socat on k8s master node
- Stop and Delete the service if the solution was deleted to make sure everything is clean
https://github.com/threefoldtech/js-sdk/issues/2199
=> Development vdc 3bot keys socat

jumpscale/packages/admin/frontend/components/pools/Pools.vue, jumpscale/packages/admin/frontend/components/solutions/SolutionChatflow.vue, jumpscale/packages/tfgrid_solutions/chats/extend_pools.py, jumpscale/packages/tfgrid_solutions/chats/pools.py
- Split capacity pools chatflows to separate extend and create chatflows
- Add separate button for extend of each capacity pool in admin dashboard pools
- Add passing of query param options in solutions chatflows in admin dashboard
- Add seperate button for extend in actions colomn
- Split chatflows
https://github.com/threefoldtech/js-sdk/issues/2220
=> Split capactity pools chatflows to seperate extend and create chatflows

jumpscale/packages/admin/frontend/components/dashboard/MemoryUsage.vue
Dashboard: Fix memory usage percentage
calculate percentage from used and total fields instead of the percent field of psutil which calculated from the available memory not the used ones. See https://psutil.readthedocs.io/en/latest/#psutil.virtual_memory
https://github.com/threefoldtech/js-sdk/issues/878
=> Dashboard: Fix memory usage percentage

jumpscale/packages/vdc/chats/new_vdc.py
VDC remove kubeconfig download from success message and tell the user that it can be download from the dashboard
https://github.com/threefoldtech/js-sdk/issues/2245
=> VDC remove kubeconfig from success message

jumpscale/servers/threebot/threebot.py
Some services saves their state in redis and it appears that gedis also somehow depends on it. so it makes sense to stop it after all the components that depends on it is stopped.
An example of when the redis fails some services:
=> Stop redis last when killing 3bot

jumpscale/packages/tfgrid_solutions/scripts/threebot/restart.sh
Send SIGKILL after 2 minutes if the server didn't stop with SIGTERM
https://github.com/threefoldtech/js-sdk/issues/2246
=> Send sigkill if sigterm failed when stopping 3bot

jumpscale/packages/vdc_dashboard/frontend/data.js
- Fix the helpLink for file browser solution to be [https://now.threefold.io/now/docs/file-browser/](https://now.threefold.io/now/docs/file-browser/)
- https://github.com/threefoldtech/js-sdk/issues/2380
=> Fix the helpLink for file browser solution

jumpscale/packages/threebot_deployer/bottle/utils.py
check and clean old subdomain workloads before redeploying the subdomain
https://github.com/threefoldtech/js-sdk/issues/2414
=> delete old subdomain workloads

jumpscale/sals/marketplace/apps_chatflow.py
- Since we are using zerossl with unlimited certificates, we don't need to raise when crt.sh is unreachable
- https://github.com/threefoldtech/js-sdk/issues/2422
=> only log certificates warnings

jumpscale/packages/vdc_dashboard/bottle/deployments.py
- Add random value as the default for the zstor encryption key
```
secrets.token_hex([nbytes=None])¶
Return a random text string, in hexadecimal. The string has nbytes random bytes, each byte converted to two hex digits. If nbytes is None or not supplied, a reasonable default is used.
```
- [https://github.com/threefoldtech/js-sdk/issues/2425](https://github.com/threefoldtech/js-sdk/issues/2425)
=> Add random value as the default for the zstor encryption key

jumpscale/packages/threebot_deployer/chats/threebot.py
remove obselete wg paths in threebot deployer
https://github.com/threefoldtech/js-sdk/issues/2424
=> fix wireguard config

.github/workflows/js-sdk-check-wheel.yml
Fixing a workflow job name typo chec --> check
=> chore: Fixing a typo in js-sdk-check-wheel.yml

jumpscale/clients/github/repo.py, jumpscale/packages/vdc_dashboard/chats/blog.py, jumpscale/packages/vdc_dashboard/chats/publisher.py, jumpscale/packages/vdc_dashboard/chats/website.py, jumpscale/packages/vdc_dashboard/chats/wiki.py, jumpscale/packages/vdc_dashboard/sals/solutions_chatflow.py
Update instructions to be more clear and fix blog, website and wiki listing.
- Adding a new class variable called `CHART_NAME` that can be used for chart name instead of solution type in `SolutionsChatflowDeploy`
- Update base publisher to use `CHART_NAME` and set the correct solution type.
- Pass `nameOverride` with the new solution type in blog, website and wiki chatflows.
- Change instructions in blog, website and wiki chatflows.
#2375
=> VDC: Fix publishingtools listing and update instructions

.github/workflows/js-sdk.yml
Adding the workflow feature requested in issue #2256
- Now js-sdk build tests should run only when a python file `*.py` changed somewhere in the project
- update: after the discussion, `.github/workflows/**.yml` as well as `pyproject.toml` and `poetry.lock` files added to paths and the workflow will trigger if one of these files changed too.
- This affects the js-sdk workflow only. the js-sdk-check-wheel workflow will still work on every Push or PR.
closes #2256
=> Run js-sdk build tests only when a python file changed

jumpscale/packages/vdc_dashboard/chats/cryptpad.py
Supporting extra storage for cryptpad chart through k8s volumes
Currently the volume is of type hostPath, but will be changed to local in another PR (because hostPath cannot be backuped)
https://github.com/threefoldtech/vdc-solutions-charts/issues/18
=> Supporting extra storage for cryptpad chart through k8s volumes

jumpscale/packages/vdc_dashboard/bottle/deployments.py, jumpscale/packages/vdc_dashboard/frontend/api.js, jumpscale/packages/vdc_dashboard/frontend/components/marketplace/Solution.vue, jumpscale/packages/vdc_dashboard/sals/vdc_dashboard_sals.py
VDC solution lists included all deployments and so a chart that included multiple deployments will show them in listing of solutions. This needs to change to only list one instance of the deployed solution.
example:
- Get all possible solution types defined in frontend, and send them in the request to get the deployed solutions
- Loop over the solution types and get the deployments for it using the single solution type function, then merge all these results and return to frontend
- Use gevent to reduce time taken to get the deployment information for each solution type
- Change label of deployment colomn to "Solution Type"
example after changes:
https://github.com/threefoldtech/js-sdk/issues/2459
=> Change listing of all vdc solutions to only list specific solution types

jumpscale/packages/admin/frontend/components/dashboard/Dashboard.vue
Create/Extend Pool button in admin dashboard goes to creating a new pool chatflow so needs to be renamed after the create and extend chatflows were seperated
- Change "Create/Extend Pool" to "Create Pool" in admin dashboard
https://github.com/threefoldtech/js-sdk/issues/2220
=> Change create/extend pool button to only create

jumpscale/packages/vdc_dashboard/sals/solutions_chatflow.py
Fixes:
```
root@zosv2-05:~# tail -f ~/.config/jumpscale/logs/fs/log.txt -n 10
File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/packages/vdc_dashboard/sals/solutions_chatflow.py", line 87, in _validate_resource_limits
queries = [{"cpu": cpu, "memory": memory}] * no_nodes
│              │          └ '1'
│              └ 128
└ 100
TypeError: can't multiply sequence by non-int of type 'str'
```
=> convert no_nodes from string to int

jumpscale/sals/vdc/kubernetes_auto_extend.py
Sometimes the cpu usage is passed in this format:
https://github.com/threefoldtech/js-sdk/issues/2474
=> Handle the case when the cpu is passed as cores not milicores

jumpscale/packages/chatflows/frontend/components/String.vue, jumpscale/packages/threebot_deployer/chats/threebot.py
- Change chatflow frontend validation to be on_change instead of on_burl
- Change the 3Bot name message in the chatflow
https://user-images.githubusercontent.com/36021484/108349229-6757e980-71eb-11eb-8864-78bc908d9d30.mp4
- https://github.com/threefoldtech/js-sdk/issues/2237
=> Change chatflow frontend validation to be on_change instead of on_burl

jumpscale/clients/explorer/models.py, jumpscale/sals/zos/kubernetes.py
PR will be needed for spawning kubernetes cluster with external etcds without doing any manual work on the k3s. related to #2553  let's not merge before the explorer is updated
=> Update kubernetes workload with etcd datastore endpoint and disable default ingress

jumpscale/packages/admin/actors/admin.py, jumpscale/packages/vdc/bottle/api.py, jumpscale/packages/vdc/frontend/api.js, jumpscale/packages/vdc/frontend/components/solutions/Wallet.vue, jumpscale/packages/vdc/frontend/index.html, jumpscale/packages/vdc_dashboard/bottle/deployments.py, jumpscale/packages/vdc_dashboard/frontend/api.js, jumpscale/packages/vdc_dashboard/frontend/components/vdcSettings/Wallet.vue, jumpscale/packages/vdc_dashboard/frontend/index.html
To top up a vdc wallet, the address needs to manually be transferred to the Threefold Connect app to fund this wallet. A top up QRCode should be available to simply scan using the app and fund the wallet.
Add top up wallet QRCodes with 100 TFT default value in vdc deployer and vdc dashboard wallets
https://github.com/threefoldtech/js-sdk/issues/2502
=> Add wallet topup qrcode in vdc dashboard and vdc deployer

jumpscale/packages/vdc_dashboard/sals/solutions_chatflow.py
Modify check if pod ready in the deployment process to use **READY** state instead of using **PHASE** state
#2592
=> Check with ready not with phase

jumpscale/packages/vdc_dashboard/chats/etcd.py
Update etcd chatflow with more info related to certificate and add additional msg shown only if cert not verified, This message contains another method to use etcd using kubectl.
=> Update etcd chatflow with more info

jumpscale/sals/vdc/kubernetes_auto_extend.py
The additional calls fails when any pod from the original listing is removed.
Fixes
https://github.com/threefoldtech/js-sdk/issues/2474#issuecomment-784333019
=> Get pods specs from the original call

.github/workflows/full.yml, pyproject.toml
Add marker `extend` for excluding the expensive tests to run daily 
#2601
=> Add marker extend for excluding the expensive tests

solutions_automation/vdc/deployer.py, tests/sals/automated_chatflows/test_vdc_dashboard.py
Update etcd chatflow with subdomain step in gedispatch and Skip taiga and discourse tests for now
=> Update and fix VDC dashboard tests

jumpscale/clients/stellar/stellar.py, jumpscale/packages/marketplace/package.py, jumpscale/packages/threebot_deployer/package.py, jumpscale/sals/vdc/wallet.py, tests/frontend/tests/test_packages.py, tests/sals/vdc/vdc_base.py, tests/sals/zos/test_pools.py
- Use activation wallet for vdc wallets activation instead of the activation service
- Remove creating wallet while adding packages.
- Adjust the tests for the activation wallets.
#2637
=> Use activation wallet for vdc wallets activation instead of the activation service

jumpscale/packages/admin/frontend/components/packages/Package.vue, jumpscale/packages/marketplace/package.toml, jumpscale/servers/threebot/threebot.py
- Allows packages to have human readable name using ui_name in config and fallback to package name if it's not defined.
- Changes the flist marketplace package UI name to 3bot_apps
Should fix https://github.com/threefoldtech/home/issues/1019 and #2645
=> Add UI name to packages and change flist marketplace to 3bot_apps

jumpscale/tools/servicemanager/servicemanager.py
appname is called app_name in the method
=> fix service manager typo

jumpscale/packages/admin/frontend/App.vue, jumpscale/packages/admin/frontend/components/legal/License.vue, jumpscale/packages/marketplace/frontend/App.vue, jumpscale/packages/marketplace/frontend/components/License.vue, jumpscale/packages/threebot_deployer/frontend/App.vue, jumpscale/packages/threebot_deployer/frontend/components/License.vue, jumpscale/packages/vdc/frontend/App.vue, jumpscale/packages/vdc/frontend/components/License.vue, jumpscale/packages/vdc_dashboard/frontend/App.vue, jumpscale/packages/vdc_dashboard/frontend/components/License.vue
Clear cache on logout to disallow user access on clicking back button after logging out.
**Should be merged into one component after the frontend code is refactored**
https://github.com/threefoldtech/js-sdk/issues/2581
=> Clear cache on logout

.github/workflows/js-sdk-check-wheel.yml
Disabling python 3.9 CI build
in this modified workflow
- CI runner is no more run tests on Python 3.9
- it makes sure that pip is the latest version
=> Disabling python 3.9 CI build

jumpscale/packages/threebot_deployer/bottle/utils.py
- The state was set to error and never went back
=> fix state when restoring threebot state

jumpscale/packages/vdc_dashboard/bottle/backup.py
204 causes
```
<h1>Critical error while processing request: /api/backup/delete</h1>127.0.0.1 - - [2021-03-02 14:38:58] "POST /api/backup/delete HTTP/1.0" 500 222 0.591415
```
=> fix status code for deleting backup

jumpscale/packages/vdc_dashboard/chats/presearch.py
The Presearch node is deployable with less resources. In the chatflow, we need to lower the chart limits for the users to select less resources.
- Lower chart limits in the chatflow
https://github.com/threefoldtech/js-sdk/issues/2684
=> presearch node - lower chart limits

jumpscale/packages/vdc_dashboard/bottle/deployments.py, jumpscale/packages/vdc_dashboard/frontend/components/vdcSettings/Home.vue
- Fix get local latest tag for js-sdk repo
- get the latest local tag from the right dir
- https://github.com/threefoldtech/js-sdk/issues/2712
=> Fix get local latest tag for js-sdk repo

jumpscale/sals/vdc/vdc.py
Fix floating-point that not rounded in extend node message
#2670
=> Update amount in extend to be rounded

jumpscale/servers/threebot/threebot.py
Solves #2744
gevent.signal is deprecated, gevent.signal_handler is the same ( https://github.com/gevent/gevent/blob/1.4.0/src/gevent/__init__.py )  but supported in newer gevent versions
In the start of the threebot, replacement of `gevent.signal` with `gevent.signal_handler`
gevent.signal is deprecated, use gevent.signal_handler : #2744
=> use gevent.signal_handler instead of the deprecated gevent.signal

docs/tests/sals/kubernetes/test_kubernetes.md, tests/sals/kubernetes/test_kubernetes.py
Kubernetes tests failed because we use bitnami images which add more auth password when updating
- Use marketplace repos instead of bitnami
- Use Cryptpad chart instead of etcd
=> Fix Kubernetes tests

tests/sals/automated_chatflows/test_vdc_dashboard.py, tests/sals/vdc/vdc_base.py
In VDC Dashboard testing, VDC expire before the end of the tests because it deploys default for 1 hour, Add hours attribute to deploy VDC with custom number of hours
- Add hours attribute for deploy_vdc function
- For double test deploy it for 2 hours
=> Add hours attribute to deploy VDC

jumpscale/packages/vdc_dashboard/frontend/data.js
Fix the Matic object key in the js dictionary
change the object key to lower case characters, because the `object key` and the `type` have to be similar.
=> Fix the Matic object key in the js dictionary

jumpscale/sals/vdc/s3.py
Change the default starting port for socat proxy from 9900 to 9910
#2715
=> Change the default starting port for socat proxy from 9900 to 9910

jumpscale/clients/stellar/__init__.py, jumpscale/clients/stellar/stellar.py
before, un unfound unlockhash on an escrow account resulted in a crash in the get_balance method , see #2812
Now it shows:
```
j.clients.stellar.robtest.get_balance()
Balances
10000.0000000 XLM
Locked balances:
- Escrow account GAPABHUXFY5C2KT33Y4RSIX2OBAPM3BHFJZR6R5WQ6Y5T4UUW6CMPR3N with unknown unlockhashes ['TBXLGRBJQY7SF7JJAGCXT7K7RZG4TJUPHFWVG4UINGPMZTSW7LAB6E2R']
- 0.0000000 TFT:GA47YZA3PKFUZMPLQ3B5F2E3CJIB57TGGU7SPCQT2WAEYKN766PWIMB3
- 7.5998700 XLM
- Escrow account GASQGXK4YJ2QGGUPNMEMI34PVDRYNO6RN4KTNDISYYK2ZRB5QPMIERX3 with unknown unlockhashes ['TBCG52AFPFLBMIQSLSPNCEI6IPK5TS3LHQSK7X53BYXLTA3LZPU7L3H7']
- 0.0000000 TFT:GA47YZA3PKFUZMPLQ3B5F2E3CJIB57TGGU7SPCQT2WAEYKN766PWIMB3
- 7.5998700 XLM
- Escrow account GAVUGUYJKKSW2QA6T6MHJKFWZN7YJQZ54DBUDBYTEQUML4J64I3TE5CI with unknown …
```
=> Handle unfound unlockhashes in the stellar client gracefully

jumpscale/packages/vdc_dashboard/bottle/backup.py
When restoring vdc backup, user is unaware it may take some time
Update vdc backup restore msg to warn it will take time
https://github.com/threefoldtech/js-sdk/issues/2790
=> Update vdc backup restore msg to warn it will take time

jumpscale/packages/vdc/chats/new_vdc.py, tests/sals/automated_chatflows/test_vdc_dashboard.py, tests/sals/vdc/test_vdc.py
- Use vdc password hash instead of password directly for backup config to allow spaces and quotes
- Fix cost method call in tests.
#2804
=> Use vdc password hash

jumpscale/packages/vdc_dashboard/frontend/components/base/Info.vue, jumpscale/packages/vdc_dashboard/frontend/components/base/JSONRenderer.vue
- Reverse calculate `timeDifference` in the base JSONRenderer component
- https://github.com/threefoldtech/js-sdk/issues/2840
=> Reverse calculate timeDifference in the base JSONRenderer component

jumpscale/sals/vdc/deployer.py, jumpscale/sals/vdc/vdc.py
When the vdc name is "new", the base factory raises an exception when trying to find instance with the name "new".
https://github.com/threefoldtech/js-sdk/issues/2848
=> Prefix ssh key to avoid special name errors

jumpscale/packages/threebot_deployer/bottle/utils.py
- workload information were cached
- https://github.com/threefoldtech/js-sdk/issues/2797
=> fix threebot workloads deletion state

jumpscale/sals/vdc/vdc.py
The problem was that we load vdc info in deployer to exclude master's node for deploying the workers, at the same time one of zdbs workload is not ready yet to get its info, so got `NoneType is not iterable`
=> Skip zdb workload in case it is not ready yet

jumpscale/clients/stellar/stellar.py
Stellar client: if the network isn't indicated, things don't work on production, only on testnet
Fixes #2904
=> Stellar client: Make stuff work on production

jumpscale/entry_points/threebot.py, jumpscale/sals/nginx/nginx.py, jumpscale/servers/threebot/__init__.py, jumpscale/servers/threebot/threebot.py
3Bot takes a lot of time when run locally because of failing to generate a certificate from certbot. cert paramter added to the threebot command and start method to allow disabling it.
=> Add cert parameter to allow disabling certbot certificate generation

jumpscale/packages/vdc_dashboard/chats/digibyte.py, jumpscale/packages/vdc_dashboard/chats/presearch.py
Need to limit unnecessarily long solution names by the user because it is used as release_name is in helm charts to distinguish different services in the cluster and at times the helm charts fail to deploy if the names are more than 15 characters
=> Limit long solution names for Digibyte and Presearch

jumpscale/packages/vdc_dashboard/chats/taiga.py, jumpscale/packages/vdc_dashboard/sals/solutions_chatflow.py
Update `vdc_dashboard` chatflow sal
- to be able to see the pod initialization timeout from the solution chat flow, to extend it in chat flows take long time
- Separate the checking on resources and checking on deploying in the right time into different if conditions to handle edge cases and get more meaningful messages
- jumpscale/packages/vdc_dashboard/chats/taiga.py
- jumpscale/packages/vdc_dashboard/sals/solutions_chatflow.py
https://github.com/threefoldtech/js-sdk/issues/2846
=> Development vdcchatflows fix

jumpscale/sals/zos/node_finder.py, jumpscale/tools/zos/reporting/__init__.py
- Implement report available capacity on nodes for specific explorer
- Update viewing  the usage usage of public ips to terminal table
=> report availble capacity on nodes for specific explorer

jumpscale/entry_points/threebot.py, jumpscale/packages/admin/bottle/admin.py, jumpscale/packages/admin/frontend/api.js, jumpscale/packages/admin/frontend/components/settings/Settings.vue, jumpscale/packages/vdc_dashboard/bottle/export.py, jumpscale/packages/vdc_dashboard/frontend/api.js, jumpscale/packages/vdc_dashboard/frontend/components/vdcSettings/Kubernetes.vue, jumpscale/packages/vdc_dashboard/package.toml, jumpscale/tools/export/__init__.py
- Export the 3Bot state as a gzip file containing:
1. `~/.config/jumpscale/` directory
2. `~/.kube/config` file
- Confirm when importing to override the mentioned files.
https://github.com/threefoldtech/js-sdk/issues/2793
=> Add export state command and endpoint for the 3bot

jumpscale/packages/vdc_dashboard/frontend/components/vdcSettings/Actions.vue, jumpscale/packages/vdc_dashboard/frontend/components/vdcSettings/Backups.vue
Fix new backup listing by adding a variable timeout with the reload event.
For create --> 10 sec
For delete --> 5 sec
Default      --> 2 sec
#2921
- Create backup
- Delete backup
=> Fix new backup listing

jumpscale/sals/vdc/deployer.py
fixing issue #2963, where VDC deployer calls a string method on Enum object when VDC chat-flow triggers the auto-extend.
however, a major refactor should be considered so the variable passed to the deployer always be either Enum or string for the sake of consistency.
Add type checking in` _check_added_worker_capacity` method to ensure proper handling of `flavor` variable to handle the case when the variable is Enum object, not a string. 
https://github.com/threefoldtech/js-sdk/issues/2963
=> fixing VDC deployer calls string method on Enum object

jumpscale/packages/vdc_dashboard/chats/discourse.py, jumpscale/packages/vdc_dashboard/chats/mastodon.py, jumpscale/packages/vdc_dashboard/chats/taiga.py, jumpscale/packages/vdc_dashboard/sals/solutions_chatflow.py, jumpscale/sals/kubernetes/manager.py
- Update the chatflow to send port number, and other possible numerical values without the need to double quotes the value.
- Add method `get_config_string_safe` to handle setting or override existing chart values without the helm type casting.
- Increase helm ’install’ command timeout from the default 5 minutes to 7 minutes in the `Kubernetes manager`.
- Handle the exception raised by the k8s `manager` when helm command failed by delete the release and stop the chat flow.
- Increase the default values for `timeout` and `pod_initialization_timeout`.
https://github.com/threefoldtech/js-sdk/issues/2942
https://github.com/threefoldtech/js-sdk/issues/2951
=> Development chatflow envvars

jumpscale/packages/vdc_dashboard/services/bandwidth_limit.py
Add bandwidth service to vdc_dashboard to limit the kubernetes cluster network bandwidth
#2968
=> Add bandwidth service to vdc_dashboard

jumpscale/sals/vdc/kubernetes_auto_extend.py, poetry.lock, pyproject.toml
Fixes #3013  by using generic kubernetes.io/hostname over k3s.io/hostname which wasn't set for some reason
and for the mentioned VDC in the issue 
```
root@vdc-testnet:~/sandbox/cfg/vdc/kube/mazraa# kubectl get nodes -o wide -o json --kubeconfig=./rudy2.yaml | jq '.items[]["metadata"]["labels"]["k3s.io/hostname"]'
null
null
"k3os-26866"
root@vdc-testnet:~/sandbox/cfg/vdc/kube/mazraa# kubectl get nodes -o wide -o json --kubeconfig=./rudy2.yaml | jq '.items[]["metadata"]["labels"]["kubernetes.io/hostname"]'
"k3os-1357"
"k3os-17130"
"k3os-26866"
```
=> kubernetes.io/hostname label instead of k3s's

jumpscale/packages/vdc_dashboard/chats/digibyte.py
Based upon different tests, we have noticed that DGB node consumes over 10GB of memory. The compute limits need to be adjusted accordingly
=> Digibyte : Set Compute Limits

jumpscale/packages/vdc/chats/new_vdc.py
that shouldn't block the VDC deployment, right now the user needs to move from the step of deploying kubernetes and zdbs to deploy/init the threebot
=> Deploy kubernetes, ZDBs and initialize threebot in the same step.

jumpscale/packages/tfgrid_solutions/scripts/threebot/minimal_entrypoint.py
- harden entrypoint against empty env variables when redeploying 3bot container
=> harden entrypoint against empty env variables when redeploying 3bot container

jumpscale/sals/vdc/kubernetes_auto_extend.py
- In case the node usage is 0 it can cause miscalculations or zero division error
- https://github.com/threefoldtech/js-sdk/issues/3040
=> harden default value to calculate capacity for nodes with usage 0 or not ready

jumpscale/packages/vdc/bottle/api.py, jumpscale/packages/vdc/chats/new_vdc.py, jumpscale/packages/vdc/services/fund_prices_diff.py, jumpscale/packages/vdc/services/update_expiration.py, jumpscale/sals/vdc/grace_period.py, jumpscale/sals/vdc/vdc.py
- Make vdc is_empty method load the info by default
- Fix error message in vdc chatflow
#2958
=> Make vdc is_empty method load the info by default

jumpscale/packages/vdc_dashboard/bottle/api/deployments.py
fix #3087 by increasing invoke timeout from 600 to 1200 to cover rare cases when the dependencies take a long time to install during update the VDC
#3087
=> Development dashboard update hotfix1

jumpscale/install/rootfs/etc/zinit/start.yaml, jumpscale/packages/admin/package.toml, jumpscale/packages/auth/package.toml, jumpscale/packages/chatflows/package.toml, jumpscale/packages/marketplace/package.toml, jumpscale/packages/polls/package.toml, jumpscale/packages/stellar_stats/package.toml, jumpscale/packages/threebot_deployer/package.toml, jumpscale/packages/vdc/package.toml, jumpscale/packages/vdc_dashboard/bottle/api/controller.py, jumpscale/packages/vdc_dashboard/bottle/app.py, jumpscale/packages/vdc_dashboard/package.toml
Fix side effects of moving all bottle apps to a single server.
- Remove 3bot auth from controller API as it already has its own authentication.
- Make controller a separate app
- Add a new non-standalone bottle server in `package.toml` of `vdc_dashbord`
- Fix status check in vdc start script
- Remove unwanted port from all non-standalone bottle servers 
#3090
=> Fix side effects of moving all bottle apps to a single server

jumpscale/packages/vdc_dashboard/frontend/components/vdcSettings/Actions.vue, jumpscale/packages/vdc_dashboard/frontend/components/vdcSettings/Backups.vue
Verify new backup names that the user creates if it contains space or used before.
- Check if the backup name contains space
- Check if the backup name duplicated
#3035 
#3104
=> Verify backup name

.github/workflows/js-sdk.yml
Fixing issue #3110 with js-sdk current workflow, the problem was setup-python GitHub action sets a new python Installation for the current user `runner` while using `sudo` with pip makes poetry get installed for default root Python installation that comes preinstalled with the system, which in the case of ubuntu 18, was 3.6 and for ubuntu 20, 3.8 regardless of the matrix setup.
in this modified workflow:
- now poetry install will pick the correct Python environment sets by the GitHub action matrix
- before the fix
- after the fix
closes #3110
=> fixing CI workflow issue #3110

jumpscale/install/Dockerfile
The recommended poetry install method is applied.
Poetry adds its bin to path in ~/.profile but it's not loaded when logging in with bash so it's added also to ~/.bashrc. 
#3081
=> Use curl installer for poetry

jumpscale/packages/vdc_dashboard/bottle/api/deployments.py, jumpscale/packages/vdc_dashboard/frontend/api.js, jumpscale/packages/vdc_dashboard/frontend/components/vdcSettings/DeleteConfirmation.vue, jumpscale/packages/vdc_dashboard/frontend/components/vdcSettings/Kubernetes.vue, jumpscale/sals/vdc/deployer.py, jumpscale/sals/vdc/kubernetes.py, jumpscale/sals/vdc/kubernetes_auto_extend.py
Drain Kubernetes node before deleting it
- Check for availability of using drain by check the remaining cluster resources and the pods on the node to be drained
- Inform the user if there are pods that can't be deployed again due to lack of resources in the cluster after deleting the node.
-If the user confirms the deletion, delete the releases that need to be deleted and then drain node, and delete it safely
#3065
- list of the pods deployed on the node we want to delete, (Taiga, Cryptpad, Peertube)
- Delete the worker for UI (Cryptpad can't be redeployed again because of resources limitation)
- Check that all the remaining pods redeployed on other nodes and solutions still running (Taiga, Peertube)
=> Drain kubernetes node before deleting

jumpscale/tools/nginx/nginxserver.py, tests/sals/nginx/test_nginx.py
due to an OS limitation (on macOS, and possibly Solaris), checking if Nginx started by matching the full command line started the process with the command line of running processes could fail, or require higher privileges.
this PR introduce a better and faster approach to verify if Nginx started that should work equally well on both Mac and Linux.
check this issue #3116 and this [comment](https://github.com/threefoldtech/js-sdk/issues/3116#issuecomment-848637414) for more context.
knowing that The process ID of the Nginx master process is written to the `nginx.pid` file after Nginx started.
- getting the path to the PID file by reading the PID directive in the Nginx configuration file.
- set a check command for `startupcmd`, that checking if the file exists to verify if the Nginx process …
=> verify Nginx by pid file instead of regex string

jumpscale/packages/vdc_dashboard/frontend/components/vdcSettings/Actions.vue
- Use numbers and small letters only for backup name
- Use v-alert instead of regular p element
#3035
=> Use numbers and small letters only for backup name

jumpscale/install/Dockerfile, jumpscale/packages/tfgrid_solutions/scripts/threebot/entrypoint.sh
Apparently the permissions in the container is discarded in the flist when started.
1. add export to poetry path addition in ~/.bashrc
2. chmod its permission.
#3081
=> Fix poetry permissions and path

jumpscale/sals/reservation_chatflow/reservation_chatflow.py, jumpscale/sals/vdc/scheduler.py
Change bot usage in reservation chatflow sal to be optional in get_ip_range
- Update usage of accessnode flag in scheduler
- Change bot usage in reservation chatflow sal to be optional in get_ip_range
- Pass accessnode flag to be used correctly in scheduler
- get_ip_range now takes bot=None, and is updated to work if no chatbot is passed
=> Fix usage of accessnode flag in scheduler

jumpscale/packages/vdc/chats/new_vdc.py, jumpscale/packages/vdc/services/renew_plans.py
Adds a plan-renew service
implementation is
-  just submitting in the chatflow the vdc name to specific renewals requests queue 
- immediately pushing that to the undhandled queue
- process the plan renewal and only if succeeded ack and remove from the unhandled queue
=> Add renew plans service

jumpscale/packages/tfgrid_solutions/scripts/threebot/minimal_entrypoint.py, jumpscale/packages/vdc/chats/new_vdc.py, jumpscale/sals/nginx/nginx.py, jumpscale/sals/vdc/deployer.py, jumpscale/sals/vdc/threebot.py, jumpscale/servers/threebot/threebot.py
Use the new pre-fetching API of our CA server and update certbot to accept existing cert.
* Update custom certbot to accept `key_path`, `cert_path` and `fullchain_path`
* Update package config to accept these path argument
* Update VDC deployer to pre-fetch the certificate and pass it to theebot being deployed
* Update `minimal_entrypoint.py` to write these key/certificates and update `vdc_dashboard` config with it.
https://github.com/threefoldtech/home/issues/1068
=> VDC: pre-fetch certificate and install it directly for controller threebot

jumpscale/packages/vdc/services/check_threebot.py
Fix `check_threebot` by using the get function with the S3_AUTO_TOPUP_FARMS key instead of direct access
#3099
=> Fix check threebot service

jumpscale/sals/vdc/kubernetes_auto_extend.py
Co-authored-by: Mohammed Essam <mohammedelborolossy@gmail.com>
fixing few methods in KubernetesMonitor class that responsible for calculating the **total, reserved, and free** resources on the VDC cluster.
**before** (incorrect calcs) js-sdk 011bea80b0603dd2ca106fefa6832fa54658757c
**after - this branch**
closes #3179
also related to #3180
=> Fixing the node resources calculation.

jumpscale/packages/vdc/services/renew_plans.py
Fix transfer amount in renew_plan service by round it to 6 digits only
#3198
=> Fix transfered amount in renew_plan service

jumpscale/sals/vdc/kubernetes_auto_extend.py
Co-authored-by: Mohammed Essam <mohammedelborolossy@gmail.com>
enhance parsing `kubectl` output to handle a very rare case (but valid) when the node allocated memory requests is '0'.
=> minor fix to reporting the allocated resources

jumpscale/packages/tfgrid_solutions/scripts/threebot/velero.py, jumpscale/packages/vdc_dashboard/services/upgrade_traefik.py, jumpscale/tools/servicemanager/servicemanager.py
Use different way to get version of the current traefik release, fix some typos
- Get the version of the current Traefik release correctly
- Add logs for the exceptions to the running services in the service manager.
- Get password from vdc directly instead of zdb monitor in velero service.
#3190, #3195
=> Update Traefik service now working

jumpscale/packages/marketplace/package.toml
Exclude the marketplace package from the admin dashboard
- jumpscale/packages/marketplace/package.toml
- https://github.com/threefoldtech/js-sdk/issues/3184
=> Exclude the marketplace package from the admin dashboard

jumpscale/packages/vdc_dashboard/bottle/api/deployments.py, jumpscale/packages/vdc_dashboard/sals/vdc_dashboard_sals.py
Improving the deployed solutions listing performance by ~17X 
**before:**
**after:**
- modifying get_all_vdc_deployments() from VDC dashboard sal and using it instead of get_all_deployments().
- adding an optional parameter get_all_vdc_deployments() to filter the solutions with a list of solution types.
- remove the blocking call.
#3069
=> Improving the deployed solutions listing performance

.github/workflows/js-sdk_macos.yml
initial macOS workflow for js-sdk that installs the dependencies, installs the project, and runs our unit tests.
it will run only when manually triggered.
#3115
=> initial macos workflow for js-sdk

jumpscale/tools/nginx/nginxserver.py
adding extra checks to make sure of the real state of Nginx when threebot server starts.
is_running() now will check if the PID file specified in the Nginx configuration file Is exists, contains PID that belongs to a running Nginx master process.
#3160
=> fix issue#3160 

jumpscale/packages/chatflows/frontend/App.vue, jumpscale/packages/chatflows/frontend/index.html
If there is a chatflow (example: extend pools) that takes query params `pool_id` to be extended and this chat is opened with a different `pool_id`, it will open the same chatflow as both depend only on the chat name.
This should solve the problem by taking the query params into consideration and get different sessions for the difference in query params.
=> Use different chatUID for chatflows with query params

jumpscale/tools/servicemanager/servicemanager.py
add option for services to immediate schedule upon addition
- Add `self.schedule_on_start = True` on your service and you are good to go
=> add option for services to immediate schedule upon addition

jumpscale/packages/vdc_dashboard/frontend/components/vdcSettings/RedeployMaster.vue
Use Number instead of String for wid in redeploy master prop
#3209
=> Use Number instead of String for wid in redeploy master frontend

jumpscale/packages/threebot_deployer/bottle/utils.py
Listing 3bots deployed take time, loading needs to be quicker
Changed check for reaching 3bot to `j.sals.reservation_chatflow.check_url_reachable(...)` to not use gevent which waits on failure of reaching so waits for timeout.
https://github.com/threefoldtech/js-sdk/issues/3228
=> Update reachability check in 3bot deployer listing to not use gevent

jumpscale/packages/threebot_deployer/chats/change_location.py, jumpscale/packages/threebot_deployer/chats/change_size.py, jumpscale/packages/threebot_deployer/chats/restart_threebot.py, jumpscale/packages/threebot_deployer/chats/threebot.py, jumpscale/sals/marketplace/apps_chatflow.py, jumpscale/sals/marketplace/deployer.py
When 3bot deployment fails, the user will lose the money sent to the explorer directly
Add refund using billing package to use intermediate wallet that will be responsible to refund the user in case the pool extension failed
https://github.com/threefoldtech/js-sdk/issues/3170
=> Add refund for failed pool extensions in threebot deployer

jumpscale/sals/reservation_chatflow/deployer.py, jumpscale/sals/vdc/vmachine.py
there was a bug in the create VM that lead to reserve more than one public IP for the VM,  issue #3239 
this PR should fix the issue above.
- remove the `get_public_ip` call in `VirtualMachineDeployer`, as we already call `create_public_ip` from another part of the code.
- closes #3239
=> fix VM multiple public ips reservation

jumpscale/sals/vdc/grace_period.py
The VDC enters the grace period when the VDC has one day remaining to expire.
=> The vdc enters the grace period when the vdc has one day remaining to expire

jumpscale/sals/vdc/kubernetes.py
fix for "Error: uninstall: Release not loaded: traefik: release: not found" which shows in the logs when the UpgradeTraefik service runs.
```
[-] threebot: 2021-07-18 15:54:10.710 | INFO     | upgrade_traefik:job:16 - Upgrade Traefik Service:: Updating traefik from 2.4.9 to 2.4.8
...
[-] threebot: 2021-07-18 15:54:17.320 | DEBUG    | jumpscale.sals.kubernetes.manager:_execute:45 - kubernetes manager: helm --kubeconfig /root/sandbox/cfg/vdc/kube/samehabouelsaad/dev18072021.yaml --namespace kube-system delete traefik
[-] threebot: 2021-07-18 15:54:17.333 | DEBUG    | jumpscale.sals.kubernetes.manager:_execute:45 - kubernetes manager: helm --kubeconfig /root/sandbox/cfg/vdc/kube/samehabouelsaad/dev18072021.yaml --namespace k3os-system delete traefik
[-] threebot: Traceback (most recent call …
```
=> fixing err "uninstall: Release not loaded: traefik"

jumpscale/packages/backup/services/system_backup.py
removing the push notifications and the alerts that related to system-backup service not configured,
now the UI will show the related alerts and notifications only when the service is configured in the system.
https://github.com/threefoldtech/tf_support/issues/6
=> removing the push notifications and the alerts related to system-backup service 

jumpscale/clients/stellar/stellar.py
This reverts commit b7c2a555b5d741fcad74fe548689a95cefe6f76b.
Restore stellar original nodes
- https://github.com/threefoldtech/tf_operations/issues/250
=> Revert "Update stellar endpoint to use the new node (#3280)"

jumpscale/packages/vdc_dashboard/sals/vdc_dashboard_sals.py
handle the case when the deployed solution has multiple k8s deployments or stateful-sets and make sure the solution will appear only once
fix issue #3302
filtering the solutions using the instance name.
closes #3302
=> fix for duplicated solutions in VDC dashboard

jumpscale/clients/stellar/stellar.py, jumpscale/servers/gedis/server.py
- calling disconnect was never reached
- for stellar on retries we should yield the control back to the event loop
tries to address #3262 #3101 #3298
=> Development redisdisconnect

jumpscale/packages/vdc_dashboard/bottle/api/deployments.py
Validate VDC admin suffix ends with `.3bot` and if it is not ended `3bot` we append it.
- we updated end point `/api/admins/add`
jumpscale/packages/vdc_dashboard/bottle/api/deployments.py
https://github.com/threefoldtech/js-sdk/issues/3265
=> validate vdc admin suffix ends with .3bot

jumpscale/packages/vdc_dashboard/frontend/components/vdcSettings/Wallet.vue
Fixed qrcode issue not showing unless you visit wallet information page before API loads
Added creating wallet QRCode on component creation
jumpscale/packages/vdc_dashboard/frontend/components/vdcSettings/Wallet.vue
https://github.com/threefoldtech/js-sdk/issues/3267
=> Development wallet qrcode

jumpscale/packages/vdc_dashboard/frontend/components/vdcSettings/Admins.vue
Removed the ability to remove the last admin in vdc
Removed close icon whenever there is only one user
jumpscale/packages/vdc_dashboard/frontend/components/vdcSettings/Admins.vue
https://github.com/threefoldtech/js-sdk/issues/3266
=> Development last admin remove

jumpscale/packages/farmmanagement/frontend/views/farmmanagement/farmmanagement.js
Fixing the country listing while adding new farm in farm management 
- Give the countries the right scope to be called right
jumpscale/packages/farmmanagement/frontend/views/farmmanagement/farmmanagement.js### Related Issues
https://github.com/threefoldtech/js-sdk/issues/3301
=> fix farm mangment countries listing

jumpscale/packages/admin/actors/admin.py, jumpscale/packages/admin/frontend/api.js, jumpscale/packages/admin/frontend/components/settings/AddIdentity.vue, jumpscale/packages/admin/frontend/components/settings/AdminConfirmation.vue, jumpscale/packages/admin/frontend/components/settings/IdentityInfo.vue, jumpscale/packages/admin/frontend/components/settings/Settings.vue
1. Validate that identity cannot be set as default when there is no admins expect via confirmation message
2. while creating new identity we set current user on admins list
3. Added admins list in ui & server for identity
4. Removed code duplication from Setting.vue `jumpscale/packages/admin/frontend/components/settings/Settings.vue`
-while adding a new identity:
- Add the logged-in user to admins
- Add comma-separated admins
- while setting an identity to be the default and this one doesn't have admins, we have to show a confirmation message that there are no admins
jumpscale/packages/admin/frontend/components/settings/IdentityInfo.vue
jumpscale/packages/admin/frontend/components/settings/AdminConfirmation.vue
jumpscale/packages/admin/frontend/components/settings/Settings.vue …
=> Allow to define admins while creating identity

jumpscale/packages/vdc_dashboard/frontend/components/vdcSettings/S3.vue
Fixed non updating issue caused by using `computed` property in vue
Change computed zdbs into method
jumpscale/packages/vdc_dashboard/frontend/components/vdcSettings/S3.vue
https://github.com/threefoldtech/js-sdk/issues/3263
=> Development storage containers cache

jumpscale/packages/vdc_dashboard/frontend/components/vdcSettings/Home.vue, jumpscale/packages/vdc_dashboard/frontend/components/vdcSettings/VirtualMachine.vue
- Update virtual machine component to load its data (VMs) using created event
- while deletion we raise an event in which we remove the delete VM
load data in created event
jumpscale/packages/vdc_dashboard/frontend/components/vdcSettings/VirtualMachine.vue
https://github.com/threefoldtech/js-sdk/issues/3296
=> VDC dashboard: fix reloading vdc info after create/delete

jumpscale/packages/vdc_dashboard/bottle/api/deployments.py, jumpscale/packages/vdc_dashboard/scripts/update.sh
- updating from the UI or `update` rest API url endpoint without specifying branch param will update using the latest remote tag.
- now `update.sh` script can work with git tag ref too. before it was accepted only a branch name.
- modifying the update API controller to check the code from the latest remote release by default unless the `branch` param was given with a specific branch name. before it was checked the HEAD of the development branch.
=> Update VDC by latest tag

poetry.lock, pyproject.toml
- Bump jsng from 11.0b13 to 11.0b14
- release jssdk 11.5b10
=> Bump jsng from 11.0b13 to 11.0b14, release 11.5b10
